### PR TITLE
Fabric Text components use their text value as the accessibility name by default

### LINKED ISSUE #12030: Fabric `Text` components do not provide their text value (Name) to accessibility tree
### Problem Description

See that the Name property is not set for a `Text` component:
image

Not sure if this is part of incomplete work already tracked here: https://github.com/microsoft/react-native-windows/issues/11898

Relevant code as far as I can tell is here:
https://github.com/microsoft/react-native-windows/blob/a8aa86022e182b3b5b4afebd160fe8584f511ee4/vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp#L248-L252

### Steps To Reproduce

See https://github.com/chrisglein/artificial-chat/issues/119#issuecomment-1675496996

### Expected Results

Accessibility Name should default to the text value

### CLI version

12.0.0-alpha.6

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.23528
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 37.38 GB / 63.86 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.4.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.6.33829.357 (Visual Studio Community 2022)
    - 16.11.33801.447 (Visual Studio Community 2019)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0-nightly-20230721-ccc50ddd2
    wanted: 0.73.0-nightly-20230721-ccc50ddd2
  react-native-windows:
    installed: 0.0.0-canary.693
    wanted: 0.0.0-canary.693
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

_No response_

### Visual Studio Version

None

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by chrisglein**
## Description
Text components were showing in the accessibility tree but not with any value. This change has `UIA_NamePropertyId` default to the text value but can be overriden by `accessibilityLabel`. 

### Type of Change
- New feature (non-breaking change which adds functionality)

### Why
Text components were showing in the accessibility tree but not with any value.

Resolves #12030

### What
Added a virtual `DefaultAccessibleName()` that enables individual Fabric components to provide a fallback if `accessibilityLabel` isn't specified. Then `ParagraphComponentView` overrides this to provide its string value.

## Screenshots
Add any relevant screen captures here from before or after your changes. 
| Before | After |
|--------|--------|
| image| image|

## Testing
- Tested first in the Artifical Chat app
- Then tested in PlaygroundComposition on the Text test page to ensure that 1. Names started showing up, and 2. `accessibilityLabel` was still respected if specified.

## Changelog
Yes? This is somewhere between bug fix (expected behavior not working) and feature (it wasn't working before).

Fabric Text components use their text value as the accessibility name by default (if `accessibilityLabel` is not specified
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/12039)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp [hunk 1]
```diff
@@ -247,7 +247,8 @@ HRESULT __stdcall CompositionDynamicAutomationProvider::GetPropertyValue(PROPERT
     }
     case UIA_NamePropertyId: {
       pRetVal->vt = VT_BSTR;
-      auto wideName = ::Microsoft::Common::Unicode::Utf8ToUtf16(props->accessibilityLabel);
+      auto wideName = ::Microsoft::Common::Unicode::Utf8ToUtf16(
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp:250]: This would avoid the extra prop access and Utf8ToUtf16 on empty strings:
`auto wideName = props->accessibilityLabel.empty() ? ::Microsoft::Common::Unicode::Utf8ToUtf16(baseView->DefaultAccessibleName()) : L"";`

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp [hunk 2]
```diff
@@ -1072,7 +1072,10 @@ void CompositionBaseComponentView::updateAccessibilityProps(
       provider, UIA_IsKeyboardFocusablePropertyId, oldViewProps.focusable, newViewProps.focusable);
 
   winrt::Microsoft::ReactNative::implementation::UpdateUiaProperty(
-      provider, UIA_NamePropertyId, oldViewProps.accessibilityLabel, newViewProps.accessibilityLabel);
+      provider,
+      UIA_NamePropertyId,
+      oldViewProps.accessibilityLabel,
+      newViewProps.accessibilityLabel.empty() ? DefaultAccessibleName() : newViewProps.accessibilityLabel);
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp:1078]: No need to call newViewProps.accessibilityLabel again if we know its empty.

**Review by acoates-ms — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp (hunk 1 above)
Comment (jonthysell) [reply vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp:250]: @chrisglein You're logic looks fine.

@acoates-ms The logic in your example isn't equivalent as it would never use the `accessibilityLabel` value. If the label has a value, you want to use it, not report an empty string.

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp (hunk 2 above)
Comment (jonthysell) [reply vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp:1078]: @chrisglein This looks good.

**Review by jonthysell — APPROVED** [review]

**Comment by chiaramooney** [comment]
Didn't see the PR. Left some comments on the commit itself. https://github.com/chrisglein/react-native-windows/commit/a58cc6d29bce5905b59e9c7c27b81cc0f3ac2c69 

Can you add this PR to this issue https://github.com/microsoft/react-native-windows/issues/11901 in the "Name" row. And update status to In Progress?

Can you also verify that you've tested the FastRefresh case?

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp (hunk 1 above)
Comment (acoates-ms) [reply vnext/Microsoft.ReactNative/Fabric/Composition/CompositionDynamicAutomationProvider.cpp:250]: Yeah, sorry... read it wrong.

**Comment by chrisglein** [comment]
> Didn't see the PR. Left some comments on the commit itself. [chrisglein@a58cc6d](https://github.com/chrisglein/react-native-windows/commit/a58cc6d29bce5905b59e9c7c27b81cc0f3ac2c69)
> Can you add this PR to this issue #11901 in the "Name" row. And update status to In Progress?
> Can you also verify that you've tested the FastRefresh case?

- Addressed the comments on the commit with an additional commit.
- I've validated fast refresh on adding/changing/removing `accessibilityLabel` (and `accessibilityRole`, since I touched that line). 
  - Should I modify the [static text](https://github.com/microsoft/react-native-windows/blob/2ed6c533349c85289ea2ccc2bc0cc30864dc0cc1/packages/%40react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx#L860-L869) that's there right now to make it interactive with a Switch to add/remove role? Or is that overkill?
- And I've added a note to the issue.

**Review by chiaramooney — APPROVED** [review]
👍 Looks good to me! The switch to turn on/off setting accessibilityRole is probably not needed for now, but would be a good thing to have once we move into adding functional testing for Fabric. So up to you if you have the time.
