### PR TITLE
Use WinRT HTTP module in Desktop

### LINKED ISSUE #6089: RNTesterIntegrationTests::Logging Sporadically Crashes
See https://dev.azure.com/ms/react-native-windows/_build/results?buildId=111850&view=logs&jobId=6a576c64-c360-5968-e6e9-1b092bc6a5ec&j=6a576c64-c360-5968-e6e9-1b092bc6a5ec&t=9867c3b7-ae0e-5159-b6d0-da40bcc7a881

This was just re-enabled. From this + past experiences, we seem to have sporadic crashes with desktop ITs in general, but previously all other tests were disabled.

### PR DESCRIPTION
**Pull request by JunielKatarn**
Adds the UWP NetworkingModule to the shared code base, making it available to the Desktop projection.

- Deletes experimental test-only class `BeastHttpResource`.

### Pre-merge checklist
- [ ] Update XHRSample test: Validate a full request-response.

### Validation
- Test `RNTesterIntegrationTest::XHRSample`.

Closes #6089

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6094)

### CODE REVIEW

File: vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp [hunk 1]
```diff
@@ -88,6 +88,8 @@ TEST_CLASS (RNTesterIntegrationTests) {
     Assert::AreEqual(L"This is from console.error", result.Message.c_str());
   }
 
+  BEGIN_TEST_METHOD_ATTRIBUTE(XHRSample)
+  END_TEST_METHOD_ATTRIBUTE()
   TEST_METHOD(XHRSample) {
```
Comment (NickGerleman) [inline vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp:93]: I think we might have talked about this before, but XHRTest seems to start some async work then immediately pass. Given it was passing before for a fully stubbed module, I'm not sure how much validation we get from it.

```
  componentDidMount() {
    try {
      this._download();
    } catch (e) {
      console.error(e);
    }

    TestModule.markTestPassed(true);
  }
```

**Comment by NickGerleman** [comment]
OOC, what was the root cause of the crash in CI that we were seeing? I see this is marked to resolve that.

File: vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp (hunk 1 above)
Comment (JunielKatarn) [reply vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp:93]: Right now very little:
- Fail if the native module crashes.
- Catch any errors during the request send operation.

Now that we can use a complete and proven HTTP module, I'll rewrite this test so it does something relevant (before merging) :)

**Comment by JunielKatarn** [comment]
> OOC, what was the root cause of the crash in CI that we were seeing? I see this is marked to resolve that.

Yes!

Turns out the very unfinished/experimental HTTP module used only to showcase the XHRTest was being invoked during other, seemingly unrelated tests (i.e. Logging).

It's not very clear to me why the HTTP module would do anything in that test, but it was failing due to a dangling pointer, especially if the test was run with the VS debugger.

Plugging in the WinRT module, it passes very consistently.

I didn't analyze other tests thoroughly, but they some also ended up running an HTTP call.
Worth looking into, but for now I'm happy with fixing the intermittent failures.

**Review by NickGerleman — APPROVED** [review]
I think this is a good change. It's great to get rid of a module that is only being used by desktop integration tests (especially when devmain has a different module anyway).

If the goal here is to pave a way to use this in devmain instead of the Networking stuff there (I definitely think we should try to go this route), be aware there are some known issues with the UWP NetworkingModule, like #2460 and #6014.

Also I'm sure CI is telling you this, but you'll need to update the UWP projects for the namespace/path change that was made.

File: vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp (hunk 1 above)
Comment (NickGerleman) [reply vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp:93]: If you're rewriting the test, could you do so in the new IT project instead of the desktop IT's? Should be the same coverage since they're testing the same module.

**Comment by JunielKatarn** [comment]
> If the goal here is to pave a way to use this in devmain instead of the Networking stuff there (I definitely think we should try to go this route), be aware there are some known issues with the UWP NetworkingModule, like #2460 and #6014.
> 

There is an issue with a security feature "baked" into Office's HTTP module.
I'd really like to use this impl instead, but this would require very smart refactoring of the Office side, or porting such extended functionality into this side.

> Also I'm sure CI is telling you this, but you'll need to update the UWP projects for the namespace/path change that was made.

Already fixing...

File: vnext/src/IntegrationTests/XHRTest.js [hunk 2]
```diff
@@ -31,78 +31,83 @@ class XHRTest extends React.Component<{}, Object> {
...
+      this.setState({downloading: true});
+    });
 
-    this.setState({downloading: true});
   };
 
   componentDidMount() {
     try {
-      this._download();
+      async () => await this._download();
```
Comment (NickGerleman) [inline vnext/src/IntegrationTests/XHRTest.js:103]: As is, this doesn't actually call this._download. This defines an anonymous async function that isn't called.

You're not going to be able to await an async function in componentDidMount/use Effect. You'll probably just want to mark the test passed at the point in the test sequence where we know it's done.

Comment (NickGerleman) [reply vnext/src/IntegrationTests/XHRTest.js:103]: Alternatively, you could expand the async function, and Mark the test passed/failed within it.

Comment (JunielKatarn) [reply vnext/src/IntegrationTests/XHRTest.js:103]: > As is, this doesn't actually call this._download. This defines an anonymous async function that isn't called.
> 
> You're not going to be able to await an async function in componentDidMount/useEffect. You'll probably just want to mark the test passed at the point in the test sequence where we know it's done.

I think I should be able to, but I did skip invoking the promise: ` (async() => awiat this._downloadI())();`
I'll give it one more try, else add a follow-up task.

Comment (NickGerleman) [reply vnext/src/IntegrationTests/XHRTest.js:103]: The easier path if you're wanting to adapt this code is to probably just move the `TestModule.markTestPassed()` to a different place and not try to incorporate the async function.

We do have a wrapper to allow writing tests in async functions in the new ITs, but it's a little bit tricky. See the below in `TestDefinition.tsx` if you're interested (there are examples of calls to `functionTest` in `SampleTests.tsx`.

```
/**
 * Create a root component which runs the passed test function
 */
function createImperativeTestComponent(fn: TestFunction): React.FC {
  return () => {
    useEffect(() => {
      (async () => {
        try {
          const testResult = fn();
          if (testResult instanceof Promise) {
            await testResult;
          }
        } catch (ex) {
          // Need to force a redbox instead of YellowBox for unhandled
          // promise rejection
          ErrorUtils.getGlobalHandler()(ex);
          return;
        }

        TestModule.markTestPassed(true);
      })();
    });

    return <View />;
  };
}
```

**Review by NickGerleman — COMMENTED** [review]
This will still immediately pass. Invoking an async function here creates a promise that we let dangle, but doesn't wait on it.

This one will be tricky if you try to use promises and async functions.

**Review by NickGerleman — CHANGES_REQUESTED** [review]
We shouldn't leave around code we know is functionally broken. The XHRTest issue has been around for more than a year at this point.

Let's either properly fix it or remove it instead of kicking the can further. The current change has the same issue as before, where it seems to do some work at first glance but it immediately passes, which can be dangerous if people use it for validation.

**Comment by JunielKatarn** [comment]
> We shouldn't leave around code we know is functionally broken. The XHRTest issue has been around for more than a year at this point.
> 
> Let's either properly fix it or remove it instead of kicking the can further. The current change has the same issue as before, where it seems to do some work at first glance but it immediately passes, which can be dangerous if people use it for validation.

Please unblock this PR before leaving for the weekend.
I disagree in the criteria on blocking others' PRs based on an item that is NOT part of the change, but I'll gladly fix this test before submitting today (see the pre-merge checklist).

**Comment by NickGerleman** [comment]
Re: XHRSample, this change adds new code which bypasses the test in its entirety, as well as enables the faulty test. We can't check in new code like this.

The change also enables additional tests that have been causing engineers pain. Within the PR, we saw a failure of IntegrationTestHarnessTest which just calls TestModule without doing anything else. If it failed in the first run for this PR, the others will as well.

We need to have a discussion before we start enabling these tests again. We already have a meeting scheduled on Thursday to talk about desktop ITs, which would be a good opportunity. There's been a history of these tests causing failures that have gone unaddressed for some time, with folks sneaking in changes to disable them. I would like to avoid that happening again.

**Comment by NickGerleman** [comment]
It looks like we also did see the AsyncStorage fail for the previous commit as well. See https://github.com/microsoft/react-native-windows/pull/6094/checks?check_run_id=1167936774

**Comment by JunielKatarn** [comment]
> It looks like we also did see the AsyncStorage test fail for the previous commit as well. See https://github.com/microsoft/react-native-windows/pull/6094/checks?check_run_id=1167936774
> 
> If we're not able to repro these locally at all, something we've done for other cases is to collect crash dumps from CI machines. Since we're wanting to retire these tests, I'm not sure it's worth the effort in this case though.

It's worth mentioning that we're not wanting nor going to retire these tests.
What we want is a better mechanism to run them, for they provide otherwise non existing direct coverage for the Desktop DLL.

The new IT framework wouldn't change this.
Though, I will continue drilling down into these intermittent failures so they don't become an issue again. That said, the fail rate is not greater than the compiler heap memory issues we get on every other PR run.

**Review by tudorms — APPROVED** [review]
:shipit:
