### PR TITLE
Fix DisconnectFromView when the view is already disconnected

### LINKED ISSUE #8219: Crash in JS engine when using react-navigation
Hitting a crash on launch when using react-navigation native, stack, etc.
This is @dstaley's repro that I adapted to simplify it: https://github.com/asklar/repro-navigation-crash

After fixing #8218 , there is still a crash when using Direct Debugging (Chakra):

<details title="stack trace">
```

	KernelBase.dll!RaiseException(unsigned long dwExceptionCode, unsigned long dwExceptionFlags, unsigned long nNumberOfArguments, const unsigned long * lpArguments) Line 937	C
 	msvcrt.dll!7735aab8()	Unknown
 	msvcrt.dll![Frames below may be incorrect and/or missing, no symbols loaded for msvcrt.dll]	Unknown
 	Chakra.dll!Js::JavascriptExceptionOperators::DoThrow(class Js::JavascriptExceptionObject *,class Js::ScriptContext *)	Unknown
 	Chakra.dll!Js::JavascriptExceptionOperators::ThrowExceptionObjectInternal(class Js::JavascriptExceptionObject *,class Js::ScriptContext *,bool,bool,void *,bool)	Unknown
 	Chakra.dll!Js::JavascriptExceptionOperators::ThrowExceptionObject(class Js::JavascriptExceptionObject *,class Js::ScriptContext *,bool,void *,bool)	Unknown
 	Chakra.dll!Js::JavascriptExceptionOperators::Throw(void *,class Js::ScriptContext *)	Unknown
 	Chakra.dll!Js::JavascriptError::ThrowReferenceError(class Js::ScriptContext *,int,unsigned short const *)	Unknown
 	Chakra.dll!Js::JavascriptOperators::OP_GetRootProperty(void *,int,class Js::PropertyValueInfo *,class Js::ScriptContext *)	Unknown
 	Chakra.dll!Js::JavascriptOperators::PatchGetRootValueNoFastPath_Var(class Js::FunctionBody * const,struct Js::InlineCache * const,unsigned int,void *,int)	Unknown
 	Chakra.dll!Js::ProfilingHelpers::ProfiledLdFld<1,0,0>()	Unknown
 	Chakra.dll!Js::ProfilingHelpers::ProfiledLdFldForTypeOf<1,0,0>()	Unknown
 	Chakra.dll!Js::InterpreterStackFrame::OP_ProfiledGetRootPropertyForTypeOf<struct Js::OpLayoutT_ElementRootCP<struct Js::LayoutSizePolicy<1> > const >(struct Js::OpLayoutT_ElementRootCP<struct Js::LayoutSizePolicy<1> > const *)	Unknown
 	Chakra.dll!Js::InterpreterStackFrame::ProcessWithDebuggingExtendedMediumLayoutPrefix(unsigned char const *)	Unknown
 	Chakra.dll!Js::InterpreterStackFrame::ProcessWithDebugging(void)	Unknown
 	Chakra.dll!Js::InterpreterStackFrame::DebugProcess(void)	Unknown
 	Chakra.dll!Js::InterpreterStackFrame::InterpreterHelper()	Unknown
 	Chakra.dll!Js::InterpreterStackFrame::InterpreterThunk(class Js::JavascriptCallStackLayout *)	Unknown
 	0ef40fe2()	Unknown
 	Chakra.dll!Js::JavascriptFunction::CallFunction<1>()	Unknown
 	Chakra.dll!<lambda>(void)()	Unknown
 	Chakra.dll!ThreadContext::SafeReentrantCall<<lambda>(void)>()	Unknown
 	Chakra.dll!Js::ScriptContext::DebugProfileProbeThunk(class Js::RecyclableObject *,struct Js::CallInfo,...)	Unknown
 	Chakra.dll!Js::JavascriptFunction::CallFunction<1>()	Unknown
 	Chakra.dll!Js::JavascriptFunction::CallRootFunctionInternal()	Unknown
 	Chakra.dll!Js::JavascriptFunction::CallRootFunction()	Unknown
 	Chakra.dll!Js::JavascriptFunction::CallRootFunction(struct Js::Arguments,class Js::ScriptContext *,bool)	Unknown
 	Chakra.dll!<lambda>(void)()	Unknown
 	Chakra.dll!ContextAPIWrapper_Core<0,<lambda_d826c7ade3c811442ed6c1dc7d80661f>>()	Unknown
 	Chakra.dll!ContextAPIWrapper<0,<lambda>(void)>()	Unknown
 	Chakra.dll!RunScriptCore(void *,unsigned char const *,unsigned int,enum LoadScriptFlag,unsigned long,unsigned short const *,bool,enum _JsParseScriptAttributes,bool,void * *)	Unknown
 	Chakra.dll!_JsRunScript@16()	Unknown
 	Microsoft.ReactNative.dll!Microsoft::JSI::SystemChakraRuntime::evaluateJavaScriptSimple(const facebook::jsi::Buffer & buffer, const std::string & sourceURL) Line 71	C++
 	Microsoft.ReactNative.dll!Microsoft::JSI::ChakraRuntime::evaluateJavaScript(const std::shared_ptr<facebook::jsi::Buffer const> & buffer, const std::string & sourceURL) Line 161	C++
 	Microsoft.ReactNative.dll!facebook::react::JSIExecutor::loadBundle(std::unique_ptr<facebook::react::JSBigString const ,std::default_delete<facebook::react::JSBigString const>> script, std::string sourceURL) Line 158	C++
 	Microsoft.ReactNative.dll!facebook::react::NativeToJsBridge::loadBundle::__l2::<lambda>(facebook::react::JSExecutor * executor) Line 146	C++
 	Microsoft.ReactNative.dll!std::invoke<void <lambda>(facebook::react::JSExecutor *) &,facebook::react::JSExecutor *>(facebook::react::NativeToJsBridge::loadBundle::__l2::void <lambda>(facebook::react::JSExecutor *) & _Obj, facebook::react::JSExecutor * && _Arg1) Line 1610	C++
 	Microsoft.ReactNative.dll!std::_Invoker_ret<void,1>::_Call<void <lambda>(facebook::react::JSExecutor *) &,facebook::react::JSExecutor *>(facebook::react::NativeToJsBridge::loadBundle::__l2::void <lambda>(facebook::react::JSExecutor *) & _Func, facebook::react::JSExecutor * && <_Vals_0>) Line 745	C++
 	Microsoft.ReactNative.dll!std::_Func_impl_no_alloc<void <lambda>(facebook::react::JSExecutor *),void,facebook::react::JSExecutor *>::_Do_call(facebook::react::JSExecutor * && <_Args_0>) Line 921	C++
 	Microsoft.ReactNative.dll!std::_Func_class<void,facebook::react::JSExecutor *>::operator()(facebook::react::JSExecutor * <_Args_0>) Line 968	C++
 	Microsoft.ReactNative.dll!facebook::react::NativeToJsBridge::runOnExecutorQueue::__l2::<lambda>() Line 311	C++
 	Microsoft.ReactNative.dll!std::invoke<void <lambda>(void) &>(facebook::react::NativeToJsBridge::runOnExecutorQueue::__l2::void <lambda>(void) & _Obj) Line 1586	C++
 	Microsoft.ReactNative.dll!std::_Invoker_ret<void,1>::_Call<void <lambda>(void) &>(facebook::react::NativeToJsBridge::runOnExecutorQueue::__l2::void <lambda>(void) & _Func) Line 745	C++
 	Microsoft.ReactNative.dll!std::_Func_impl_no_alloc<void <lambda>(void),void>::_Do_call() Line 921	C++
 	Microsoft.ReactNative.dll!std::_Func_class<void>::operator()() Line 968	C++
 	Microsoft.ReactNative.dll!Mso::React::MessageDispatchQueue::tryFunc(const std::function<void __stdcall(void)> & func) Line 41	C++
 	Microsoft.ReactNative.dll!Mso::React::MessageDispatchQueue::runOnQueue::__l2::<lambda>() Line 36	C++
 	Microsoft.ReactNative.dll!Mso::Details::FunctionObjectWrapper<void <lambda>(void),void>::Invoke() Line 166	C++
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<void __stdcall(void)> && task, std::optional<std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000>>>> endTime) Line 206	C++
 	Microsoft.ReactNative.dll!Mso::LooperScheduler::RunLoop(const Mso::WeakPtr<Mso::LooperScheduler> & weakSelf) Line 49	C++
 	Microsoft.ReactNative.dll!Mso::LooperScheduler::<lambda>() Line 36	C++
 	Microsoft.ReactNative.dll!std::invoke<void <lambda>(void)>(Mso::LooperScheduler::void <lambda>(void) && _Obj) Line 1586	C++
 	Microsoft.ReactNative.dll!std::thread::_Invoke<std::tuple<void <lambda>(void)>,0>(void * _RawVals) Line 56	C++
 	ucrtbased.dll!thread_start<unsigned int (__stdcall*)(void *),1>(void * const parameter) Line 97	C++
 	kernel32.dll!76276739()	Unknown
 	ntdll.dll!___RtlUserThreadStart@8()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
```

### PR DESCRIPTION
**Pull request by asklar**
DisconnectFromView can be called on an view that has no connected tag.
Also fix exceptions to be thrown by value as the rest of the code expects them to be

Fixes #8219 
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8220)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp [hunk 1]
```diff
@@ -41,7 +41,7 @@ PropsAnimatedNode::PropsAnimatedNode(
 
 void PropsAnimatedNode::ConnectToView(int64_t viewTag) {
   if (m_connectedViewTag != s_connectedViewTagUnset) {
-    throw new std::invalid_argument(
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp:44]: 😞

**Review by NickGerleman — APPROVED** [review]
