### PR TITLE
Fix issue with new arch cpp-app apps not finding the bundle in release builds

### LINKED ISSUE #12752: Fabric canary app crashes on launch in Release builds
### Problem Description

Here's the failure:

```
artificialChat.exe!winrt::throw_hresult(const winrt::hresult result) Line 4938	C++
[Inline Frame] artificialChat.exe!winrt::check_hresult(const winrt::hresult) Line 5036	C++
[Inline Frame] artificialChat.exe!winrt::get_activation_factory(const winrt::param::hstring &) Line 6059	C++
artificialChat.exe!winrt::impl::factory_cache_entry<winrt::Microsoft::UI::Dispatching::DispatcherQueueController,winrt::Microsoft::UI::Dispatching::IDispatcherQueueControllerStatics>::call<winrt::Microsoft::UI::Dispatching::DispatcherQueueController (__cdecl*)(winrt::Microsoft::UI::Dispatching::IDispatcherQueueControllerStatics const &)>(winrt::Microsoft::UI::Dispatching::DispatcherQueueController(*)(const winrt::Microsoft::UI::Dispatching::IDispatcherQueueControllerStatics &) && callback) Line 6290	C++
[Inline Frame] artificialChat.exe!winrt::impl::call_factory_cast(winrt::Microsoft::UI::Dispatching::DispatcherQueueController::CreateOnCurrentThread::__l2::winrt::Microsoft::UI::Dispatching::DispatcherQueueController <lambda>(const winrt::Microsoft::UI::Dispatching::IDispatcherQueueControllerStatics &) &&) Line 6351	C++
[Inline Frame] artificialChat.exe!winrt::Microsoft::UI::Dispatching::DispatcherQueueController::CreateOnCurrentThread() Line 560	C++
artificialChat.exe!WinMain(HINSTANCE__ * instance, HINSTANCE__ * __formal, char * __formal, int showCmd) Line 95	C++
```

```
Exception thrown at 0x00007FFAE6144D8C (KernelBase.dll) in artificialChat.exe: WinRT originate error - 0x80040154 : 'Class not registered'.
Exception thrown at 0x00007FFAE6144D8C in artificialChat.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x0000002D322FF520.
Unhandled exception at 0x00007FFAE6144D8C in artificialChat.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x0000002D322FF520.
```

### Steps To Reproduce

1. Follow these steps to set up a new Fabric app on canary 769: https://github.com/microsoft/react-native-windows/wiki/Using-the-new-architecture-templates
3. Build the app for Release x64 in Visual Studio
4. Hit exception on app startup

(note that app does run correctly when done via command line `yarn windows` (Debug, connected to metro))

### Expected Results

Able to launch a Retail build

### CLI version

13.0.0

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.23656
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 48.49 GB / 63.86 GB
Binaries:
  Node:
    version: 18.16.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.9.34607.119 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0-nightly-20240102-05ec058ac
    wanted: 0.74.0-nightly-20240102-05ec058ac
  react-native-windows:
    installed: 0.0.0-canary.769
    wanted: ^0.0.0-canary.769
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

### Snack, code example, screenshot, or link to a repository

Branch with the app updated to canary 769 [here](https://github.com/chrisglein/artificial-chat/compare/fabric...fabric_updatedTemplate?expand=1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)

That's for an existing app. But this repros on a brand new app from template. And is also reproing for the Fabric conversion of the Gallery app in progress.

### PR DESCRIPTION
**Pull request by jonthysell**
## Description

The new cpp-app template (and related apps `playground-composition` and `e2e-test-app-fabric`) were all set with an invalid `BundleRootPath`. This causes the app to throw an error because it can't parse the given path from the URI, furthermore, since it was a URI based on the current working directory, it might not even be the right directory to load the bundle from.

This PR fixes the issue by instead using the correct `file://` URI scheme and also looking for the bundle path relative to the location of the app exe itself. This PR also re-aligns the apps to use the similar instance settings setup of the older UWP app (using both the `BUNDLE` and `_DEBUG` macros appropriately).

Partially resolves #12752

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
So that release builds work for the apps using the new template.

### What
See above.

## Screenshots
image

## Testing
Tested a new app works with the changes.

## Changelog
Should this change be included in the release notes: _yes_

Fixed issue with new arch cpp-app apps not finding the bundle in release builds
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/12754)

### CODE REVIEW

File: packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp [hunk 1]
```diff
@@ -62,26 +62,34 @@ void UpdateRootViewSizeToAppWindow(
...
+
+  // Include any autolinked modules
+  //RegisterAutolinkedNativeModulePackages(host.PackageProviders());
+
   host.PackageProviders().Append(winrt::make<RNTesterAppReactPackageProvider>());
   host.PackageProviders().Append(winrt::AutomationChannel::ReactPackageProvider());
 
+#if BUNDLE
   host.InstanceSettings().JavaScriptBundleFile(L"index.windows");
-  host.InstanceSettings().DebugBundlePath(L"index");
```
Comment (marlenecota) [inline packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp:76]: Is this not needed?

Comment (jonthysell) [reply packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/RNTesterApp-Fabric.cpp:76]: It doesn't appear to be needed anymore, since now we set JavaScriptBundleFile to index in debug (like we did for UWP)

**Review by chrisglein — APPROVED** [review]

**Review by chiaramooney — APPROVED** [review]
