### PR TITLE
Avoid crash when unsupported facade is given - `react-native-paper` button fix

### LINKED ISSUE #6430: button click from react-native-paper lib crashes on windows
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:

```
System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 9.18 GB / 15.94 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 25, 29
      Build Tools: 25.0.3, 26.0.1, 28.0.3, 29.0.2
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a... | Intel x86 Atom_64, a...google_apis | Google APIs Intel x86 Atom Sys...
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.16299.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  2.3.0.0 AI-162.4069837
    Visual Studio: 15.4.27004.2002 (Visual Studio Enterprise 2017), 16.7.30621.155 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_262 - C:\Program Files\OpenJDK\openjdk-8u262-b10\bin\javac.EXE
    Python: 2.7.18 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. steps desribed in https://github.com/callstack/react-native-paper/issues/2329

## Expected Results

it should not crash ;)

## other

im not sure if this is something to be fixed in the windows platform or the rn-paper lib, thats why im cross-posting here. If it is out of scope feel free to close this issue.

### PR DESCRIPTION
**Pull request by BartoszKlonowski**
This pull request fixes #6430 

It creates new enumeration value that indicates whether unsupported facade type is specified.

---

This fix delivers new facade type: `FacadeType::None` which indicates that a given type is not supported by the framework. It avoids a crash because if `None` is noticed the animation is just not started and further processing is omitted.

The usage of this type is to first get the result of `StringToFacadeType()` method, and only then check it against the `None` value to see whether an existing and supported value is used.

Another change is to modify the default return value of `FacadeType`, which was previously set to `progress` and now it's `None` instead of throwing an assert.

---

These changes were tested on the real example application given in the original [issue](https://github.com/callstack/react-native-paper/issues/2329).
The button marked as a crashing button now does not crash and animates correctly:
RNPaperCrashExample

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h [hunk 1]
```diff
@@ -41,6 +44,6 @@ inline FacadeType StringToFacadeType(const std::string &value) noexcept {
   if (value == "perspective")
     return FacadeType::Perspective;
 
-  assert(value == "progress");
-  return FacadeType::Progress;
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h:45]: with this change we won't ever use the progress facade

File: vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp [hunk 2]
```diff
@@ -89,7 +89,9 @@ void PropsAnimatedNode::UpdateView() {
           MakeAnimation(styleEntry.second, styleEntry.first);
         }
       } else if (const auto &valueNode = manager->GetValueAnimatedNode(entry.second)) {
-        MakeAnimation(entry.second, StringToFacadeType(entry.first));
+        const auto &facade = StringToFacadeType(entry.first);
+        if (facade != FacadeType::None)
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp:93]: please add braces to single-line if blocks (here and below)

File: vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h (hunk 1 above)
Comment (BartoszKlonowski) [reply vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h:45]: Sure, I didn't notice that `progress` is returned only here, without previous `if`.
I brought back the `FacadeType::Progress` handling.

**Review by asklar — APPROVED** [review]

**Review by asklar — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]

**Comment by BartoszKlonowski** [comment]
@asklar @jonthysell Thank you!
