### PR TITLE
[0.63] Set Content-Length on the content object and not on the request itself.

### LINKED ISSUE #6407: XMLHttpRequest doesn't work with Content-Length property
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
```
4.13.0
```

2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.78 GB / 15.62 GB
  Binaries:
    Node: 14.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30517.126 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Run the following code. 
2. Press both buttons. 
3. Observer the debug log.

First button works fine, the second one errors out (see what actually happens in the end of this issue).

**Sample Code**

```javascript
import React from 'react';
import {
  SafeAreaView,
  Text,
  StatusBar,
  Button,
} from 'react-native';

const testXmlHttpRequest = (addContentSize) => {
    let xhr = new XMLHttpRequest();
    xhr.onreadystatechange = () => {
        console.log(`request done readyState=${xhr.readyState} status=${xhr.status}`);
    };

    xhr.onerror = () => {
      console.log("an error occured");
    }
    xhr.open("GET", "https://wikipedia.org", true);

    if (addContentSize) {
      xhr.setRequestHeader('Content-Length', 0);
    }

    xhr.send();
}

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Button title="Test Without Content-Length" onPress={() => testXmlHttpRequest(false)} />
        <Button title="Test With Content-Length" onPress={() => testXmlHttpRequest(true)} />
      </SafeAreaView>
    </>
  );
};

export default App;
```

## Expected Results
Requests for both buttons don't fail.

## Snack, code example, screenshot, or link to a repository:

The code is failing in NetworkingModule.cpp:289 with the following exception `"Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects."`

I know that my example uses a GET request where `Content-Length` makes no sense, but some libraries (like Amazon's Amplify) set it for POST requests. So it is important for compatibility reasons.

This example also works correctly (both buttons succeed) on every other platform I tested (macOS, iOS, Android).

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #6407

I made it similarly to `Content-Encoding`. I'm open for suggestions if something else needs to be adjusted here.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6414)

### CODE REVIEW

**Comment by mandrigin** [comment]
if needed, I can open another PR for the main branch.

**Comment by mandrigin** [comment]
I opened #6415 just in case (because likely I'm in a very different timezone than core contributors). Feel free to close on of these PRs in favour of the correct one.

**Comment by dannyvv** [comment]
@mandrigin: To pass the validation could you run `yarn change` at the root of your repo and push the changes? This will introduce a change file that we use to keep track of semantic versioning the various packages in our repo.

**Comment by mandrigin** [comment]
@dannyvv done

File: vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp [hunk 1]
```diff
@@ -229,11 +229,16 @@ void NetworkingModule::NetworkingHelper::OnRequestError(int64_t requestId, std::
...
     winrt::Windows::Web::Http::Headers::HttpMediaTypeHeaderValue contentType,
-    std::string contentEncoding) {
+    std::string contentEncoding,
+    std::string contentLength) {
   if (contentType != nullptr)
     content.Headers().ContentType(contentType);
   if (!contentEncoding.empty())
     content.Headers().ContentEncoding().ParseAdd(Microsoft::Common::Unicode::Utf8ToUtf16(contentEncoding));
+  if (!contentLength.empty()) {
+    auto contentLengthHeader = atoi(contentLength.c_str());
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp:239]:
```suggestion
    auto contentLengthHeader = _atoi64(contentLength.c_str());
```

File: vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp [hunk 2]
```diff
@@ -229,11 +229,16 @@ void NetworkingModule::NetworkingHelper::OnRequestError(int64_t requestId, std::
...
+    content.Headers().ContentLength() = contentLengthHeader;
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp:240]: it's interesting that this works (because ContentLength returns an IReference), but consider writing this as all the other idiomatic cppwinrt in this file:

```suggestion
    content.Headers().ContentLength(contentLengthHeader);
```

File: vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp [hunk 3]
```diff
@@ -229,11 +229,16 @@ void NetworkingModule::NetworkingHelper::OnRequestError(int64_t requestId, std::
 void AttachContentHeaders(
     winrt::Windows::Web::Http::IHttpContent content,
     winrt::Windows::Web::Http::Headers::HttpMediaTypeHeaderValue contentType,
-    std::string contentEncoding) {
+    std::string contentEncoding,
+    std::string contentLength) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp:233]: you could parse the value earlier and pass it here as either `uint64_t` with a sentinel value like (uint64_t)-1 to denote "unspecified", or as a `std::optional<uint64_t>`

Comment (mandrigin) [reply vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp:233]: makes sense, but I've seen that `ContentEncoding` is using `ParseAdd`, so I thought that would keep parsing to the same method. But I can move the parsing if needed.

**Review by asklar — APPROVED** [review]

**Comment by asklar** [comment]
Thanks for making this change @mandrigin. I just realized that this PR is for 0.63. Can you please retarget to master, and then we can discuss whether this can be backported to 63?

**Comment by mandrigin** [comment]
@asklar the code was moved in master so I opened another PR for it with the same set of changes: https://github.com/microsoft/react-native-windows/pull/6415

I didn't expect that the review would be so quick, thanks for that!

**Comment by mandrigin** [comment]
@asklar if you are okay with that, I can close this PR and just keep #6415 as the main one. I ported your suggested changes to it as well.

**Comment by mandrigin** [comment]
@asklar, @Khalef1 approved the backport to 0.63 so I figured we can just reopen and merge this PR. 
It looks like I can’t myself reopen tut myself :-(.

**Review by dannyvv — APPROVED** [review]

**Comment by dannyvv** [comment]
Copying backport approved tag from main branch commit: #6415

**Comment by dannyvv** [comment]
@msftbot rebase

**Review by Khalef1 — APPROVED** [review]
