### PR TITLE
Fix crash during instance destruction if there are outstanding animations

### LINKED ISSUE #6271: Reloading an app while a native animation is in progress results in a crash
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
System:
    OS: Windows 10 10.0.19042
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 13.70 GB / 31.91 GB
  Binaries:
    Node: 10.21.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.5
  Installed UWP SDKs:
    10.0.18362.0
    10.0.19041.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

## Steps To Reproduce
Reload an app while an animation which uses native driver is running.

1. Create a new react native app (typescript template) with the instructions here https://microsoft.github.io/react-native-windows/docs/getting-started
2. Replace App.tsx with the code bellow
3. launch the app
4. Press 'r' in the metro console to reload the app

## Expected Results
App reloads and does not crash.

Note this does not reproduce on rnw 0.60

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */

import React, { useEffect } from 'react';
import { useState } from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
  Animated,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

declare const global: {HermesInternal: null | {}};

const App = () => {

  const [opacity] = useState(new Animated.Value(1));

  const bodyStyle = {
    ...styles.body,
    opacity
  };

  useEffect(() => {
    Animated.timing(opacity, {
      toValue: 0,
      duration: 10000000,
      useNativeDriver: true,
  }).start();
  }, [])

  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <Header />
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
          <Animated.View style={bodyStyle}>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Step One</Text>
              <Text style={styles.sectionDescription}>
                Edit <Text style={styles.highlight}>App.tsx</Text> to change this
                screen and then come back to see your edits.
              </Text>
            </View>
            <LearnMoreLinks />
          </Animated.View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});

export default App;
```

### PR DESCRIPTION
**Pull request by acoates-ms**
Fixes #6271

We were never notifying JS to detach a root view when the rootview went away.  So JS would not send commands to clean up animations from that rootview.  

There was an issue in ReactRootControl where it would clear out the UI the JS created as part of reload, which would cause a crash when the JS then tried to remove that UI.

We were not properly quitting the main UI queue, so things would get run there after the instance was gone.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6289)

### CODE REVIEW

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 1]
```diff
@@ -14,7 +15,11 @@ BatchingQueueThread::BatchingQueueThread(
 BatchingQueueThread::~BatchingQueueThread() noexcept {}
 
 void BatchingQueueThread::runOnQueue(std::function<void()> &&func) noexcept {
-  ThreadCheck();
+  std::lock_guard<std::mutex> lck(m_mutex);
```
Comment (dannyvv) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:18]: Just checking: Is a mutex not a bit too heavy here in the queue processing and scheduling? Should we use an interlock compareexchange?

**Review by dannyvv — APPROVED** [review]

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 2]
```diff
@@ -62,9 +69,17 @@ void BatchingQueueThread::runOnQueueSync(std::function<void()> && /*func*/) noex
...
+  {
+    std::lock_guard<std::mutex> lck(m_mutex);
+
+    m_quit = true;
+
+    if (m_taskQueue)
+      m_taskQueue->emplace_back([&resetEvent]() { resetEvent.Set(); });
+  }
+
+  resetEvent.Wait();
```
Comment (vmoroz) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:82]: >resetEvent.Wait(); [](start = 2, length = 18)

Ideally we should wait only if the current queue does not have the thread access. Otherwise, it is going to be a deadlock. Can we do the m_queueThread.quitSynchronous() instead? We should call the onBatchComplete() before that.

**Review by vmoroz — APPROVED** [review]
:shipit:

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 3]
```diff
@@ -56,15 +57,20 @@ void BatchingQueueThread::onBatchComplete() noexcept {
...
 void BatchingQueueThread::runOnQueueSync(std::function<void()> && /*func*/) noexcept {
   assert(false && "Not supported");
   std::terminate();
 }
 
 void BatchingQueueThread::quitSynchronous() noexcept {
-  // Used by OInstance
-  // assert(false && "Not supported");
-  // std::terminate();
+  std::lock_guard lck(m_mutex);
```
Comment (vmoroz) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:71]: >lock_guard [](start = 7, length = 10)

The new "fashion" is to use std::scoped_lock

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp [hunk 4]
```diff
@@ -16,6 +17,16 @@ NativeAnimatedModule::NativeAnimatedModule(Mso::CntPtr<Mso::React::IReactContext
...
 }
 
+NativeAnimatedModule::~NativeAnimatedModule() {
+  auto uiDispatcher =
+      winrt::Microsoft::ReactNative::implementation::ReactDispatcher::GetUIDispatcher(m_context->Properties());
+
+  // To make sure that we destroy UI components in UI thread.
+  if (!uiDispatcher.HasThreadAccess()) {
+    uiDispatcher.Post([maanger = std::move(m_nodesManager)]() {});
+  }
```
Comment (NikoAri) [inline vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp:27]: >} [](start = 2, length = 1)

What if we don't have thread access?

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp [hunk 5]
```diff
@@ -16,6 +17,16 @@ NativeAnimatedModule::NativeAnimatedModule(Mso::CntPtr<Mso::React::IReactContext
   m_nodesManager = std::make_shared<NativeAnimatedNodeManager>(NativeAnimatedNodeManager());
 }
 
+NativeAnimatedModule::~NativeAnimatedModule() {
+  auto uiDispatcher =
+      winrt::Microsoft::ReactNative::implementation::ReactDispatcher::GetUIDispatcher(m_context->Properties());
+
+  // To make sure that we destroy UI components in UI thread.
+  if (!uiDispatcher.HasThreadAccess()) {
+    uiDispatcher.Post([maanger = std::move(m_nodesManager)]() {});
```
Comment (NikoAri) [inline vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp:26]: >maanger [](start = 23, length = 7)

(nit) misspelled?

File: vnext/Shared/Threading/BatchingQueueThread.h [hunk 6]
```diff
@@ -27,12 +27,14 @@ struct BatchingQueueThread final : facebook::react::BatchingMessageQueueThread {
  private:
   void EnsureQueue() noexcept;
   void ThreadCheck() noexcept;
+  void postBatch() noexcept;
```
Comment (NikoAri) [inline vnext/Shared/Threading/BatchingQueueThread.h:30]: >postBatch [](start = 7, length = 9)

(nit) why some private Apis follow Camel casing, while others Pascal? Would be nice to align all private Apis :)

**Review by NikoAri — APPROVED** [review]
:shipit:

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp (hunk 4 above)
Comment (acoates-ms) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp:27]: Then the destruction of m_nodesManager will happen on the UI thread already
