### PR TITLE
Fix RedBox on topMouseLeave event.

### LINKED ISSUE #6738: RedBox about topMouseLeave when hovering away from RNTester bottom buttons
1. Launch Playground and load RNTester
2. Hover the mouse over the bottom buttons ("Components / APIs").
3. Move the mouse away from those buttons, wait a couple of seconds.

image

### PR DESCRIPTION
**Pull request by rectified95**
Fixes #6738 
In #6268 we accidentally dropped the `topMouseLeave` event's registration in ViewManagerBase.cpp, which led to it missing in the ViewConfig in JS. 

Verified in Chrome debugger that the 'Unsupported top level event type..' exception is longer thrown from ReactNativeRenderer-dev.js@2426

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6739)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp [hunk 1]
```diff
@@ -175,6 +175,7 @@ void ViewManagerBase::GetExportedCustomDirectEventTypeConstants(
   const PCWSTR eventNames[] = {// Generic events
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp:175]: this can be made `constexpr`

**Review by asklar — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp (hunk 1 above)
Comment (rectified95) [reply vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp]: done

**Comment by NickGerleman** [comment]
@rectified95 could you cherry pick this into 0.64?
