### PR TITLE
Fix Color Customization Bug During High Contrast Mode

### LINKED ISSUE #10207: Text styles can't be customized in high contrast mode
### Problem Description

When a high contrast theme is active on Windows, if I have custom styles set on some text (such as a link), those styles don't show up in the UI. It will set all text to the same color and text-decoration, regardless.

Screenshot example - the "Get help", "Give feedback", and "Unlink this PC" text should all be a shade of blue, and should have underlines when hovered over, but they're all white, and nothing happens on hover:

Screen Shot 2022-06-27 at 1 27 04 PM

### Steps To Reproduce

1. Make an app with a `<Text>` element and a `style` prop. Set the `color` to something bright and obvious.
2. Go into Windows 11 settings and choose the "Aquatic" high contrast theme
3. Go back to the app. The text will be white, no matter what color you chose.

### Expected Results

Ideally the text respects the styles applied to it.

### CLI version

0.66.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.25131
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 106.19 GB / 127.71 GB
  Binaries:
    Node: 16.9.1 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\node.EXE
    Yarn: 1.22.11 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\yarn.CMD
    npm: 7.21.1 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17134.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Enterprise 2019), 17.2.32602.215 (Visual Studio Enterprise 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.0 => 0.66.0
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

_No response_

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by chiaramooney**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)
-
### Why
When a high contrast theme is active on Windows, if I have custom styles set on some text (such as a link), those styles don't show up in the UI. It will set all text to the same color and text-decoration, regardless.

Resolves #10207

### What
Used HighContrastAdjustment property to disable XAML ignoring specified foreground color when "color" prop is specified. Property restored to application value once "color" prop returns to null. 

## Testing
Tested in Playground with multiple scenarios.  

NOTE: When backgroundColor is set, XAML will not adjust foreground color automatically. When foreground color is set, this is no issue. When foreground color is not set with "color" prop, color will remain RNW default and will not adjust with high contrast theme change. <Filing issue soon to track>

NOTE: Bug also appeared when testing react-native-xaml. Work needed to fix bug in that repo as well. <Filing Issue soon to track>

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10229)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Utils/PropertyUtils.h [hunk 1]
```diff
@@ -11,6 +11,7 @@
 #include <stdint.h>
 #include <winrt/Windows.Foundation.Metadata.h>
 #include <winrt/Windows.Foundation.h>
+#include <winrt/Windows.UI.Xaml.h>
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Utils/PropertyUtils.h:14]: don't use this header / namespace. Use the `xaml` namespace alias.

**Review by asklar — CHANGES_REQUESTED** [review]
needs updating for winui3

**Review by asklar — APPROVED** [review]
