### PR TITLE
Fix concurrency issue in NetworkingModule

### LINKED ISSUE #4174: Concurrency issue in NetworkingModule causes _STL_VERIFY to fail
### Environment

If you are using latest version:
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.6
2. `react-native run-windows --info`:
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 12.28 GB / 31.92 GB
  Binaries:
    Node: 11.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
    react-native-windows: 0.60.0-vnext.141 => 0.60.0-vnext.141
    rnpm-plugin-windows: 0.3.5 => 0.3.5
  Installed UWP SDKs:
    10.0.16299.0
    10.0.17134.0
    10.0.17749.0
    10.0.17763.0
    10.0.18362.0

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

1. In RNW app, make a large number of network requests so that NetworkModule.cpp gets hammered. (We use axios and we see this issue often after we kick off 800+ requests)

### Expected Behavior

No _STL_VERIFY asserts get hit.

### Actual Behavior

STL_VERIFY asserts get hit and the app is forced to close.

### Additional context

(Write any other additional context that may help in root causing the issue.)
image

image

The issue is that the large number of requests increases the chances that m_requests map gets modified while an add or erase is being done which causes the iterators to be invalidated.

### PR DESCRIPTION
**Pull request by lamxdoan**
Fix #4174 

- Add locking around modifications to m_requests map.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4179)

### CODE REVIEW

**Comment by vmoroz** [comment]
>   auto iter = m_requests.find(requestId);

Should we use mutex here as well?

---
Refers to: vnext/ReactUWP/Modules/NetworkingModule.cpp:342 in 80e32c9. [](commit_id = 80e32c9850559ce046ec4b079106b1d54eec2185, deletion_comment = False)

**Comment by lamxdoan** [comment]
>   auto iter = m_requests.find(requestId);

Yeah I think it makes sense to add it here as well.

---
In reply to: [591128047](https://github.com/microsoft/react-native-windows/pull/4179#issuecomment-591128047) [](ancestors = 591128047)

---
Refers to: vnext/ReactUWP/Modules/NetworkingModule.cpp:342 in 80e32c9. [](commit_id = 80e32c9850559ce046ec4b079106b1d54eec2185, deletion_comment = False)

**Comment by vmoroz** [comment]
It seems that your PR is missing a change file. Please run 'yarn change' to create it.

File: vnext/ReactUWP/Modules/NetworkingModule.cpp [hunk 1]
```diff
@@ -336,11 +339,17 @@ void NetworkingModule::NetworkingHelper::SendRequest(
...
 
 void NetworkingModule::NetworkingHelper::AbortRequest(int64_t requestId) noexcept {
-  auto iter = m_requests.find(requestId);
-  if (iter == end(m_requests))
-    return;
+  winrt::Windows::Foundation::IAsyncOperationWithProgress<
+    winrt::Windows::Web::Http::HttpResponseMessage, 
+    winrt::Windows::Web::Http::HttpProgress> httpRequest(nullptr);
+  {
+    std::scoped_lock(m_mutex);
```
Comment (vmoroz) [inline vnext/ReactUWP/Modules/NetworkingModule.cpp]: >( [](start = 20, length = 1)

There must be a variable name for the lock.

Comment (lamxdoan) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: Ahh good catch. Fixed.

---
In reply to: [384211714](https://github.com/microsoft/react-native-windows/pull/4179#discussion_r384211714) [](ancestors = 384211714)
