### PR TITLE
Revise Architecture of react-native-platform-override

### LINKED ISSUE #4847: Fail Override Validation if Copy Type Files are Modified
During override validation we currently only check that upstream files haven't changed. Until upstream releases integration tests and RNTester as a package, we have copies of source in our repo that should not be modified. Fail validation of the original change.

### PR DESCRIPTION
**Pull request by NickGerleman**
override-tools started out as as three week project to increase safety and
decrease effort of integration. The overall architecture has gotten quite messy
and will get messier with new functionality we want to add, such as integration
of new RNTester files without manual copies, treating stub files specially, validating copy
integrity, or being used programatically. This change rethinks the architecture of the
project in preparation of these changes.

Goals:
- Allow overrides to represent entities other than single files
- Allow oer-override-type logic without teaching the world about every override type
- Increase testability
- Increase cohesion/single responsibility
- Decouple internal override representation from their serialized form

The crux of the change is adding a new representation of overrides separate
from the serialized one. This representation hides internal details from the
rest of the world. Overrides describe how they can be upgradeed and validated
using common strategies. This approach allows declaritively describing override
rules, keeps overrides unaware of upgrade details, and allows the rest of the
system to be unaware of how upgrades work.

Responsibility for override creation is moved from Manifest to a specific
OverrideFactory. This helps to keep Manifest as an object describing an
aggregation of overrides instead of the hub it has been turning into.

While here we stricten Typescript configuration to catch some more cases we
weren't before. We implement a copy-specific rule to validate some of the design ideas as well.

Validation was done by a combination of UTs and manual validation of key scenarios like override validation, adding override through the CLI, and automated upgrades.

Fixes #4847 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5065)

### CODE REVIEW

File: packages/react-native-platform-override/src/Cli.ts [hunk 1]
```diff
@@ -134,8 +135,13 @@ async function validateManifest(manifestPath: string, version?: string) {
   const spinner = ora(`Verifying overrides in ${fullPath}`).start();
 
   await spinnerGuard(spinner, async () => {
-    const manifest = await readManifest(manifestPath, version);
-    const validationErrors = await manifest.validate();
+    const manifest = await readManifest(manifestPath);
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:138]: fold this into createContext

File: packages/react-native-platform-override/src/Cli.ts [hunk 2]
```diff
@@ -230,52 +243,49 @@ async function manualUpgrade(manifestPath: string, version?: string) {
...
     for (const override of outOfDateOverrides) {
       spinner.text = `Merging overrides (${++i}/${outOfDateOverrides.length})`;
 
-      const upgraded = await upgrader.getUpgraded(
-        override,
-        manifest.currentVersion(),
-      );
+      const upgradeResult = await override
+        .upgradeStrategy()
+        .upgrade(gitReactRepo, overrideRepo, version, isManual);
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:274]: Add `/*allowConflicts*/`

File: packages/react-native-platform-override/src/Cli.ts [hunk 3]
```diff
@@ -213,15 +218,23 @@ async function removeOverride(overridePath: string) {
  * out-of-date overrides.
  */
 async function autoUpgrade(manifestPath: string, version?: string) {
-  return doUpgrade(manifestPath, false /*isManual*/, version);
+  return doUpgrade(
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:221]: Rename to performUpgrade

File: packages/react-native-platform-override/src/Cli.ts [hunk 4]
```diff
@@ -314,56 +324,61 @@ function printValidationErrors(errors: Array<ValidationError>) {
...
-  const baseFilesNotFound = errors.filter(err => {
-    return err.type === 'baseFileNotFound';
-  });
-  const outOfDateFiles = errors.filter(err => {
-    return err.type === 'outOfDate';
-  });
-
-  if (filesMissing.length > 0) {
-    const errorMessage = `Found override files that aren't listed in the manifest. Overrides can be added to the manifest by using 'npx ${
+  printErrorsOfType(
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:327]: Rename to `printErrorType` and reorder params

File: packages/react-native-platform-override/src/Cli.ts [hunk 5]
```diff
@@ -382,36 +397,46 @@ async function checkFileExists(friendlyName: string, filePath: string) {
 /**
  * Read a manifest and print a pretty error if we can't
  */
-async function readManifest(file: string, version?: string): Promise<Manifest> {
-  const gitReactRepo = await GitReactFileRepository.createAndInit();
-  const ovrRepo = new OverrideFileRepositoryImpl(path.dirname(file));
+async function readManifest(file: string): Promise<Manifest> {
+  try {
+    const data = await Serialized.readManifestFromFile(file);
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:402]: Having these scoped to a `Serialized` module is a bit awkward. Consider changing serialized stuff to ES6 exports and add naming a different way.

File: packages/react-native-platform-override/src/Cli.ts [hunk 6]
```diff
@@ -382,36 +397,46 @@ async function checkFileExists(friendlyName: string, filePath: string) {
...
+  } catch (ex) {
+    throw new Error('Could not parse manifest. Is it valid?');
+  }
+}
 
-  return readManifestUsingRepos(file, ovrRepo, gitReactRepo, version);
+/**
+ * Context contianing global properties for the CLI
+ */
+interface Context {
```
[the remark this answers is not in the document]
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Cli.ts:412]: Maybe `ManifestContext` since these are centered around a given manifest.

File: packages/react-native-platform-override/src/GitReactFileRepository.ts [hunk 7]
```diff
@@ -25,33 +25,33 @@ export default class GitReactFileRepository
...
-  private constructor() {}
+  private constructor(gitDirectory: string, gitClient: simplegit.SimpleGit) {
+    this.actionQueue = new ActionQueue();
+    this.gitDirectory = gitDirectory;
+    this.gitClient = gitClient;
+  }
 
   static async createAndInit(
-    gitDirectory?: string,
+    gitDirectory: string = DEFAULT_DIR,
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/GitReactFileRepository.ts:42]: DEFAULT_DIR shouldn't be cased as a constant

File: packages/react-native-platform-override/src/Manifest.ts [hunk 8]
```diff
@@ -5,183 +5,82 @@
...
-
-interface OverrideBaseInfo {
-  baseFile: string;
-  baseVersion: string;
-  baseHash: string;
-}
-
+/**
+ * Represents a collection of overrides listed in an on-disk manifest. Allows
+ * performing aggregate operations on the overrides.
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Manifest.ts:19]: Was considering having the manifest delegate upgrade work as well, but the upgrade process touches quite a bit so it didn't feel like the right place. I should consider taking that out of the CLI at some point though when we start programatically consuming react-native-platform-override for daily integration scripts, etc.

File: packages/react-native-platform-override/src/Manifest.ts [hunk 9]
```diff
@@ -5,183 +5,82 @@
...
-
-      case 'derived':
-        return this.addDerivedOverride(file, baseFile, issue);
-
-      case 'patch':
-        return this.addPatchOverride(file, baseFile, issue);
-
-      case 'copy':
-        return this.addCopyOverride(file, baseFile, issue);
+    const overrideValidationStrats = _.flatMap(this.overrides, ovr =>
```
[the remark this answers is not in the document]
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Manifest.ts:53]: Maybe `validationTasks`

File: packages/react-native-platform-override/src/Manifest.ts [hunk 10]
```diff
@@ -5,183 +5,82 @@
...
-  constructor(
-    data: ManifestData.Manifest,
-    overrideRepo: OverrideFileRepository,
-    reactRepo: ReactFileRepository,
-  ) {
-    this.overrides = _.cloneDeep(data.overrides);
-    this.overrideRepo = overrideRepo;
-    this.reactRepo = reactRepo;
+  constructor(overrides: Array<Override>) {
+    this.overrides = _.cloneDeep(overrides);
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Manifest.ts:25]: We should validate we don't have duplicates here and make sure to propagate that error up further.

File: packages/react-native-platform-override/src/Manifest.ts [hunk 11]
```diff
@@ -5,183 +5,82 @@
...
-   * Copy override specific version of {@see addOverride}
+   * Add an override to the manifest
    */
-  async addCopyOverride(file: string, baseFile: string, issue: number) {
-    file = await this.checkAndNormalizeOverrideFile(file);
-
-    const overrideBaseInfo = await this.getOverrideBaseInfo(baseFile);
-    this.overrides.push({type: 'copy', file, ...overrideBaseInfo, issue});
+  addOverride(override: Override) {
+    this.overrides.push(override);
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Manifest.ts:68]: Check for duplicates here

File: packages/react-native-platform-override/src/UpgradeStrategy.ts [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+ */
+
+import GitReactFileRepository from './GitReactFileRepository';
+import {OverrideFileRepository} from './FileRepository';
+
+export interface UpgradeResult {
+  hasConflicts: boolean;
+}
+
+export interface UpgradeStrategy {
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/UpgradeStrategy.ts:15]: export default

File: packages/react-native-platform-override/src/ValidationStrategy.ts [hunk 13]
```diff
@@ -0,0 +1,96 @@
...
+    | 'outOfDate' // A base file has changed since the manifested version
+    | 'overrideDifferentFromBase'; // An override file is not an expact copy of the base file
+
+  /**
+   * What override failed validation
+   */
+  overrideName: string;
+}
+
+export interface ValidationStrategy {
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/ValidationStrategy.ts:28]: export default

File: packages/react-native-platform-override/src/Cli.ts (hunk 5 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Cli.ts:402]: Going to leave this as is

File: packages/react-native-platform-override/.eslintrc.js [hunk 14]
```diff
@@ -7,7 +7,14 @@
...
 
 module.exports = { 
-  extends: "@react-native-community",
+  extends: [
+    "@react-native-community",
+
+    // @react-native-community doesn't seem to include the
+    // eslint-config-prettier blacklist which can sometimes lead to conflicting
+    // rules. Make sure to include the exclusions here.
+    "prettier",
```
Comment (NickGerleman) [inline packages/react-native-platform-override/.eslintrc.js:16]: Need to file an upstream RN issue for this

File: packages/react-native-platform-override/src/Hash.ts [hunk 15]
```diff
@@ -0,0 +1,18 @@
+/**
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Hash.ts:1]: Same functionality as before, just moved out of Manifest.ts

File: packages/react-native-platform-override/src/PackageUtils.ts [hunk 16]
```diff
@@ -23,9 +23,13 @@ export async function getInstalledRNVersion(): Promise<string> {
 }
 
 /**
- * Return an object representing the package.json of this package
+ * Return an object representing the package.json of our current package
  */
 export function getNpmPackage(): any {
+  if (!require.main) {
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/PackageUtils.ts:29]: Needed with strict since `require.main` can be null sometimes according to typings? Not sure if that's ever true running in Node though.

File: vnext/src/Libraries/Image/Image.windows.js [hunk 17]
```diff
@@ -1,10 +1,13 @@
 /**
- * Copyright (c) Microsoft Corporation.
- * Licensed under the MIT License.
+ * Copyright (c) Facebook, Inc. and its affiliates.
```
Comment (NickGerleman) [inline vnext/src/Libraries/Image/Image.windows.js:2]: This file was marked as a copy-style override, so any changes will get clobbered during upgrades. Adding validation to prevent tampering discovered it wasn't a verbatim copy of the original file, so I needed to restore this as an exact copy.

File: packages/react-native-platform-override/src/Cli.ts [hunk 18]
```diff
@@ -382,36 +396,46 @@ async function checkFileExists(friendlyName: string, filePath: string) {
...
  */
-async function readManifest(file: string, version?: string): Promise<Manifest> {
-  const gitReactRepo = await GitReactFileRepository.createAndInit();
-  const ovrRepo = new OverrideFileRepositoryImpl(path.dirname(file));
+async function readManifest(file: string): Promise<Manifest> {
+  try {
+    const data = await Serialized.readManifestFromFile(file);
+    return Manifest.fromSerialized(data);
+  } catch (ex) {
+    throw new Error('Could not parse manifest. Is it valid?');
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:404]: I should throw this lower so we can get more descriptive messages when this isn't the case.

File: packages/react-native-platform-override/src/GitReactFileRepository.ts [hunk 19]
```diff
@@ -29,32 +30,32 @@ export default class GitReactFileRepository
...
+  private checkedOutVersion?: string;
 
   // We have a potential race condition where one call to getFileContents
   // could checkout out a new tag while an existing call is rading a file.
   // Queue items to ensure the read operation is performed atomically
   private actionQueue: ActionQueue;
 
-  private constructor() {}
+  private constructor(gitDirectory: string, gitClient: simplegit.SimpleGit) {
+    this.actionQueue = new ActionQueue();
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/GitReactFileRepository.ts:41]: Changed bc TS strict settings enforces that we set instance variables in the constructor or mark them possibly undefined.

File: packages/react-native-platform-override/src/Manifest.ts [hunk 20]
```diff
@@ -5,183 +5,91 @@
...
+    overrideRepo: OverrideFileRepository,
+    reactRepo: ReactFileRepository,
+  ): Promise<Array<ValidationError>> {
+    const errors: ValidationError[] = [];
 
-      case 'copy':
-        return this.addCopyOverride(file, baseFile, issue);
+    const overrideFiles = await overrideRepo.listFiles();
+    const missingFromManifest = overrideFiles.filter(
+      file => !this.overrides.some(manOvr => manOvr.includesFile(file)),
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Manifest.ts:51]: `manOvr` is a bad name. Will change that to something better.

File: packages/react-native-platform-override/src/Manifest.ts [hunk 21]
```diff
@@ -5,183 +5,91 @@
...
+    const validationTasks = _.flatMap(this.overrides, ovr =>
+      ovr.validationStrategies(),
+    );
 
-  /**
-   * Patch override specific version of {@see addOverride}
-   */
-  async addPatchOverride(file: string, baseFile: string, issue: number) {
-    file = await this.checkAndNormalizeOverrideFile(file);
+    for (const strat of validationTasks) {
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Manifest.ts:62]: `task` instead of `strat` (an artifact of an older name)

File: packages/react-native-platform-override/src/Cli.ts [hunk 22]
```diff
@@ -154,35 +159,34 @@ async function addOverride(overridePath: string) {
...
       chalk.yellow(
         'Warning: override already exists in manifest and will be overwritten',
       ),
     );
-    manifest.removeOverride(relOverride);
+    manifest.removeOverride(overrideName);
   }
 
-  const overrideDetails = await OverridePrompt.askForDetails(relOverride);
+  const promptAnswers = await promptForOverrideDetails();
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Cli.ts:176]: Rename this back to "details"

File: packages/react-native-platform-override/src/Manifest.ts [hunk 23]
```diff
@@ -194,93 +102,51 @@ export default class Manifest {
...
-    const baseContent = await this.reactRepo.getFileContents(baseFile);
-    if (baseContent === null) {
-      throw new Error(`Could not find base file '${file}'`);
-    }
-
-    const baseVersion = this.currentVersion();
-    const baseHash = Manifest.hashContent(baseContent);
-
-    return {baseFile, baseVersion, baseHash};
+  private findOverrideIndex(overrideName: string): number {
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/Manifest.ts:149]: I might be able to remove this helper now?

File: packages/react-native-platform-override/src/test/Override.test.ts [hunk 24]
```diff
@@ -0,0 +1,95 @@
...
+});
+
+const fileOverrides: TestCase<OverrideConstructor>[] = [
+  platformOverride,
+  copyOverride,
+  derivedOverride,
+  patchOverride,
+];
+
+test.each(fileOverrides)('%s Override Name', (_, ovrClass, args) => {
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/test/Override.test.ts:67]: Change string to match other tests

Comment (NickGerleman) [reply packages/react-native-platform-override/src/test/Override.test.ts:67]: Also fix the typo at the top

File: packages/react-native-platform-override/src/Serialized.ts [hunk 25]
```diff
@@ -60,39 +59,43 @@ const CopyEntryType = t.type({
...
 }
 
 /**
  * Parse a string with JSON for the override manifest into one.
  *
  * @throws if the JSON doesn't describe a valid manifest
  */
-export function parse(json: string): Manifest {
+export function parseManifest(json: string): Manifest {
   const parsed = JSON.parse(json);
```
Comment (dannyvv) [inline packages/react-native-platform-override/src/Serialized.ts:99]: > = [](start = 14, length = 2)

You should be able to assign the type so you don't need the `as Manfiest` later

```suggestion
 : Manifest =
```

File: packages/react-native-platform-override/src/UpgradeStrategy.ts [hunk 26]
```diff
@@ -0,0 +1,88 @@
...
+  hasConflicts: boolean;
+}
+
+/**
+ * An UpgradeStrategy describes the process to upgrade an individual override
+ * to a new version of the React Native source tree.
+ */
+export default interface UpgradeStrategy {
+  upgrade(
+    reactRepo: GitReactFileRepository,
```
Comment (NickGerleman) [inline packages/react-native-platform-override/src/UpgradeStrategy.ts:21]: rename `reactRepo` in this file to `gitReactRepo`

File: packages/react-native-platform-override/src/Serialized.ts (hunk 25 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Serialized.ts:99]: We don't know yet whether the JSON on disk conforms to the schema. The `ManifestType.decode(parsed)` call validates against the type, which is why we delay associating the type until we know its correct.

File: packages/react-native-platform-override/src/Manifest.ts [hunk 27]
```diff
@@ -5,183 +5,91 @@
...
  */
 
-import * as ManifestData from './ManifestData';
+import * as Serialized from './Serialized';
 
 import * as _ from 'lodash';
-import * as crypto from 'crypto';
-import * as path from 'path';
 
+import Override, {deserializeOverride} from './Override';
```
Comment (dannyvv) [inline packages/react-native-platform-override/src/Manifest.ts:12]: curious why not import the interface named like the function. Is that not allowed when it is the default export?

File: packages/react-native-platform-override/src/Override.ts [hunk 28]
```diff
@@ -0,0 +1,299 @@
...
+import OverrideFactory from './OverrideFactory';
+
+/**
+ * Immmutable programatic representation of an override. This should remain
+ * generic to files vs directories, different representations, different
+ * validation rules, etc.
+ */
+export default interface Override {
+  /**
+   * Identifer of the override (e.g. filename or directory name)
```
Comment (dannyvv) [inline packages/react-native-platform-override/src/Override.ts:22]: When looking in Manifest.ts, maybe add a comment that the identifier is case sensitive?

File: packages/react-native-platform-override/src/Manifest.ts (hunk 27 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Manifest.ts:12]: Yep, that's exactly it. Default imports go outside of braces and the name you give it doesn't actually matter.

File: packages/react-native-platform-override/src/Manifest.ts (hunk 20 above)
Comment (dannyvv) [inline packages/react-native-platform-override/src/Manifest.ts:51]: Just curious: Any particular reason why using `some` instead of `findOverrideIndex` in all the other places...

File: packages/react-native-platform-override/src/Manifest.ts [hunk 29]
```diff
@@ -194,93 +102,51 @@ export default class Manifest {
...
    */
-  static hashContent(str: string) {
-    const hasher = crypto.createHash('sha1');
-    const normalizedStr = str.replace(/(?<!\r)\n/g, '\r\n');
-    hasher.update(normalizedStr);
-    return hasher.digest('hex');
+  serialize(): Serialized.Manifest {
+    return {
+      overrides: this.overrides
+        .sort((a, b) => a.name().localeCompare(b.name()))
```
Comment (dannyvv) [inline packages/react-native-platform-override/src/Manifest.ts:140]: since the names are identifiers, are we sure we should sort locale-specific

File: packages/react-native-platform-override/src/Override.ts [hunk 30]
```diff
@@ -0,0 +1,299 @@
...
+   */
+  name(): string;
```
Comment (dannyvv) [inline packages/react-native-platform-override/src/Override.ts:24]: Curious why you are using functions for readonly properties. TypeScript does have support for readonly.
```suggestion
  readonly name: string;
```
I can totally understand if this has to operate and give readonly guarantee when operating with regular JS.

File: packages/react-native-platform-override/src/Cli.ts [hunk 31]
```diff
@@ -314,56 +323,61 @@ function printValidationErrors(errors: Array<ValidationError>) {
...
-    outOfDateFiles.forEach(err => console.error(` - ${err.file}`));
+    } manual-upgrade <manifest>':`,
+  );
+
+  printErrorType(
+    'overrideDifferentFromBase',
+    errors,
+    'The following overrides should be an exact copy of their base files. Ensure overrides are up to date or revert changes:',
+  );
+}
```
Comment (dannyvv) [inline packages/react-native-platform-override/src/Cli.ts:365]: future suggestion: maybe a catch-all here? 
i.e. have printErrorType remove the errors printed from the errors list and then here cehck if there are any errors left?

**Comment by dannyvv** [comment]
Is there a sample manifest to look at?

**Comment by NickGerleman** [comment]
> Is there a sample manifest to look at?

Yeah, there are a few files named "overrides.json" in the repo in various places.

File: packages/react-native-platform-override/src/Cli.ts (hunk 31 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Cli.ts:365]: Addressed in the next iteration.

File: packages/react-native-platform-override/src/Manifest.ts (hunk 29 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Manifest.ts:140]: Makes sense. Can move from `localCompare` to comparison operators.

File: packages/react-native-platform-override/src/Manifest.ts (hunk 20 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Manifest.ts:51]: Here we want to check if an override contains a file instead of the override name. These are effectively the same now but won't be with directory based overrides.

File: packages/react-native-platform-override/src/Override.ts (hunk 30 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Override.ts:24]: We don't care much about untyped scenarios, but this is mostly for consistency with other methods. Not sure if how inheritance stuff would work for ValidationStrategies if we used props.

File: packages/react-native-platform-override/src/Manifest.ts (hunk 23 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Manifest.ts:149]: Nvm, still need for splicing

File: packages/react-native-platform-override/src/Manifest.ts (hunk 29 above)
Comment (NickGerleman) [reply packages/react-native-platform-override/src/Manifest.ts:140]: Actually I'm not sure that I like how casing is handled for pure lexocographic sort. Going to hardcode to English locale to get determinism though.
