### PR TITLE
Fix UTF8 Bug in vswhere Command

### LINKED ISSUE #10034: CLI code fails to invoke vswhere.exe properly to get UTF8 output
### Problem Description

I tried to start with the template, but it would not start.
Possibly, it could be because they are using a Japanese environment.

### Steps To Reproduce

1. `npx react-native init test --template react-native-template-typescript`
2. `cd test`
3. `npx react-native-windows-init --overwrite`
4. `npx react-native run-windows`

### Expected Results

```
C:\dev\sources\repos\<HIDDEN>\test>npx react-native run-windows --logging
 i Verbose: ON
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 ‼ No public VS release found
 i Trying pre-release VS
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 × Unexpected token � in JSON at position 672
Command failed with error Unknown: Unexpected token � in JSON at position 672
Your telemetry sessionId was 012ae3e47fd733c807b714d01befcfda
```

### CLI version

7.0.3

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 35.84 GB / 63.92 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Disabled
      Versions: 10.0.16299.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: 0.68.3 => 0.68.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.16299

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by chiaramooney**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)

### Why
The default cmd.exe is not in utf8 mode when launched from node. When run-windows is run, the vswhere command fails when their are unexpected characters in the description. We need a workaround to standardize the characters before vswhere is run.

Resolves #10034 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10123)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts [hunk 1]
```diff
@@ -43,7 +43,9 @@ function vsWhere(args: string[], verbose?: boolean): any[] {
     );
   }
 
-  const cmdline = `"${vsWherePath}" ${args.join(' ')} -format json -utf8`;
+  const cmdline = `cmd /c chcp 65001>nul && "${vsWherePath}" ${args.join(
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts:46]: nice :) chcp bring back memories of the 90s and DOS.

Can you specify paths for cmd and chcp? they should be in system32:
```suggestion
  const system32 = `${process.env.SystemRoot}\\System32`;
  const cmdline = `${system32}\\cmd.exe /c ${system32}\\chcp.com 65001>nul && "${vsWherePath}" ${args.join(
```

**Review by asklar — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts [hunk 2]
```diff
@@ -43,7 +43,9 @@ function vsWhere(args: string[], verbose?: boolean): any[] {
...
+    ' ',
+  )} -format json -utf8`;
   const json = JSON.parse(execSync(cmdline).toString('utf8'));
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts:49]: actually another option - possibly more elegant - is to only pass the encoding as a param to execSync:
https://nodejs.org/api/child_process.html#child_processexecsynccommand-options

(it's part of the options object)
