### PR TITLE
Fixes autolink check error to include command to fix it

### LINKED ISSUE #6761: Autolinking check failing during msbuild should be a warning, not an error
The auto-linking check during msbuild is only meant to notify the user if their autolinking files are out of date, and provide the command to run to fix the issue. It should not prevent the user from completing the build.

In https://github.com/microsoft/react-native-windows/pull/6403, an error was added to this warning so that the situation could be caught in telemetry, but that causes the build to fail. The error also leaves out the command to fix the issue, and since VS prefers to show an error over a warning, the user is left with no reconciliation.

Unfortunately, the command to run should contain the names of the user's project/solution files, which we don't want to log.

I think the correct solution here is to remove the error and return to the original desired behavior, where users of VS aren't forced to run autolinking, but are given a path to (optionally) resolve the warning. Then we should log the appropriate telemetry that the situation occurred (if that's even useful) excluding the command, but not by throwing a build-failing error.

### PR DESCRIPTION
**Pull request by jonthysell**
If the autolinking check fails, the error should include the proper command to fix it.

Closes #6761

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7146)

### CODE REVIEW

**Comment by jonthysell** [comment]
This PR supersedes #6763.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 1]
```diff
@@ -808,6 +808,18 @@ export class AutolinkWindows {
     });
     return changed;
   }
+
+  /** @return The CLI command to invoke autolink-windows independently */
+  public getAutolinkWindowsCommand() {
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:813]: nit: consider adding an explicit return type. Can be helpful when skimming through code.

**Review by NickGerleman — APPROVED** [review]

**Review by asklar — APPROVED** [review]
