### PR TITLE
Detect whether a project file is a dynamic library

### LINKED ISSUE #8072: Autolinking is picking up project files not meant to be autolinked
`@react-native-windows/cli` is adding a project file that wasn't meant to be autolinked. This was probably introduced in https://github.com/microsoft/react-native-windows/commit/11a322b373c28d0e73dde83550dc42cee1352457.

Correct me if I'm wrong, but it seems like we are assuming that if `react-native config` populates the `windows` field, it must be a `react-native-windows` compatible project. This will break JS-only libraries that have a Windows test app somewhere in the package. As far as I can see, there are two solutions to this, either rename the `windows` folder to something else, or disable autolinking of the package altogether, i.e.:

```js
// react-native.config.js
module.exports = {
  dependency: {
    platforms: {
      windows: null,
    },
  },
};
```

## Environment

1. `npx react-native --version`: 5.0.1
2. `npx react-native info`:
    ```
    System:
      OS: Windows 10 10.0.19041
      CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
      Memory: 7.33 GB / 15.45 GB
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      react: 17.0.2 => 17.0.2
      react-native: ^0.64.2 => 0.64.2
      react-native-windows: canary => 0.0.0-canary.327
    Installed UWP SDKs:
      10.0.18362.0
      10.0.19041.0
    ```
- Target Device(s): Desktop
- Visual Studio Version: 2019

## Steps To Reproduce

```sh
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
yarn set-react-version canary-windows
cd example
yarn
yarn install-windows-test-app --use-nuget
cd windows
nuget restore
```

## Expected Results

`nuget restore` to succeed. Instead, I'm getting an error _The solution file has two projects named "ReactTestApp"_ because a `.vcxproj` was added twice. I can work around this error by adding a `Dummy.vcxproj` to force `isRnwDependencyProject` to be called, but then I get an exception `Found a Windows solution for ReactTestApp but no React Native for Windows native module projects`.

## Snack, code example, screenshot, or link to a repository:

See "Steps To Reproduce".

### PR DESCRIPTION
**Pull request by tido64**
Resolves #8072

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8099)

### CODE REVIEW

**Comment by NickGerleman** [comment]
@tido64 FYI looks like this is causing failures in auto-linking UTs.

**Comment by tido64** [comment]
> @tido64 FYI looks like this is causing failures in auto-linking UTs.

Thanks, I will take a look later. I got pulled into another thing 😄

File: packages/@react-native-windows/cli/src/config/configUtils.ts [hunk 1]
```diff
@@ -291,6 +291,92 @@ export function importProjectExists(
   return nodes.length > 0;
 }
 
+export type ConfigurationType =
+  | 'application'
+  | 'dynamiclibrary'
+  | 'generic'
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/config/configUtils.ts:297]: what is 'generic'?

File: packages/@react-native-windows/cli/src/config/dependencyConfig.ts [hunk 2]
```diff
@@ -271,47 +271,69 @@ export function dependencyConfigWindows(
...
+          directDependency,
+          cppHeaders,
+          cppPackageProviders,
+          csNamespaces,
+          csPackageProviders,
+        });
+      } else {
+        const projectPath = path.relative(sourceDir, projectFile);
+        result.projects.push({
+          projectFile: `Error: ${projectPath} is type '${projectType}'`,
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/config/dependencyConfig.ts:326]: I'm not following this error - we couldn't figure out the root namespace for the project, but this error seems to be about project type instead?

File: packages/@react-native-windows/cli/src/config/configUtils.ts (hunk 1 above)
Comment (tido64) [reply packages/@react-native-windows/cli/src/config/configUtils.ts:297]: _Makefile, displays makefile toolset (NMake)_ according to [ConfigurationTypes documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcproject.configurationtypes?view=visualstudiosdk-2019).

File: packages/@react-native-windows/cli/src/config/dependencyConfig.ts [hunk 3]
```diff
@@ -271,47 +271,69 @@ export function dependencyConfigWindows(
...
+          directDependency: false,
+          projectName: '',
+          projectLang: null,
+          projectGuid: null,
+          cppHeaders: [],
+          cppPackageProviders: [],
+          csNamespaces: [],
+          csPackageProviders: [],
+        });
+      }
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/config/dependencyConfig.ts:336]: I'm not sure pushing a project onto the config if it isn't of interest is the right thing? @jonthysell what do you think?

Also note that the project type will be empty for some projects, e.g. WAP projects

Comment (tido64) [reply packages/@react-native-windows/cli/src/config/dependencyConfig.ts:336]: Pushing the error invalidates the project here: https://github.com/microsoft/react-native-windows/blob/b7da9b7b910ee38853a4afdcdbad4afde9ab6958/packages/%40react-native-windows/cli/src/runWindows/utils/autolink.ts#L443-L450

It's a pattern that is used elsewhere: https://github.com/microsoft/react-native-windows/blob/b7da9b7b910ee38853a4afdcdbad4afde9ab6958/packages/%40react-native-windows/cli/src/config/projectConfig.ts#L175-L185

If you feel uncomfortable with this change, an alternative would be to downgrade this to a warning instead of throwing an exception: https://github.com/microsoft/react-native-windows/blob/b7da9b7b910ee38853a4afdcdbad4afde9ab6958/packages/%40react-native-windows/cli/src/runWindows/utils/autolink.ts#L428-L437

File: packages/@react-native-windows/cli/src/config/configUtils.ts (hunk 1 above)
Comment (asklar) [reply packages/@react-native-windows/cli/src/config/configUtils.ts:297]: gotcha. We don't support nmake (msbuild support of nmake is limited to drivers, I think?) but I guess it doesn't hurt to leave it here. Feel free to remove if you want.

**Review by asklar — APPROVED** [review]

**Comment by asklar** [comment]
@tido64 consider adding a unit test to make sure we don't regress this again?

File: packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap [hunk 4]
```diff
@@ -24,6 +24,34 @@ Object {
 }
 `;
 
+exports[`dependencyConfig - SimpleCSharpApp (Ignore react-native.config.js) 1`] = `
+Object {
+  "folder": "D:\\\\Source\\\\react-native-windows\\\\packages\\\\@react-native-windows\\\\cli\\\\src\\\\e2etest\\\\projects\\\\SimpleCSharpApp",
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap:29]: thanks for adding tests :) I think you'll want these to be relative paths so they work everywhere

Comment (tido64) [reply packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap]: Thanks! Definitely didn't intend to have hard-coded paths here 😛
