### PR TITLE
Fix remote debugging with web debugging in Playground.

### LINKED ISSUE #5112: Remote native debugging Playground with web debugging doesn't work anymore
We added some support for remote debugging the Playground app, see:
https://github.com/microsoft/react-native-windows/wiki/VS-Remote-Debugging

However this technique doesn't work anymore.  I debugged this and found two issues:
1. The privateNetworkClientServer capability isn't turned on in Package.appxmanifest
2. The client code is failing to connect due to using localhost:8081.  It looks like we're missing the plumbing code that was originally added to HostingPane, which is no longer being used in Playground.

We should find a way to re-enable this.  We should also think about how to enable remote debugging for CLI apps when we fix this - ideally whatever we do would also work for template apps.

### PR DESCRIPTION
**Pull request by nasadigital**
Fixes #5112.
To remote debug the Playground app follow the steps in the wiki: https://github.com/microsoft/react-native-windows/wiki/VS-Remote-Debugging
Don't forget to open the port on the host machine.
This implementation is based on #3535.
Limitations:
- There is no way to specify only the hostname or only the port, you have to specify both.
- Not sure what I am missing but running `yarn change` gives me the following error so I couldn't update the changelog:
Annotation 2020-06-23 192843

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5327)

### CODE REVIEW

File: packages/playground/windows/playground/MainPage.cpp [hunk 1]
```diff
@@ -73,6 +76,10 @@ void winrt::playground::implementation::MainPage::x_entryPointCombo_SelectionCha
   }
 }
 
+void MainPage::OnNavigatedTo(const Windows::UI::Xaml::Navigation::NavigationEventArgs &e) {
```
Comment (acoates-ms) [inline packages/playground/windows/playground/MainPage.cpp:79]: use xaml::Navigation::NavigationEventArgs - we build the playground app both with regular xaml, and with WinUI3.  And they use different namespaces.  The xaml alias switches between the two depending on which one we are building.

File: packages/playground/windows/playground/MainPage.h [hunk 2]
```diff
@@ -17,11 +17,13 @@ struct MainPage : MainPageT<MainPage> {
   Windows::Foundation::Collections::IVector<Microsoft::ReactNative::IReactPackageProvider> m_packageProviders;
 
   bool m_useWebDebugger{false};
+  winrt::hstring debugHost;
```
Comment (acoates-ms) [inline packages/playground/windows/playground/MainPage.h:20]: looks like the other member of this file is using m_ for the members. -- You should at least be consistent with the rest of the members.

Comment (nasadigital) [reply packages/playground/windows/playground/MainPage.h]: My bad, I also went ahead and removed the the other variable since it wasn't used.

**Comment by nasadigital** [comment]
Thank you for reviewing!
