### PR TITLE
Raise Instance notifications in JSDispatcher thread

### LINKED ISSUE #7305: ABI safe JsiRuntime is torn down before underlying facebook::jsi::Runtime during dev mode refresh causing weird behavior
## Environment

I have synced with @vmoroz offline on this issue but am filing it here for tracking with my team.

## Steps To Reproduce
Branch: [chrisfromwork/BabylonReactNative at swapChainFix (github.com)](https://github.com/chrisfromwork/BabylonReactNative/tree/swapChainFix)

#### Setup
1. Repo root: git submodule update --init --recursive *
1. Apps\Playground: npm install
1. Package: npm install
1. Package: npx gulp buildUWP
    * This may take a while/its building all dependency static libs
1. Apps\Playground: npm run windows-verbose
    * Or run npm start and then build the Playground.sln in the windows folder

#### Repro
1. Ensure app.cpp resolves to index bundle and dev mode refresh are enabled for Playground.sln. **Don't use web debugger tools** (BabylonReactNative dependencies require access to the jsi runtime, which does not work with web debugger tools)
1. Build and run Debug x64 Playground.sln build
1. Once the application is up, press r in the metro server window to refresh

#### Observed:	
ABI safe JsiRuntime is destroyed prior to cleaning up lower level facebook::jsi::Runtime. JSI objects still attempt to execute logic that fails because they are unable to resolve the ABI safe JsiRuntime even though the facebook::jsi::Runtime is still valid.

#### Expected:	
ABI safe JsiRuntime is destroyed after destroying lower level jsiruntime. JSI objects are destroyed prior to the ABI safe JsiRuntime being destroyed.

### PR DESCRIPTION
**Pull request by vmoroz**
The React instance notifications (`InstanceCreated`, `InstanceLoaded`, and `InstanceDestroyed`) introduced in 0.64 version are raised on a dispatcher thread that is used internally for synchronizing ReactHost and ReactInstanceWin components. While it works, it makes it difficult to use in the code because this dispatcher is not exposed to the public API and users must always redirect it to JS nor UI dispatchers. Such asynchronous redirection may cause unexpected issues in instance unload scenarios.
E.g. it is the the root cause of the issue #7305 where it is impossible to correctly destroy the JSI Runtime when a React instance is reloaded.

In this PR we change these notifications to be always raised in the JSDispatcher thread. This way the notifications are following the native module model where we also call methods in the JSDispatcher thread. It fixes the issue #7305 because we can now destroy the JSI Runtime at the same time when the JSDispatcher is destroyed. The `JsiSimpleTurboModuleTests` unit test is added to verify the threading model for the notifications.

Note that these instance events are new in 0.64 and if we change it in the upcoming 0.64 release, then there will be no breaking change.

Closes #7305

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7356)

### CODE REVIEW

File: vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp [hunk 1]
```diff
@@ -0,0 +1,124 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+// See that we can safely reload react instance when we use C++ TurboModules.
+
+#include "pch.h"
+#include <ReactCommon/TurboModule.h> // This comes from the react-native package.
+#include <ReactCommon/TurboModuleUtils.h> // This must come from the react-native package, but we use a local version to fix issues.
```
Comment (asklar) [inline vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp:8]: i don't see a fork of this file, is the comment out of date?

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp [hunk 2]
```diff
@@ -190,6 +189,26 @@ ReactInstanceWin::ReactInstanceWin(
           this,
           options.Properties,
           winrt::make<implementation::ReactNotificationService>(options.Notifications))} {
+  m_whenLoaded.AsFuture()
```
Comment (dannyvv) [inline vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:192]: nit: it feels like the indentation is not intuitivie.

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp [hunk 3]
```diff
@@ -190,6 +189,26 @@ ReactInstanceWin::ReactInstanceWin(
...
+      .Then<Mso::Executors::Inline>(
+          [onLoaded = m_options.OnInstanceLoaded, reactContext = m_reactContext](Mso::Maybe<void> &&value) noexcept {
+            if (onLoaded) {
+              onLoaded.Get()->Invoke(reactContext, value.IsError() ? value.TakeError() : Mso::ErrorCode());
```
Comment (dannyvv) [inline vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:196]: Do we need the weak/strong dance here for `reactcontext`?

Comment (dannyvv) [reply vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:196]: similar for below.

**Comment by NickGerleman** [comment]
I remember @acoates-ms mentioning there was a reason we needed to have callbacks fired inline instead of dispatched. Don't remember the details though.

Not sure the complexity, but it would be neat if we are dispatching to allow passing arbitrary dispatchers. E.g. it may be assumed these have UI-thread affinity.

Changing the API for 0.64 makes sense to me, if we're going to change it.

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp [hunk 4]
```diff
@@ -190,6 +189,26 @@ ReactInstanceWin::ReactInstanceWin(
...
+      .Then(Queue(), [whenLoaded = std::move(whenLoaded)](Mso::Maybe<void> &&value) noexcept {
+        whenLoaded.SetValue(std::move(value));
+      });
+  m_whenDestroyedResult =
+      m_whenDestroyed.AsFuture().Then<Mso::Executors::Inline>([whenLoadFailed = m_whenLoaded,
+                                                               onDestroyed = m_options.OnInstanceDestroyed,
+                                                               reactContext = m_reactContext]() noexcept {
+        whenLoadFailed.TryCancel();
+        if (onDestroyed) {
+          onDestroyed.Get()->Invoke(reactContext);
```
Comment (dannyvv) [inline vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:208]: The old code had it's null check onthe result of Get() is that no longer needed?

File: vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj [hunk 5]
```diff
@@ -183,6 +183,7 @@
     <ClInclude Include="Base\CoreNativeModules.h" />
     <ClInclude Include="Base\CxxReactIncludes.h" />
     <ClInclude Include="Base\FollyIncludes.h" />
+    <ClInclude Include="ReactHost\JSCallInvokerScheduler.h" />
```
Comment (dannyvv) [inline vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj:186]: Just checking: Was this just a missing file in the vcxproj or is it still here from an intermediate change?

File: vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp (hunk 1 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp]: Yes, it was a copy and paste comment from the previous test. In the meantime the `TurboModuleUtils.h` was fixed in the react-native repo and the comment became out-of-date. I have removed the comments in both files: https://github.com/microsoft/react-native-windows/pull/7356/commits/7547d7b2890b2afcd184d724566ee8238a8b15ba

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp (hunk 2 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:195]: Agree, but we use the automated clang-format and I have no control over it.
I am adding some comments. Hopefully it will make it stand out a little bit easier.
See commit https://github.com/microsoft/react-native-windows/pull/7356/commits/ab9f063cff5dacfe0bbaec7d6efa167c6ab3c9eb

**Comment by acoates-ms** [comment]
The important thing was that I want the created callback to happen before we load the JS Bundle.  We'd use with JSI to inject things into the runtime that may be requirements to run the app bundle.

Its a little hard to tell from this change if that's still the case.  Think inject platfrom bundles during the create event. 



---
In reply to: [796872402](https://github.com/microsoft/react-native-windows/pull/7356#issuecomment-796872402) [](ancestors = 796872402)

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp (hunk 3 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:199]: No, we do not need it. The `ReactContext` is a specialized weak pointer to the `ReactInstance`. Using a weak pointer to the `ReactInstance` is so common that in our API we decided to never expose the `ReactInstance`, but rather only give its weak pointer - the `ReactContext`.

**Comment by vmoroz** [comment]
> I remember @acoates-ms mentioning there was a reason we needed to have callbacks fired inline instead of dispatched. Don't remember the details though.
I agree with @acoates-ms here and it is the core of the change: the `InstanceCreated`, `InstanceLoaded`, and `InstanceDestroyed` are now triggered inline on the JSDispatcher thread where they are originated. I have updated the doc comments for these events saying that developers could use the notification service subscription if they want to handle them in a different dispatcher.

> Not sure the complexity, but it would be neat if we are dispatching to allow passing arbitrary dispatchers. E.g. it may be assumed these have UI-thread affinity (this tripped me up before).
It is already possible by using the `ReactNotificationService`. The notification handler receives a `ReactDispatcher` as a parameter. If this parameter in nullptr, then the notification is handled synchronously.

> Changing the API for 0.64 makes sense to me, if we're going to change it.
Sounds great! Hope it gets approved for 0.64 then. :)

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp (hunk 4 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:216]: It is the same: checking for null has the same effect as the explicit cast to bool.
BTW, we could call the callback as `onDestroyed(reactContext);`. The reason we use longer syntax is avoid one extra entry in the call stack. The `onDestroyed(reactContext);` internally calls `Invoke(reactContext)`. Thus, the longer syntax removes the `onDestroyed(reactContext);` from the call stack.

**Comment by vmoroz** [comment]
> The important thing was that I want the created callback to happen before we load the JS Bundle. We'd use JSI to inject things into the runtime that may be requirements to run the app bundle.
> 
> Its a little hard to tell from this change if that's still the case. Think inject platfrom bundles during the create event.
> 
> In reply to: [796872402](https://github.com/microsoft/react-native-windows/pull/7356#issuecomment-796872402) [](ancestors = 796872402)

Let's discuss it offline. After the change the `InstanceCreated` is raised as the very first event in the JS queue before anything else.  I must check, but I think it is raised before any other react-native JS variables are set.

File: vnext/Microsoft.ReactNative/ReactInstanceSettings.idl [hunk 6]
```diff
@@ -137,17 +137,45 @@ Subsequent runs of the application should be faster as the JavaScript will be lo
...
 
-    DOC_STRING("This event is triggered when React Native instance has finished loading the JavaScript bundle.  If there were errors, then the @InstanceLoadedEventArgs.Failed property on the args will be true.\n\
-\n\
-Error types include:\n\
-* JavaScript Syntax Errors\n\
-* Global JavaScript Exception Thrown\n\
-\n\
-The @InstanceLoadedEventArgs.Context property on the event arguments provides access to the instance.")
+    DOC_STRING(
+      "The @InstanceCreated event is triggered when React Native instance has finished loading the JavaScript bundle.\n"
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/ReactInstanceSettings.idl:153]: InstanceCreated

File: vnext/Microsoft.ReactNative/ReactInstanceSettings.idl [hunk 7]
```diff
@@ -137,17 +137,45 @@ Subsequent runs of the application should be faster as the JavaScript will be lo
...
+      "\n"
+      "It is triggered on the JSDispatcher thread.\n"
+      "If there were errors, then the @InstanceLoadedEventArgs.Failed property on the event arguments will be true.\n"
+      "The error types include:\n"
+      "\n"
+      "* JavaScript syntax errors.\n"
+      "* Global JavaScript exceptions thrown.\n"
+      "\n"
+      "The @InstanceCreatedEventArgs.Context property on the event arguments provides access to the instance context.\n"
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/ReactInstanceSettings.idl:162]: InstanceLoadedEventArgs

File: vnext/Microsoft.ReactNative/ReactInstanceSettings.idl [hunk 8]
```diff
@@ -137,17 +137,45 @@ Subsequent runs of the application should be faster as the JavaScript will be lo
...
+      "raised in the 'ReactNative.InstanceSettings' namespace. "
+      "Consider using @Notifications to handle the notification in a dispatcher different from JSDispatcher.")
     event Windows.Foundation.EventHandler<InstanceLoadedEventArgs> InstanceLoaded;
+
+    DOC_STRING(
+      "The @InstanceDestroyed event is triggered when React Native instance is destroyed.\n"
+      "\n"
+      "It is triggered on the JSDispatcher thread as the last work item before it shuts down.\n"
+      "No new JSDispatcher work can be executed after that.\n"
+      "The @InstanceCreatedEventArgs.Context property on the event arguments provides access to the instance context.\n"
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/ReactInstanceSettings.idl:174]: InstanceDestroyedEventArgs

**Review by acoates-ms — APPROVED** [review]

File: vnext/Microsoft.ReactNative/ReactInstanceSettings.idl (hunk 6 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative/ReactInstanceSettings.idl]: It is fixed in https://github.com/microsoft/react-native-windows/pull/7356/commits/9ac62d52d6500853c2e6a07543f875ca9e000f5f. Thank you!

File: vnext/Microsoft.ReactNative/ReactInstanceSettings.idl (hunk 7 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative/ReactInstanceSettings.idl]: It is fixed in https://github.com/microsoft/react-native-windows/pull/7356/commits/9ac62d52d6500853c2e6a07543f875ca9e000f5f. Thank you!

File: vnext/Microsoft.ReactNative/ReactInstanceSettings.idl (hunk 8 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative/ReactInstanceSettings.idl]: It is fixed in https://github.com/microsoft/react-native-windows/pull/7356/commits/9ac62d52d6500853c2e6a07543f875ca9e000f5f. Thank you!

**Comment by vmoroz** [comment]
> > The important thing was that I want the created callback to happen before we load the JS Bundle. We'd use JSI to inject things into the runtime that may be requirements to run the app bundle.
> > Its a little hard to tell from this change if that's still the case. Think inject platfrom bundles during the create event.
> > In reply to: [796872402](https://github.com/microsoft/react-native-windows/pull/7356#issuecomment-796872402) [](ancestors = 796872402)
> 
> Let's discuss it offline. After the change the `InstanceCreated` is raised as the very first event in the JS queue before anything else. I must check, but I think it is raised before any other react-native JS variables are set.

**Comment by vmoroz** [comment]
The PR was closed by accident... I reopened it.

File: vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp (hunk 2 above)
Comment (dannyvv) [reply vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp:195]: Sorry, keep forgetting that...
