### PR TITLE
[0.63] Port telemetry improvements to 0.63

### LINKED ISSUE #6536: Anonymize forward slash paths
It's possible that some exceptions from NodeJS produce paths that use forward slashes in Windows, so we should anonymize those in the telemetry too.

### PR DESCRIPTION
**Pull request by asklar**
Backport #6532 to 0.63
- `\\server\share` paths
- paths with forward slashes
- parse msbuild/compiler/linker error codes from exceptions

Fixes #6536 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6535)

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]

**Comment by jonthysell** [comment]
Is the test infra available in 0.63?

**Review by jonthysell — APPROVED** [review]

**Comment by asklar** [comment]
@jonthysell 
> Is the test infra available in 0.63?

the tests run/pass, yes :)

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 1]
```diff
@@ -129,6 +132,12 @@ export function sanitizeFrame(frame: any): void {
   frame.assembly = '';
 }
 
+export function tryGetErrorCode(msg: string): string | undefined {
+  const errorRegEx = /error (\w+\d+):/gi;
```
Comment (asklar) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:136]:
```suggestion
  const errorRegEx = /error (\w+\d+)\s*:/gi;
```
