### PR TITLE
fix(LayoutAnimation): Fix overflow: hidden with LayoutAnimation

### LINKED ISSUE #1236: LayoutAnimation + `overflow: hidden` broken
Since we changed the overflow property to be based on the SetDimensions method, we've lost the ability to track the overflow against a Storyboard animation, which is used in LayoutAnimation.

### PR DESCRIPTION
**Pull request by rozele**
A previous change decoupled `overflow: hidden` from the `SizeChanged` event for views. We have to keep this to support clipping on dependent animations (affecting size and position) generated from LayoutAnimation.

Fixes #1236

### CODE REVIEW

File: ReactWindows/ReactNative/UIManager/BaseViewManager.cs [hunk 1]
```diff
@@ -210,9 +212,15 @@ public override void SetDimensions(TFrameworkElement view, Dimensions dimensions
...
                 SetOverflowHidden(view, dimensions);
+                view.SizeChanged -= OnSizeChanged;
             }
 
             base.SetDimensions(view, dimensions);
+
+            if (overflowHidden)
+            {
+                view.SizeChanged += OnSizeChanged;
+            }
```
Comment (sayar) [inline ReactWindows/ReactNative/UIManager/BaseViewManager.cs]: I'm not sure I like the approach of removing and readding event handlers. It is something a developer will forget to do if they add their own OnSizeChanged event or if they override this method. Is there a way to move this logic to the OnSizeChanged handler or whatever triggers the SizeChanged event?
