### PR TITLE
Fixes issue with restarting animations

### LINKED ISSUE #8419: Native animation gets "stuck" when restarting animation before previous animation completes
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run RNTester, open Native Animated Example
2. Scroll to "Animated Tracking - tap me many times" example
3. Click the example to start the animation.
4. Before the active animation completes, click again.

## Expected Results
The native example should match the restart behavior of the JavaScript example, but it appears that the native animation gets stuck on the second click.

## Snack, code example, screenshot, or link to a repository:
- Repros from RNTester on master

https://user-images.githubusercontent.com/1106239/129373924-1a727ec1-5ac3-4cfe-8cad-e90dd0c77590.mp4

### LINKED ISSUE #9206: Tracking animation nodes do not restart correctly
### Problem Description

When attempting to start a tracking animation from an animation that is already running, the animation pauses at it's current value and does not restart.

### Steps To Reproduce

1. Open RNTester > Native Animated example
2. Scroll to the tracking animation example
3. Click the animation twice (once to start, then again to update while the animation is running).

### Expected Results

The animation behavior should match the JS driver, but the native animation gets stuck.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

_No response_

### Target Device(s)

_No response_

### Visual Studio Version

_No response_

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/1106239/143905660-445fedb2-25b1-4635-9f6b-1b467b39f23d.mp4

### PR DESCRIPTION
**Pull request by rozele**
Fixes #8419

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
Animations on Animated values can be stopped and restarted for any number of reasons. When this occurs, unless the Animated value is removed, it is expected that the next animation on that value will continue from where it left off. Previously, this only worked if the animation ran to completion. These changes allow restarting animations even if the animation over the value is imperatively stopped.

Resolves #8419
Resolves #9206 

### What
Animated Composition values cannot be queried until the animation completes (generally, 1 full frame callback after the animation is stopped). The value is also ready to be queried after a scoped batch completion event fires.

This change introduces deferred animation starts. If we attempt to start an animation on a ValueAnimatedNode where an active animation was recently (i.e., synchronously) stopped, we wait for the `Completed` callback on that animations scoped batch to fire before starting the next animation. The `Completed` callback will fire either after the animation has run to completion or roughly one animation frame after `StopAnimation` is called.

Doing this ensures that animated value in the composition property set reports the correct value when computing the frames for the next animation.

## Testing
Before:

https://user-images.githubusercontent.com/1106239/142925264-1a9a9216-01bf-4f20-83e8-31c8bb9d3c80.mp4

After:

https://user-images.githubusercontent.com/1106239/142925288-495c9410-4b66-467d-af95-bf8521c2e4a0.mp4

This change also fixes restarts for tracking animations:

https://user-images.githubusercontent.com/1106239/146297121-37c17f03-2212-42c2-9cbf-efcac1a51517.mp4

Notice that the animations get out of sync with one another because the UI.Composition approach requires waiting for the completion callback to start any new animations on the same value node, so "restarting" the animation, or setting a new tracked to value, causes the animation to fall behind by a frame or two. This is partly the motivation for #9249.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9190)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp [hunk 1]
```diff
@@ -96,12 +96,24 @@ void ValueAnimatedNode::AddActiveAnimation(int64_t animationTag) {
...
+      // Dispose completed props animations
       for (const auto &props : m_dependentPropsNodes) {
         if (const auto propsNode = manager->GetPropsAnimatedNode(props))
           propsNode->DisposeCompletedAnimation(Tag());
       }
+
+      // Start any deferred animations, if the animation was stopped before
+      // this is run, we will get a null pointer for the animation driver. We
+      // also remove any deferred animation tags in StopAnimation.
+      for (const auto &deferredId : m_deferredAnimations) {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp:111]: Run this loop in a separate conditional that fires if there are no more stopped animations, rather than active animations.

**Comment by rozele** [comment]
Converting back to draft - there's still a minor issue where the animations do not start correctly when deferred.

**Review by chiaramooney — COMMENTED** [review]
Looks good to me. Deferring approval until another dev can review.

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h [hunk 2]
```diff
@@ -37,7 +37,7 @@ class TransformAnimatedNode;
 class TrackingAnimatedNode;
 class AnimationDriver;
 class EventAnimationDriver;
-class NativeAnimatedNodeManager {
+class NativeAnimatedNodeManager : public std::enable_shared_from_this<NativeAnimatedNodeManager> {
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h:40]: Trying to remember the history of this.

I remember seeing a fix for cases where this had an intrusive reference count, but something kept a `unique_ptr` to it. Was that fix from the FB repo that already had this change?

**Review by NickGerleman — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h (hunk 2 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h:40]: I think you're thinking of #9158. In that case, we introduced `enable_shared_from_this` on AnimationDriver back in #8418 but never switched the map of `m_activeAnimations` to hold `std::shared_ptrs` instead of `std::unique_ptrs`.

Comment (rozele) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h:40]: But now that you mention it, we probably don't need to add `enable_shared_from_this` because we can just as easily pass the `shared_ptr` to the NativeAnimatedNodeManager from here:
https://github.com/microsoft/react-native-windows/pull/9190/files#diff-0b33c90c397cd63c83ffa33ef49b79adc59e63cc02267923b8f0aa4944445b7eR64

 since we already pass the NativeAnimatedModule's shared_ptr to the same instance of NativeAnimatedNodeManager in a bunch of other places, e.g.: 
 https://github.com/microsoft/react-native-windows/blob/495edc099b2652fadc10db16abe22e1bfd9ca347/vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h#L53-L70

**Comment by NickGerleman** [comment]
@rozele it looks like there was a conflict with your other PR. Can merge after you resolve it.

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h [hunk 3]
```diff
@@ -99,6 +108,9 @@ class NativeAnimatedNodeManager {
   std::unordered_map<std::tuple<int64_t, std::string>, std::vector<std::unique_ptr<EventAnimationDriver>>>
       m_eventDrivers{};
   std::unordered_map<int64_t, std::shared_ptr<AnimationDriver>> m_activeAnimations{};
+  std::unordered_map<int64_t, std::shared_ptr<AnimationDriver>> m_pendingCompletionAnimations{};
+  std::unordered_map<int64_t, std::unordered_set<int64_t>> m_stoppedAnimations{};
+  std::unordered_map<int64_t, std::unordered_set<int64_t>> m_deferredAnimations{};
```
[the remark this answers is not in the document]
Comment (rozele) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h:113]: There may not be anything to do here, considering the following scenario:
1. Start animation 1 for value X
2. Start animation 2 for value X (will stop animation 1, add animation 2 to pending completion)
3. Start animation 3 for value X (will stop animation 2, add animation 3 to pending completion)

In the current implementation, animation 2 and 3 will be in the pending animation set at the time the completion callback fires for animation 1, and we will attempt to start them simultaneously. Animation 2 will already have been stopped, so there will not be any active animation for it, so it won't get started. Only animation 3 will start, assuming it has not been stopped imperatively.

This could be optimized a bit since we know for certain that animation 2 will be stopped before animation 3 is started. So we never need to add animation 2 to stopped animations (because it never started) and we never need more than 1 animation tag in the deferred animations for a value node tag, because 3 will supercede 2.

However, it may complicate the logic a bit to do this, because when we stop animation 2, we need to check if it is currently the deferred animation before we decide to add it to the stopped animation list.

This also relies on an implementation detail of Animated that there can only be 1 active animation per value node at a time, which isn't likely to change any time soon, but could change in theory.

[the remark this answers is not in the document]
Comment (rozele) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h:113]: Actually, minor modification, looks like there could be a leak here, because if animation 2 never fires a completion callback, it will never be removed from the stopped animation set. I will go ahead and revise to match the expectations of the Animation API.

**Comment by rozele** [comment]
Thanks @NickGerleman - rebased and also fixed a minor bug where deferred animations leaked / prevented new animations from starting.

File: vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.h [hunk 4]
```diff
@@ -11,6 +11,7 @@ using namespace comp;
 }
 
 namespace Microsoft::ReactNative {
+class AnimationDriver;
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.h:14]: Remove.

File: vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp [hunk 5]
```diff
@@ -120,10 +120,37 @@ void NativeAnimatedNodeManager::DisconnectAnimatedNode(int64_t parentNodeTag, in
   }
 }
 
-void NativeAnimatedNodeManager::StopAnimation(int64_t animationId) {
+void NativeAnimatedNodeManager::StopAnimation(int64_t animationId, bool isTrackingAnimation) {
   if (m_activeAnimations.count(animationId)) {
-    if (const auto animation = m_activeAnimations.at(animationId).get()) {
-      animation->StopAnimation();
+    if (const auto animation = m_activeAnimations.at(animationId)) {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp:125]: Not sure why `.get()` was called, perhaps we should add it back...

Comment (NickGerleman) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp:125]: I think it's just extracting the raw pointer to the COM object instead of something that will refcount. The smart pointer still has a boolean operatio, so the `get()` is fine to remove.

Comment (rozele) [reply vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp:125]: Needed to remove the .get() anyway because we need to persist the shared pointer in the pendingCompletionAnimation map until its completion callback fires.
