### PR TITLE
#6217 : Add Clearer Error Msg for YGValues

### LINKED ISSUE #6217: Clearer error messages for unsupported CSS units
From `NativeUIManger.cpp`, you have:

```cpp
static YGValue YGValueOrDefault(const folly::dynamic &value, YGValue defaultValue) {
  YGValue result = defaultValue;

  if (value.isNumber())
    return YGValue{static_cast<float>(value.asDouble()), YGUnitPoint};

  if (value.isNull())
    return defaultValue;

  if (value.isString()) {
    std::string str = value.getString();
    if (str == "auto")
      return YGValue{YGUndefined, YGUnitAuto};
    if (str.length() > 0 && str.back() == '%') {
      str.pop_back();
      folly::dynamic pct(str);
      return YGValue{static_cast<float>(pct.asDouble()), YGUnitPercent};
    }
  }

  // Unexpected format, using default
  assert(false);
  return defaultValue;
}
```

The `assert(false)` just fails without any message as to why this happened. A message like `you used an unsupported CCS unit` might be a better dev experience. 

By the way, the code already returns  `defaultValue` so why `assert(false)`? How about just a warning?

### PR DESCRIPTION
**Pull request by chiaramooney**
Fix #6217 

**_Why_**
YGValueOrDefault function with NativeUIManager crashes when input value is not in an expected format. Issue requested an error message replace the crash behavior for a better dev experience. Conversation within the issue also requested that a separate error message be displayed if the 'pt' or 'px' unit was specified in the input value to tell the user to replace with an integer value instead. 

**_What_**
Behavior matches that of iOS and Android where the following value formats are allowed:
10 - integer
'10%' - string with %

Behavior matches that of iOS and Android where the following value formats are **not** allowed and will trigger a Red Box Error:
'10pt' - string with pt
'10px' - string with px
'10' - string

**_How_**
Altered ShadowNodeBase to add a RedBox API so that a Red Box Error may be called from NativeUIManager where YGValueOrDefault is located. Altered YGValueOrDefault API so that the RedBox func could be called inside this function (needs a reference to a ShadowNodeBase). Altering YGValueOrDefault itself prevented against the need to fire the Red Box error in the calling location of YGValueOrDefault, which would require many instances of repeated code that would be tedious to update in future and could lead to inconsistent behavior across different style keys. Altered YGValueOrDefault API to include a "key" string (indicates which prop/style type is being examined) so that error messages could be more descriptive. Added two calls to RedBox func: (1) for '#px' and '#pt' formats; (2) all other unexpected formats. 

_Snippet of RedBox Call (1)_
image

Snippet of RedBox Call (2)
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6837)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp [hunk 1]
```diff
@@ -271,7 +271,7 @@ static float NumberOrDefault(const winrt::Microsoft::ReactNative::JSValue &value
   return result;
 }
 
-static YGValue YGValueOrDefault(const winrt::Microsoft::ReactNative::JSValue &value, YGValue defaultValue) {
+static YGValue YGValueOrDefault(const winrt::Microsoft::ReactNative::JSValue &value, YGValue defaultValue, ShadowNodeBase& shadowNode, std::string key) {
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:274]: String parameters should generally not be passed by value. The story on what to use where in C++ is much more confusing than it should be, but for here, you could keep it as `const std::string&` instead of `std::string`.

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp [hunk 2]
```diff
@@ -290,10 +290,13 @@ static YGValue YGValueOrDefault(const winrt::Microsoft::ReactNative::JSValue &va
       folly::dynamic pct(str);
       return YGValue{static_cast<float>(pct.asDouble()), YGUnitPercent};
     }
+    if (str.length() > 2 && (str.substr((str.length() - 2), 2) == "px" || str.substr((str.length() - 2), 2) == "pt")) {
+      shadowNode.RedBox("Value '" + static_cast<std::string>(value.AsString()) + "' for " + key + " is invalid. Cannot be converted to YGValue. '" + str.substr((str.length() - 2), 2) + "' unit not needed. Simply use integer value.");
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:294]: I don't think you want to `static_cast` to a value. Did you run into issues using the raw result of `value.AsString()`?

**Comment by acoates-ms** [comment]
This doesn't look like the RedBox provides particularly useful information to identify the component causing the issue.

Does the equivalent error on iOS/android provide the component stack?  This feels like something where the error would be better of being detected in the component tree on the JS side, which would be able to provide much better context.

File: vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp [hunk 3]
```diff
@@ -162,4 +162,8 @@ void ShadowNodeBase::YellowBox(const std::string &message) const noexcept {
   GetViewManager()->GetReactContext().CallJSFunction("RCTLog", "logToConsole", folly::dynamic::array("warn", message));
 }
 
+void ShadowNodeBase::RedBox(const std::string &message) const noexcept {
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp:165]: I know you didn't add this, but having these methods on ShadowNodeBase isn't very cohesive. It creates a convenience for certain functions in certain parts of ViewManagers that cannot be used generically, and isn't part of the ViewManager interface.

A pattern to allow these to be used more generically could be free functions that accept a `ReactContext`. That would allow ViewManagers or other bits of the code to trigger these errors in a generic way, Depending on your comfort level, feel free to leave this as is and file an issue for someone to take a look.

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp [hunk 4]
```diff
@@ -290,10 +290,13 @@ static YGValue YGValueOrDefault(const winrt::Microsoft::ReactNative::JSValue &va
       folly::dynamic pct(str);
       return YGValue{static_cast<float>(pct.asDouble()), YGUnitPercent};
     }
+    if (str.length() > 2 && (str.substr((str.length() - 2), 2) == "px" || str.substr((str.length() - 2), 2) == "pt")) {
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:293]: This is super tricky, but ends up allocating some extra strings that we don't need. Because this function is called frequently, we likely want to avoid this.

Could you instead use [`string::compare`](https://en.cppreference.com/w/cpp/string/basic_string/compare) to compare at a given index without creating a substring?

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp (hunk 2 above)
Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:294]: I didn't give just value.AsString() a try; I believe I just copied the format from Line 291 for the float cast. Just tried the change now and it works. 👍

**Comment by NickGerleman** [comment]
> This doesn't look like the RedBox provides particularly useful information to identify the component causing the issue.
> 
> Does the equivalent error on iOS/android provide the component stack? This feels like something where the error would be better of being detected in the component tree on the JS side, which would be able to provide much better context.

From the original issue, looks like iOS also does this in native. 
image

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp (hunk 2 above)
Comment (NickGerleman) [reply vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:294]: For more context, `static_cast` has a couple of uses. One is to treat a pointer to one type as a pointer to another (e.g. casting from superclass to a subclass). Another is to change the representation of a primitive. E.g. converting between `double` and `float`.

**Comment by chiaramooney** [comment]
> This doesn't look like the RedBox provides particularly useful information to identify the component causing the issue.
> 
> Does the equivalent error on iOS/android provide the component stack? This feels like something where the error would be better of being detected in the component tree on the JS side, which would be able to provide much better context.

@acoates-ms @NickGerleman 
This is a screenshot I took from running in Android, doesn't seem like Android gives stack information for where the issue is in the js files either. More context would definitely be better though if it's possible.

image

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp (hunk 2 above)
Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:294]: Ah yes makes sense. Thanks for the extra info!

File: vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp (hunk 3 above)
Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp:165]: I see that makes sense. And would that free function continue to live in ShadowNodeBase? I guess the one other question I have in my understanding is that CallJSFunction expects to be called by an IReactContext but NativeUIManager for example uses a ReactContext. Is there a way to convert from a ReactContext to a IReactContext? Or is there an equivalent for CallJSFunction for ReactContexts?

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp (hunk 4 above)
Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp:293]: Yes definitely. I'll change that now.

**Comment by acoates-ms** [comment]
I suspect it could be done on the JS side by adding a process function for the appropriate style properties in Libraries\Components\View\ReactNativeViewViewConfig.js.  It would be a core change rather than a RNW change.  

That would potentially improve the error for all the platforms.

File: vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp (hunk 3 above)
Comment (NickGerleman) [reply vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp:165]: It would probably make sense to live in a separate file somewhere. It's probably fine to leave this as is for now though.

Re the difference between ReactContext and IReactContext, the former is a wrapper around the latter. The IReactContext interface is generated from an IDL file and has certain restrictions, where the wrapper is the more user friendly API.

You can get the underlying IReactContext from the ReactContext by calling its "Handle" function, and you can go the other way by passing an IReactContext to the ReactContext constructor. This pattern is present in a few other places in this code.

**Review by NickGerleman — APPROVED** [review]

**Review by asklar — COMMENTED** [review]
looks like I had forgotten to click on submit review :( anyway, here were my comments i had saved :)

File: vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp]: Based on my testing this should not be able to work. Android and iOS don't accept the units of px or pt in general or even just '12' (a string with just a number) is not accepted. So the only valid string inputs are '12%' for example. Just tried '12% ' and that produces an error for Android.
