### PR TITLE
Autolink best effort

### LINKED ISSUE #8047: Older modules cannot be autolinked (e.g. Clipboard, DateTimePicker, Slider)
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 45.79 GB / 63.84 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31328.270 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.0.0-7e05480cc => 0.0.0-7e05480cc
    react-native-windows: 0.65.0-preview.1 => 0.65.0-preview.1
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.19041
- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: All

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an RNW app. Issue should repro on any RNW >= 0.63
2. Add the clipboard, datetimepicker, and react-native-picker modules to the app.
3. Run `npx react-native autolink-windows --logging`.
4. Observe that the autolinking script finds all three projects and states that it is adding them to the application.
5. Open AutolinkedNativeModules.g.cpp.  Observe that the three modules are not included in this file. 
6. Edit App.js to use the components from these modules. 
7. Run your app. Observe that the app will throw errors because it is unable to find the modules. 

## Expected Results
All three modules appear in AutolinkedNativeModules.g.cpp. No editing on native code is necessary to successfully use the components. 

## Snack, code example, screenshot, or link to a repository:
See React Native Gallery if you want to easily repro.

### PR DESCRIPTION
**Pull request by asklar**
Best-effort autolinking - if a module was built without the standard module project template, use it for autolinking anyway

Fixes #8047 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8053)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 1]
```diff
@@ -425,6 +425,16 @@ export class AutolinkWindows {
             'projects' in windowsDependency &&
             Array.isArray(windowsDependency.projects)
           ) {
+            if (
+              windowsDependency.projects.length === 0 &&
+              dependencyName.includes('react-native')
+            ) {
+              // the dependency is probably a react native module, but we didn't find a module project
```
Comment (jonthysell) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:432]: When we implement modules delivered via nuget (as specd) we'll only want to throw an error if both `projects` and `nugetPackages` is empty.

File: packages/@react-native-windows/cli/src/config/configUtils.ts [hunk 2]
```diff
@@ -140,7 +140,15 @@ export function findDependencyProjectFiles(winFolder: string): string[] {
 
   // Try to find any project file that appears to be a dependency project
   for (const projectFile of allProjects) {
-    if (isRnwDependencyProject(path.join(winFolder, projectFile))) {
+    // A project is marked as a RNW dependency iff either:
+    // - If the project has the standard native module imports, or
+    // - If we only have a single project (and it doesn't have the standard native module imports),
+    // pick it and hope for the best. This enables autolinking for modules that were written
```
Comment (jonthysell) [inline packages/@react-native-windows/cli/src/config/configUtils.ts:146]: Does this actually make those older modules work or just pass the buck? Checking for the targets ensures that the module is properly loading the same version of RNW as the app among other things.

I'm fine with relaxing this logic if it enables older modules without us needing to revisit them.

**Review by jonthysell — APPROVED** [review]

File: packages/@react-native-windows/cli/src/config/configUtils.ts (hunk 2 above)
Comment (asklar) [reply packages/@react-native-windows/cli/src/config/configUtils.ts:146]: yes this makes clipboard and the other modules link in :)
