### PR TITLE
[Telemetry] Expand field sanitization to codedError.data

### LINKED ISSUE #14158: Expand PII scrubbing to all Error telemetry fields
### Problem Description

Some fields in Error telemetry instances are not processed for removed PII.

For instance, call stacks are correctly processed to remove PII from file paths, but other fields can potentially include such information and are not being processed yet.

### Steps To Reproduce

N/A

### Expected Results

PII scrubbing should occur for all Error telemetry fields.

### CLI version

N/A

### Environment

```markdown
N/A
```

### Community Modules

_No response_

### Target Platform Version

None

### Target Device(s)

_No response_

### Visual Studio Version

None

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by danielayala94**
## Description

Expand sanitization checks in telemetry, in this case error telemetry instances (and more specifically, all the string fields in `codedError.data`).

### Type of Change
Bug fix.

### Why
In telemetry error instances, certain fields may potentially contain file paths. This requires sanitization checks - they already exist for other telemetry fields.

Resolves #14158 

### What
In `Telemetry.trackException()`, take the `codedError` struct (i.e., a struct that contains error information), check each field in the struct if it's a string. If it is, perform sanitization; this will replace any filepaths with `[path]`.

## Screenshots
N/A

## Testing
Added a unit test to verify a codedError.data struct containing:
fieldWithPath - sanitization will modify remove a filepath with `[path]`.
fieldWithNoPath - a string that won't be modified.
fieldWithNoString - non-string, won't be modified.

## Changelog
Yes

Add a brief summary of the change to use in the release notes for the next release.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/14161)

### CODE REVIEW

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 1]
```diff
@@ -442,6 +442,21 @@ export class Telemetry {
       data: codedError?.data ?? {},
     };
 
+    // Scrub any potential PII present in codedError.data array, as long as the data is a string.
+    if (Object.keys(codedErrorStruct.data).length > 0) {
```
Comment (jonthysell) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:446]: What types are possible to put in `data[field]`? Can we change the type of Data to be `Record<string, string>`? I'm worried this fix will leave us open to something else in the future, like a nested object (which the current `Record<String,any>` type currently allows for).

**Review by jonthysell — CHANGES_REQUESTED** [review]

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 1 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:446]: We can then call sanitize on every field. And we can toString or toJSON any non-string data value.

Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:446]: The alternative would be to create a `sanitizeAny()` which can recursively through the entire potential tree and call sanitize on every string it finds. then make sure we're doing that any place that we have an `any`

Comment (danielayala94) [reply packages/@react-native-windows/telemetry/src/telemetry.ts]: I improved the fix by using recursion, so it now traverses all fields, inspecting arrays and nested objects appropriately, and sanitizes if the "leaf" value is a string.

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 2]
```diff
@@ -531,4 +534,30 @@ export class Telemetry {
 
     return exceptionData;
   }
+
+  static traverseCodedErrorStruct(
```
Comment (jonthysell) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:538]: This is close, but could you instead perhaps call this something like `sanitizeAny` that can take `any` type, then if it's an Array, recurse through the items or if it's an object, recurse through the fields?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 3]
```diff
@@ -531,4 +534,30 @@ export class Telemetry {
...
+  ) {
+    for (const key in data) {
+      if (Object.prototype.hasOwnProperty.call(data, key)) {
+        const value = data[key];
+        const currentPath = [...path, key];
+
+        if (Array.isArray(value)) {
+          // Replace the array by reading all elements in it,
+          // then check if they are strings. If that's the case, sanitize.
+          data[key] = value.map(item =>
```
Comment (jonthysell) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:550]: This won't sanitize an array of objects will it?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 4]
```diff
@@ -531,4 +534,26 @@ export class Telemetry {
 
     return exceptionData;
   }
+
+  static sanitizeAny(data: any): any {
```
Comment (jonthysell) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:538]: In the future we may want to move `sanitizeAny` into errorUtils so we can unit test it independently but you can save that for another PR if you like

**Review by jonthysell — APPROVED** [review]

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 4 above)
Comment (danielayala94) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:538]: Created #14247
