### PR TITLE
Fix to allow authorization header to be added.

### LINKED ISSUE #2466: Bug: Unable to add authorization header to network requests from javascript.
In NetworkingModule.cpp the headers are appended to the headers object.
https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Modules/NetworkingModule.cpp#L266

This throws when trying to add an authorization header.

The most straight-forward fix is to use TryAppendWithoutValidation instead of Append.

### PR DESCRIPTION
**Pull request by stecrain**
fixes #2466 

Changing this to TryAppendWithoutValidation seems like the most developer friendly fix for this issue.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/2467)

### CODE REVIEW

**Comment by stecrain** [comment]
@kmelmon @acoates-ms @rozele 
Any concerns with this approach?

This issue has come up in the past for the C# implementation (ex: #2040)
I think this change keeps the network module much simpler compared to the previous fixes.

File: vnext/ReactUWP/Modules/NetworkingModule.cpp [hunk 1]
```diff
@@ -263,7 +263,7 @@ void NetworkingModule::NetworkingHelper::SendRequest(const std::string& method,
         else if (_stricmp(name.c_str(), "content-encoding") == 0)
           contentEncoding = value;
         else
-          request.Headers().Append(facebook::react::unicode::utf8ToUtf16(name), facebook::react::unicode::utf8ToUtf16(value));
+          request.Headers().TryAppendWithoutValidation(facebook::react::unicode::utf8ToUtf16(name), facebook::react::unicode::utf8ToUtf16(value));
```
Comment (kmelmon) [inline vnext/ReactUWP/Modules/NetworkingModule.cpp]: >TryAppendWithoutValidation [](start = 28, length = 26)

Would it be safer to only use TryAppendWithoutValidation() if name == "Authorization", otherwise fallback to use Append()?

Comment (stecrain) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: If you feel that is the right call I am fine with making that change.

I personally think that the validation performed by Append is unexpected.
There are a couple more headers that can cause this as well, HttpHeaderContentCollection expects consumers to use the properties for any value that has a property.
https://docs.microsoft.com/en-us/uwp/api/windows.web.http.headers.httpcontentheadercollection.contentdisposition

I believe that using TryAppendWithoutValidation gives the most control to the developer and will prevent this from coming up again.

But I acknowledge that this is not my decision to make :) and if you feel strongly that this should be scoped to Authorization headers I am happy to make that change.

Comment (kmelmon) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: My main concern is security - if the validation done by Append is adding protection from security vulnerabilities then I'd prefer to use it as much as possible.  I honestly don't know what validation it's performing though.  If there's no real security aspect then your change is fine as is.

Comment (stecrain) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: That's a fair point.
I tried to skim through the source for Append vs TryAppendWithoutValidation, but there is too much abstraction to easily be able to say that this is generically safe.
I don't believe there is a security aspect, but I'm not a security expert.

I think you are correct, the right thing to do in this case is to only use TryAppendWithoutValidation for the Authentication header. I'll update the PR today.
Thanks for taking a look!

Comment (stecrain) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: Apologies for the delay on getting the update. But better than never (I hope :) )

Comment (kmelmon) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: Thanks!  good to go

Comment (stecrain) [reply vnext/ReactUWP/Modules/NetworkingModule.cpp]: awesome thanks!

**Comment by stecrain** [comment]
@kmelmon unfortunately I don't think have permission to merge this
image

can you click the button for me please :)
