### PR TITLE
Folly::Dynamic.asInt() throws when the type is not Int

### LINKED ISSUE #2484: Text throws ARITH_LOSS_OF_PRECISION with non-integer letterSpacing
## Repro steps
```jsx
<Text style={{letterSpacing: 10.5}}>foo</Text>
```
## Observed behavior
RNW throws with Folly error ARITH_LOSS_OF_PRECISION, because the conversion to integer loses the 0.5.
## Expected behavior
Silently lose precision. Other react native platforms do not throw with a non-integer letterSpacing.

### PR DESCRIPTION
**Pull request by StephenLPeters**
It throws because of a check that the value before the cast within asInt() is the same as the value after the cast so we have assert(double->asInt() == originalDouble) which isn't necessarily true.

Replace isInt() with isNumber() and get/asInt() with asDouble(), somtimes static_cast back to int/int64_t.

Fixes #2484

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/2561)

### CODE REVIEW

File: vnext/ReactUWP/Utils/PropertyUtils.h [hunk 1]
```diff
@@ -101,7 +101,7 @@ void SetBorderBrush(const T& element, const winrt::Windows::UI::Xaml::Media::Bru
 }
 
 template <class T>
-bool TryUpdateBackgroundBrush(T& element, const std::string& propertyName, const folly::dynamic& propertyValue)
+bool TryUpdateBackgroundBrush(T& element, const folly::dynamic& propertyName, const folly::dynamic& propertyValue)
```
Comment (ahimberg) [inline vnext/ReactUWP/Utils/PropertyUtils.h]: >isNumber [](start = 22, length = 8)

What is your branch based on?  I already have isNumber here?
