### PR TITLE
Autolinking fixes for C++ / C# interop

### LINKED ISSUE #6218: C++ app/lib project templates use C# projects
We should not require any C# components in C++ apps or modules by default.

Related: #5549 
CC @jonthysell

### LINKED ISSUE #6291: Config doesn't see dependencies that only specify sourceDir
A library package set up with a source folder other than "windows" should be able to just specify sourceDir in their react-native.config.js, i.e.:

```js
module.exports = {
  dependency: {
    platforms: {
      windows: {
        sourceDir: './src/windows',
      },
    },
  },
};
```

Current workaround is to just specify the the `projects` array, i.e.:

```js
module.exports = {
  dependency: {
      windows: {
        sourceDir: './src/windows',
        solutionFile: 'ModuleName.sln',
        projects: [
          {
            projectFile: 'ModuleName\\ModuleName.csproj',
            directDependency: true,
          }
        ],
      },
    },
  },
};
```

`sourceDir` is required if you specify the `projects` array, but you shouldn't need a `projects` array just for `sourceDir` to be recognized. The bug is in dependencyConfig.ts.

### LINKED ISSUE #6292: Autolinking for C++ app adds Win32 config for C# module when it should be x86
Autolinking adds project config entries for the module into the app's solution file.

It should insert x86 but it instead inserts Win32, so it doesn't build. Error something like:

` Please check to make sure that you have specified a valid combination of Configuration and Platform for this
project.  Configuration='Debug'  Platform='Win32'.`

### PR DESCRIPTION
**Pull request by jonthysell**
This PR fixes various issues with C++ and C# interop with autolinking.

* Adds a new AutolinkedNativeMdoules.g.props to apps so autolinking can
  also generate properties alongside the targets
* When autolinking detects a C++ app requiring a C# module, it now
  sets ConsumeCSharpModules = true automatically
* Fixed issues with relative paths during `react native config`
* Removed C# projects from C++ templates, autolinking will add it when
  necessary
* Fixed issue with adding Win32 config to solution for C# projects
* Fixed issue with only specifying sourceDir in dependency config
* Moved AutolinkedNativeModules.g.targets and AutolinkedNativeModules.g.props into shared-app/proj
* Added jest e2e tests for `react-native config`

Closes #6218
Closes #6291
Closes #6292

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6375)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 1]
```diff
@@ -401,6 +411,48 @@ async function updateAutoLink(
         changesNecessary;
     }
 
+    // Generating props for app project consumption
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:414]: Would be great if we could add some unit tests for this, not that the CLI lets you add them pretty easily. This logic has gotten pretty tricky, so I think they could help a lot.

Comment (kmelmon) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:414]: +1 
We also have issue #5882 tracking creating a sample native module and adding an automated test to ensure autolinking works.  I'd love to see that happen as it will help guarantee autolinking works end-to-end.

---
In reply to: [514454496](https://github.com/microsoft/react-native-windows/pull/6375#discussion_r514454496) [](ancestors = 514454496)

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 2]
```diff
@@ -401,6 +411,48 @@ async function updateAutoLink(
...
+        windowsDependencies[dependencyName].projects.forEach(project => {
+          if (project.directDependency && project.projectLang === 'cs') {
+            addCsModuleSupport = true;
+          }
+        });
+      }
+
+      if (addCsModuleSupport) {
+        propertiesForProps += `\n    <ConsumeCSharpModules>true</ConsumeCSharpModules>`;
+      }
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:429]: do we need to check whether this prop is already defined?

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 3]
```diff
@@ -471,6 +523,29 @@ async function updateAutoLink(
...
+          'Microsoft.ReactNative.Managed.CodeGen//Microsoft.ReactNative.Managed.CodeGen.csproj',
+        ),
+        projectName: 'Microsoft.ReactNative.Managed.CodeGen',
+        projectLang: 'cs',
+        projectGuid: '{ADED4FBE-887D-4271-AF24-F0823BCE7961}',
+        projectTypeGuid: '{9A19103F-16F7-4668-BE54-9A1E7A4F7556}',
+      });
+    }
+
     verboseMessage(
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:549]: nice

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 4]
```diff
@@ -471,6 +523,29 @@ async function updateAutoLink(
...
+      });
+      projectsForSolution.push({
+        projectFile: path.join(
+          rnwRoot,
+          'Microsoft.ReactNative.Managed.CodeGen//Microsoft.ReactNative.Managed.CodeGen.csproj',
+        ),
+        projectName: 'Microsoft.ReactNative.Managed.CodeGen',
+        projectLang: 'cs',
+        projectGuid: '{ADED4FBE-887D-4271-AF24-F0823BCE7961}',
+        projectTypeGuid: '{9A19103F-16F7-4668-BE54-9A1E7A4F7556}',
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:545]: consider making these consts
also why is the project above not have a project type guid but this one does?

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 2 above)
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:429]:
```suggestion
    let csModule = '';

    if (projectLang === 'cpp') {
      for (const dependencyName in windowsDependencies) {
        windowsDependencies[dependencyName].projects.forEach(project => {
          if (project.directDependency && project.projectLang === 'cs') {
            csModule = project.projectName;
          }
        });
      }

      const addCsModuleSupport: boolean = (csModule !== '');

      if (addCsModuleSupport) {
        propertiesForProps += `\n    <!-- Auto-generated by autolinking due to dependency on C# module ${csModule}: -->`;
        propertiesForProps += `\n    <ConsumeCSharpModules>true</ConsumeCSharpModules>`;
      }
```

**Review by asklar — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 4 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:545]: All C++ projects use one guid for project type. All "normal" c# projects use one guid for project type.

dotnet core (for the codegen project) uses a different one.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 2 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:429]: I like this idea, but more than one project can be responsible, so I'll build an array.

File: vnext/template/cs-app/src/AutolinkedNativeModules.g.props [hunk 5]
```diff
@@ -0,0 +1,6 @@
+<?xml version="1.0" encoding="utf-8"?>
+<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```
Comment (dannyvv) [inline vnext/template/cs-app/src/AutolinkedNativeModules.g.props:2]: I did some factoring to share as much between cpp and cs as possible.
Please consider if i ti makes sense to place this in `template\shared-app\src` since the file seems identical between cs and cpp

**Review by dannyvv — APPROVED** [review]
:shipit:

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 2 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:429]: Why would we support that? So people could break their build?

File: vnext/template/cs-app/src/AutolinkedNativeModules.g.props (hunk 5 above)
Comment (jonthysell) [reply vnext/template/cs-app/src/AutolinkedNativeModules.g.props:2]: Done.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 1 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:414]: Added unit tests

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:414]: Thank you for adding these!

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+    path.join(windowsDir, 'SimpleCSharpLib.sln'),
+    replacements,
+    null,
+  );
+
+  const projDir = path.join(windowsDir, 'SimpleCSharpLib');
+  if (!fs.existsSync(projDir)) {
+    fs.mkdirSync(projDir);
+  }
+  void copyAndReplace(
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:135]: Do these need to be awaited instead of using the void operator? You can have async tests with Jest, and that all works out fine.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts [hunk 7]
```diff
@@ -0,0 +1,141 @@
+/**
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:1]: Depending on how long these takes, consider renaming `test` to `e2etest`. The difference is that unit tests are run in parallel, and on save when the cli project is open. So you would want to keep heavier stuff under e2etest.

I definitely need to document that somewhere...

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts [hunk 8]
```diff
@@ -0,0 +1,141 @@
...
+  WindowsDependencyConfig,
+} from '../config/dependencyConfig';
+
+import {copyAndReplace} from '../generator-common';
+
+const templateRoot = path.resolve('../../../vnext/template');
+
+const testProjectGuid = '{416476D5-974A-4EE2-8145-4E331297247E}';
+
+function projectTests(testLibName: string, setup?: Function): void {
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:21]: nit: `Function` doesn't have great type safety, and some linters will tell you not to use it (we don't have the rules enabled right now). Consider something like `() => void` instead, or `() => Promise<void>` if async.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts [hunk 9]
```diff
@@ -0,0 +1,141 @@
...
+  const folder = path.resolve('src/test/projects/', testLibName);
+  const rnc = require(path.join(folder, 'react-native.config.js'));
+
+  if (setup !== undefined) {
+    setup(folder);
+  }
+
+  test(`dependencyConfig - ${testLibName} (userConfig is null)`, () => {
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:29]: I think this is fine, but a tip for the future is that Jest has builtin support for this pattern by using `test.each`. See https://github.com/microsoft/react-native-windows/blob/master/packages/react-native-platform-override/src/test/Override.test.ts#L99-L102 for an example.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts (hunk 6 above)
Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:135]: Oh, looking at things, this works because the only async bit currently is the prompt. I think await would be needed if other async code was added to copyAndReplace.

**Review by NickGerleman — APPROVED** [review]
Took a look at the tests and overall looks good!

Two main comments:
- Would be good to move from `test` to `e2etest` if the tests do I/O. They'll still be picked up automatically in `yarn test`
- `copyAndReplace` needs to be awaited instead of using the void operator.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts (hunk 8 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:21]: Fixed.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts (hunk 6 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:135]: Fixed async issues.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts (hunk 9 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts:29]: Fixed.

File: packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts (hunk 7 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/test/dependencyConfig.test.ts]: Fixed.
