### PR TITLE
fix(rnpm-plugin-windows): fixes installing react-native-windows to a …

### LINKED ISSUE #1155: Installing react-native-windows to react-native project initialized with yarn
When installing react-native-windows with node v8 & npm v5 into an existing react-native project, the react-native-cli reports no more commands except for init after `npm install rnpm-plugin-windows` succeeds.

### PR DESCRIPTION
**Pull request by sayar**
…project initialized with yarn

Fixes #1155

### CODE REVIEW

File: local-cli/rnpm/windows/src/common.js [hunk 1]
```diff
@@ -93,8 +93,21 @@ const getReactNativeAppName = function () {
...
+ * When using an old global react-native-cli@1.0.0 (or older), we don't want
+ * to install React Native with npm, and React + Jest with yarn.
+ * Let's be safe and not mix yarn and npm in a single project.
+ * @param projectDir e.g. /Users/martin/AwesomeApp
+ */
+const isGlobalCliUsingYarn = function(projectDir) {
+  return fs.existsSync(path.join(projectDir, 'yarn.lock'));
+}
+
+
```
Comment (rozele) [inline local-cli/rnpm/windows/src/common.js]: delete extra newline here.

**Comment by sayar** [comment]
Removed extra newline, can I merge or do you want to @rozele ?
