### PR TITLE
Fix app template to use app.json's name for main component name

### LINKED ISSUE #7451: Error on metro server after "successfully" loading app
## Error
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (C:\Users\emanuelmartin\Documents\git\pruebahrsl\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:347:17)
    at new UnableToResolveError (C:\Users\emanuelmartin\Documents\git\pruebahrsl\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (C:\Users\emanuelmartin\Documents\git\pruebahrsl\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (C:\Users\emanuelmartin\Documents\git\pruebahrsl\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at C:\Users\emanuelmartin\Documents\git\pruebahrsl\node_modules\metro\src\lib\transformHelpers.js:317:42
    at C:\Users\emanuelmartin\Documents\git\pruebahrsl\node_modules\metro\src\Server.js:1471:14
    at Generator.next (<anonymous>)

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 
     5.0.1-alpha.2
2. `npx react-native info`:
     System:
    OS: Windows 10 10.0.21337
    CPU: Unknown
    Memory: 526.00 MB / 3.00 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31112.23 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.0
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  Install and init react-native-windows template
2. Run windows template
3. Add up my project files and modules
4. Windows autolinking
4. Restart server and Visual Studio
5. Run for Debug on Local Machine in Visual Studio

## Expected Results
Describe what you expected to happen.
App to show correctly, but error on Metro appears 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

### PR DESCRIPTION
**Pull request by jonthysell**
In react-native-community/cli#1370 the CLI was
changed in a way that can produce different values for the project name
(name in package.json) and the main component name (name in app.json).

Historically, sometimes older templates didn't set name in the
package.json at all, instead using app.json. So our CLI was written to
accomodate that logic (load name from package.json if possible, then
fallback to app.json). Either way, we use that single value everywhere
in our template, for file and varaible names.

This PR updates our template to use the value in app.json, if possible,
to set the component name to load. This matches the behavior on iOS and
and Android.

Closes #7451

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7464)

### CODE REVIEW

**Comment by jonthysell** [comment]
I still need to add tests to this.

File: packages/@react-native-windows/cli/src/generator-windows/index.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@ import * as fs from 'fs';
 import * as os from 'os';
 import * as semver from 'semver';
 import * as _ from 'lodash';
+import * as findUp from 'find-up';
```
Comment (acoates-ms) [inline packages/@react-native-windows/cli/src/generator-windows/index.ts:16]: find-up isn't a dependency of @react-native-windows/cli currently.  You'll either need to add it, or use something else.

**Review by acoates-ms — APPROVED** [review]

**Review by asklar — APPROVED** [review]

File: packages/@react-native-windows/cli/src/generator-windows/index.ts [hunk 2]
```diff
@@ -179,6 +180,12 @@ export async function copyProjectTemplateAndReplace(
   const packageGuid = uuid.v4();
   const currentUser = username.sync()!; // Gets the current username depending on the platform.
 
+  let mainComponentName = newProjectName;
+  const appJsonPath = findUp.sync('app.json', {cwd: destPath});
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/generator-windows/index.ts:184]: We should use the async version of this if possible.

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts:184]: Same below. File system reads can take arbitrarily long (e.g. over a network file system) and can cause the spinner to stutter.

File: vnext/template/shared-app/src/MainPage.xaml [hunk 3]
```diff
@@ -15,7 +15,7 @@
 {{^languageIsCpp}}
         x:Name="reactRootView"
 {{/languageIsCpp}}
-        ComponentName="{{ name }}"
+        ComponentName="{{ mainComponentName }}"
```
Comment (NickGerleman) [inline vnext/template/shared-app/src/MainPage.xaml:18]: For my own understanding, how does mismatched component name connect to the metro issue? I would have guessed that we would see failures funding the component from the AppRegistry instead of bundling errors.

Comment (NickGerleman) [reply vnext/template/shared-app/src/MainPage.xaml:18]: From the metro callstack, I wonder if the issue is in two parts. E.g.

1. We redbox bc of mismatch
2. Metro barfs on redbox

Where this would fix 1, preventing 2, but there's still am underlying issue.

Comment (jonthysell) [reply vnext/template/shared-app/src/MainPage.xaml:18]: Metro has a bug where it misreports the error message within metro.

The red box on my machine *does* give an error about not finding the component name in the App registry.

Comment (NickGerleman) [reply vnext/template/shared-app/src/MainPage.xaml:18]: Good to know. Could we leave the Metro bug open to track it separately?

File: packages/@react-native-windows/cli/src/generator-windows/index.ts (hunk 2 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts:184]: Switched to using async for findup, but we literally do every fs fead/write sync in template generation.

**Comment by jonthysell** [comment]
I didn't realize there aren't already any generateWindows tests - taking that as a separate task so we can unblock people.

https://github.com/microsoft/react-native-windows/issues/7469

File: packages/@react-native-windows/cli/src/generator-windows/index.ts (hunk 2 above)
Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts]: There's some history behind that. Up until 0.63 the generator boundary was synchronous, so everything in it _needed_ to be sync. That was fixed to enable usage of standard async prompting libraries. In the future it would be great to use methods like `fs.promises.readFile` instead of `fs.readFileSync` to avoid more debt.

Comment (asklar) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts]: I tried making some more of the operations in autolinking async but IIRC the entrypoint for autolinking _must_ be synchronous

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts]: I remember for generator I had to change a chain of like 10 functions to be async. I think the CLI allows async commands though.

We have ESLint rules now that warn if you're missing an "await", so that style of refactoring should be pretty safe.

Comment (asklar) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts]: IIRC when I made the autolink entrypoint async, the RN CLI did not await it
See https://github.com/microsoft/react-native-windows/pull/7196

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts]: It looks like commands can be async, but dependencyConfig/projectConfig cannot be. See https://github.com/react-native-community/cli/blob/master/packages/cli-types/src/index.ts

Super nit, but we should probably be setting an explicit type for our dependency functions so the type checker can catch if we have unexpected return type for those functions (eg sync vs async). The react-native-config.js file exposing this I think has to be untyped, so we need to check types within the boundary.
