### PR TITLE
Fixes textTransform recursion

### LINKED ISSUE #7534: Virtual text children overwritten when no textTransform specified
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Apply the repro from this commit to RNTester: https://github.com/rozele/react-native-windows/commit/cda922d71b7913a12f5648c8515fc8a7f1326a80
2. Open the Text component example
3. Notice that the last line in the textTransform example should be "xYz" but is instead "zYz".

## Expected Results
The last line of the textTransform example should be: 'Should be "xYz": xYz'
Instead it is: 'Should be "xYz": zYz'

## Snack, code example, screenshot, or link to a repository:
Repro in this commit for RNTester: https://github.com/rozele/react-native-windows/commit/cda922d71b7913a12f5648c8515fc8a7f1326a80

Here's a screenshot:
playground 4_5_2021 9_44_50 AM

### LINKED ISSUE #7535: The 'textTransform' prop is shallow and not applied from root TextBlock
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Apply the repro from this commit to RNTester: https://github.com/rozele/react-native-windows/commit/d5036febe389ff8ecd12c140503f718598b9c3a1
2. Open the Text component example
3. In the textTransform example, the third-to-last line should be "ABC" but is "ABc"
4. In the textTransform example, the second-to-last line should be all uppercase but is all lowercase
5. In the textTransform example, the last line should toggle between uppercase and no transform, but does not.

## Expected Results
The third-to-last line of the textTransform example should be: 'Should be "ABC": ABC'
Instead it is: 'Should be "ABC": ABc'

The second-to-last line of the textTransform example should be 'ALL TEXT HERE SHOULD BE UPPERCASE'
Instead it is: 'all text here should be uppercase'

The last line should toggle between 'Click to toggle uppercase. Toggle off.' and 'CLICK TO TOGGLE UPPERCASE. TOGGLE ON.'

## Snack, code example, screenshot, or link to a repository:
Repro in this commit for RNTester: https://github.com/rozele/react-native-windows/commit/d5036febe389ff8ecd12c140503f718598b9c3a1

Here's a screenshot:
playground 4_5_2021 10_35_27 AM

### PR DESCRIPTION
**Pull request by rozele**
This change includes a number of fixes to the approach to textTransform. There were 4 issues with the previous textTransform approach that this diff solves:
1. The textTransform prop was only applied to the parent TextBlock when it had a single raw text child
2. The textTransform prop on a virtual text Span only recursed one level
3. The one-level textTransform approach had a bug where the last raw text value overwrote all Run text values (#7534)
4. The textTransform prop did not update correctly when changed

Rather than holding state in the TransformableText struct, this change keeps the originalText state exclusively in RawTextShadowNode, and only when a parent VirtualTextShadowNode or TextShadowNode has a textTransform setting (that is not "none" or undefined). The VirtualTextShadowNode and TextShadowNode holds only the TextTransform prop value (and not any originalText value which was causing the issue in #7534). When a child is added to either a TextShadowNode or VirtualTextShadowNode, we now attempt to recursively apply the textTransform on the child sub-tree (wherever textTransform is not explicitly overwritten). Whenever the textTransform prop changes on VirtualTextShadowNode or TextShadowNode, we now attempt to recurse over all children of that node to apply the textTransform (wherever it is not explicitly overwritten).

Fixes #7534
Fixes #7535

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7538)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Utils/TransformableText.h [hunk 1]
```diff
@@ -7,13 +7,13 @@ namespace Microsoft::ReactNative {
 struct TransformableText final {
   enum class TextTransform : uint8_t { Undefined, None, Uppercase, Lowercase, Capitalize };
 
-  TextTransform textTransform{TextTransform::Undefined};
-  std::wstring originalText{};
-
-  std::wstring TransformText() const noexcept {
+  static winrt::hstring TransformText(
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Utils/TransformableText.h:10]: Was trying to minimize the diff here, but if we want to, we can lift this out of the TransformableText struct (and eliminate the TransformableText struct).

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 2]
```diff
@@ -20,28 +24,57 @@ using namespace xaml::Documents;
...
-          run.Text(childVTSN.transformableText.TransformText());
-        }
+    m_highlightData.data.emplace_back(childVTSN.m_highlightData);
+  }
+  Super::AddView(child, index);
+}
+
+void VirtualTextShadowNode::ApplyTextTransform(TransformableText::TextTransform transform, bool hasChanged, bool inherited) {
+    if (!inherited || textTransform == TransformableText::TextTransform::Undefined) {
+    if (auto uiManager = GetNativeUIManager(GetViewManager()->GetReactContext()).lock()) {
```
Comment (rectified95) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:38]: nit: indentation is off slightly

**Review by rectified95 — APPROVED** [review]
I think this is a good change.
Adding @asklar for another view

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 3]
```diff
@@ -43,18 +46,17 @@ class TextShadowNode final : public ShadowNodeBase {
   }
 
   void AddView(ShadowNode &child, int64_t index) override {
+    auto &childNode = static_cast<ShadowNodeBase &>(child);
+    VirtualTextShadowNode::ApplyTextTransformToNode(childNode, textTransform, /* hasChanged = */false);
+
+    auto run = childNode.GetView().try_as<winrt::Run>();
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:52]: I think this might be able to be a superclass of Run, either Inline or TextElement

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 4]
```diff
@@ -43,18 +46,17 @@ class TextShadowNode final : public ShadowNodeBase {
...
     if (index == 0) {
-      auto run = static_cast<ShadowNodeBase &>(child).GetView().try_as<winrt::Run>();
       if (run != nullptr) {
         m_firstChildNode = &child;
         auto textBlock = this->GetView().as<xaml::Controls::TextBlock>();
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: we don't currently have RichTextBlock inbox, but if we did, this would need to be rewritten to allow RichTextBlock too

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 5]
```diff
@@ -43,18 +46,17 @@ class TextShadowNode final : public ShadowNodeBase {
...
-        std::wstring text(run.Text().c_str());
-        transformableText.originalText = text;
-        text = transformableText.TransformText();
-        textBlock.Text(winrt::hstring(text));
-
+        textBlock.Text(run.Text());
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:57]: it would be great to be able to use CharacterCasing instead but that's only available for TextBox, not TextBlock :(
Consider filing a xaml bug :)
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.charactercasing?view=winrt-19041

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 6]
```diff
@@ -20,28 +24,57 @@ using namespace xaml::Documents;
...
 void VirtualTextShadowNode::AddView(ShadowNode &child, int64_t index) {
-  auto view = static_cast<ShadowNodeBase &>(child).GetView();
-
-  if (auto run = view.try_as<xaml::Documents::Run>()) {
-    transformableText.originalText = run.Text().c_str();
-    run.Text(transformableText.TransformText());
-  } else if (auto span = view.try_as<xaml::Documents::Span>()) {
+  auto &childNode = static_cast<ShadowNodeBase &>(child);
+  ApplyTextTransformToNode(childNode, textTransform, /* hasChanged = */false);
+  if (auto span = childNode.GetView().try_as<xaml::Documents::Span>()) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:29]: see if this can be up-classed

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 7]
```diff
@@ -20,28 +24,57 @@ using namespace xaml::Documents;
...
+    const auto view = node.GetView();
+    const auto span = view.try_as<winrt::Span>();
+    const auto run = view.try_as<winrt::Run>();
+    if (span) {
+      auto &virtualTextChildNode = static_cast<VirtualTextShadowNode &>(node);
+      virtualTextChildNode.ApplyTextTransform(transform, hasChanged, /* inherited = */true);
+    } else if (run) {
+      auto &rawTextChildNode = static_cast<RawTextShadowNode &>(node);
+      auto originalText = rawTextChildNode.originalText;
+      if (originalText.size() != run.Text().size()) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:63]: can we get into a situation where these two have the same size but different content?
or vice-versa? w/surrogate pairs maybe?

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 8]
```diff
@@ -20,28 +24,57 @@ using namespace xaml::Documents;
...
-          // project the parent transform onto the child
-          childVTSN.transformableText.textTransform = transformableText.textTransform;
-          run.Text(childVTSN.transformableText.TransformText());
-        }
+    m_highlightData.data.emplace_back(childVTSN.m_highlightData);
+  }
+  Super::AddView(child, index);
+}
+
+void VirtualTextShadowNode::ApplyTextTransform(TransformableText::TextTransform transform, bool hasChanged, bool inherited) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:36]: looks like this can be const?

**Review by asklar — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 3 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:52]: The point of checking if it's a Run is so we can take advantage of the TextBlock fast path and lift the Run content into the TextBlock.Text field: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-block#performance-considerations

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 4 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: RichTextBlock would likely be a different root text component than TextBlock. But yes, if we change from TextBlock to RichTextBlock, this will need some adjustment (as I believe we'll need a top-level Paragraph inline in the RichTextBlock).

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 5 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:57]: Will do :)

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 4 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: It would probably be better to create a base shadow node type with a field that discriminates between virtual text (Span) and raw text (Run), but given that React Native's ABI-safe IViewManager implementation only supports FrameworkElement and higher right now (see #5539), a react-native-windows user would not be able to create a ViewManager for Inlines that would break this today.

Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: react-native-xaml creates Inlines/Runs and other non-frameworkelements
when a type is not an FE, I create a ContentControl and set the Content to be the non-FE element.
Then in AddView, I unwrap it from the ContentControl and set the right parent/child relationship (as well as transfer the Tag id)

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 7 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:63]: I *think* that raw text nodes are immutable. You cannot change the text prop on the raw text node, so once it's set, if the raw text value is changed, the entire Run will be replaced.

I am now questioning this, so I'll verify that raw text nodes are immutable and if they are leave a nice comment explaining why it's safe to use the length here :)

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 4 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: plus one thing to note that might be relevant: we have mixed-mode apps where part of the content is being created directly in XAML and other content in RNW, so it's important to make sure there are no assumptions made about how we might treat Run/Span/etc. differently inside of RNW (e.g. if we set an attached property on Runs created inside RNW, we should not expect all Runs to have that tag since some can come from outside)

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 8 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:36]: Yup :)

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 6 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:29]: This is just re-using whatever behavior was there before to test whether the highlight data (background color) needs to be updated. I don't want to break this here. At any rate, same comment as above. We're using Run vs. Span as a reasonably safe way to distinguish between VirtualTextShadowNode and RawTextShadowNode (safe because users of react-native-windows as of today cannot create ViewManagers that would return classes derived from Inline). Another way to handle this would be to create an InlineTextShadowNode base class to enable this differentiation.

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 4 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: @asklar - The react-native-windows TextViewManager does not do any ContentControl unwrapping today, that's an implementation detail of your plugin. We can safely assume that any Run or Span that is created *today* that can be added as a child to the TextBlock or a virtual text Span will come from either VirtualTextViewManager or RawTextViewManager.

If you'd prefer, I'm happy to change this "switch" behavior into a base shadow node class for inlines as an enum, but it's solving a problem that will not exist until a significant change to react-native-windows occurs (FrameworkElement -> DependencyObject base type for IViewManager). And the point at which that happens, we'll probably be on to Fabric and all these ViewManagers will be deprecated :D

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: Actually, I don't think this should change right now. I can't take the base shadow node class approach because I'm just shifting the assumption in an even less safe way to a static cast on the ShadowNode reference. At least the current approach uses try_as.

I suggest we keep the check as is for now, and at some point in the future (that may never come), if someone needs to extend this behavior to support user supplied or mixed-mode supplied Inlines, then we can fix then.

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 5 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:57]: Actually CharacterCasing is a little different. CharacterCasing actually changes the stored value of the typed text, where we only want to change the rendered value. I'd hate to file a bug for something we don't currently need and doesn't impact our app perf / memory usage significantly :)

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 4 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:56]: Changed my mind - we can use `node->GetViewManager()->GetName()` to check what type of view we're dealing with.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 7 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:63]: Indeed this was a good catch. Raw text nodes are not immutable, we re-use the runs.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 6 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:29]: Not fixing here as this is not modifying existing behavior.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 7 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp]: Fixed.

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 9]
```diff
@@ -260,4 +262,8 @@ void TextViewManager::OnDescendantTextPropertyChanged(ShadowNodeBase *node) {
   }
 }
 
+TextTransform TextViewManager::GetTextTransformValue(ShadowNodeBase *node) {
+  return static_cast<TextShadowNode *>(node)->textTransform;
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:266]: Not super happy about this, but I didn't want to pull TextShadowNode into the header. I'll at least add a safety check to make sure the shadow node is actually from RCTText

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:266]: The alternative to this approach was to force a full textTransform update from the root, which in practice is probably not very expensive, but this allows us to apply the correct inherited textTransform directly to a raw text node that changed (without needing to recurse the entire text tree).

File: vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp [hunk 10]
```diff
@@ -75,10 +62,34 @@ void RawTextViewManager::NotifyAncestorsTextChanged(ShadowNodeBase *nodeToUpdate
...
+      if (!std::wcscmp(nodeType, L"RCTText")) {
+        const auto textViewManager = static_cast<TextViewManager *>(viewManager);
+        if (textTransform == TextTransform::Undefined) {
+          textTransform = textViewManager->GetTextTransformValue(parent);
+        }
+
+        VirtualTextShadowNode::ApplyTextTransform(
+            *nodeToUpdate, textTransform, /* forceUpdate = */ false, /* isRoot = */ false);
+
+        if (parent->m_children.size() == 1) {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp:78]: Needed to move this until after we re-applied the textTransforms

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 4 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:55]: @rozele yes, it's an implementation detail of react-native-xaml but my point was more about making you aware that we have these hybrid apps, and where xaml objects can come into RNW even when they're not framework elements.
 FYI there is already new API for view managers that operates on `IInspectable`: [IViewManagerCreateWithProperties](https://microsoft.github.io/react-native-windows/docs/next/IViewManagerCreateWithProperties).

We still expect to get a FrameworkElement internally, but I'm hoping we can relax this in the future, and the fact that the API is based on IInspectable allows to do this transparently for the modules/apps out there that may use this new API.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp (hunk 7 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp]: thanks for verifying :)

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 9 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp]: sounds like an assert that the view manager is named Text or whatever it's called should be enough at least to catch things in debug :)
Ideally we have some level of rtti on these things without actually using rtti

**Comment by dannyvv** [comment]
FYI: Took the liberty of merging master to get past the CI issues.

**Comment by dannyvv** [comment]
@asklar Since you reviewed I'll leave the merge up to you.

**Comment by asklar** [comment]
@rozele I see you have a comment to make an update, so just ping me when it's ready to merge :)

File: vnext/Microsoft.ReactNative/Utils/TransformableText.h [hunk 11]
```diff
@@ -3,17 +3,15 @@
...
+
 namespace Microsoft::ReactNative {
 struct TransformableText final {
-  enum class TextTransform : uint8_t { Undefined, None, Uppercase, Lowercase, Capitalize };
-
-  TextTransform textTransform{TextTransform::Undefined};
-  std::wstring originalText{};
-
-  std::wstring TransformText() const noexcept {
+  static winrt::hstring TransformText(winrt::hstring originalText, TextTransform textTransform) noexcept {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Utils/TransformableText.h:10]: const reference for this?

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 9 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp]: This has been fixed with the view manager assertion.
