### PR TITLE
Calling UIManager.dispatchViewManagerCommand doesn't trigger a UI update

### LINKED ISSUE #7543: Calling UIManager.dispatchViewManagerCommand waits for UI changes before calling native code when building for Release on 0.64
On 0.63 and when building for Debug on 0.64, when we call `UIManager.dispatchViewManagerCommand` the native code `DispatchCommand` gets called immediately. When building for Release on 0.64, `DispatchCommand` seems to only be called on the next UI update.

This causes some issues on modules that depend on calling `DispatchCommand` without doing UI updates at the same time. `react-native-sketch-canvas` is an example of this, since it uses `PanResponder` to call `UIManager.dispatchViewManagerCommand` to enable real time drawing.

## Environment
1. `npx react-native --version`:
```
5.0.1-alpha.2
```

2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.64 GB / 15.92 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31129.286 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_262 - C:\Program Files\OpenJDK\openjdk-8u262-b10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.3
  npmGlobalPackages:
    *react-native*: Not Found
```

- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: Debug and Release

## Steps To Reproduce
Instructions that I used to create the sample repo I pushed to: https://github.com/jaimecbernardo/reproduce-rnw64-release-dispatch-command-issue

1. Create an app from the template:
```bash
npx react-native init ReproduceRNWReleaseBug --template react-native@^0.64.0
cd ReproduceRNWReleaseBug
npx react-native-windows-init --overwrite
```

2. Add a native module that exports a command to be called by `UIManager.dispatchViewManagerCommand`:
```C++
winrt::Windows::UI::Xaml::FrameworkElement winrt::reproducernwreleasebug::implementation::SimpleViewManager::CreateView() noexcept
{
    auto control = winrt::Windows::UI::Xaml::Controls::TextBlock();
    control.Text(L"This text hasn't been changed yet.");
    return control;
}

winrt::Windows::Foundation::Collections::IVectorView<winrt::hstring> winrt::reproducernwreleasebug::implementation::SimpleViewManager::Commands() noexcept
{
    auto commands = winrt::single_threaded_vector<hstring>();
    commands.Append(L"changeText");
    return commands.GetView();
}

void winrt::reproducernwreleasebug::implementation::SimpleViewManager::DispatchCommand(winrt::Windows::UI::Xaml::FrameworkElement const& view, winrt::hstring const& commandId, winrt::Microsoft::ReactNative::IJSValueReader const& commandArgsReader) noexcept
{
    auto commandArgs = winrt::Microsoft::ReactNative::JSValue::ReadArrayFrom(commandArgsReader);
    if (commandId == L"changeText")
    {
        if (auto control = view.try_as<winrt::Windows::UI::Xaml::Controls::TextBlock>())
        {
            control.Text(winrt::to_hstring(commandArgs[0].AsString()));
        }
    }
}
```

3. Access the command from JavaScript using `UIManager.dispatchViewManagerCommand` after a little delay:
```JavaScript
          <Text>Button to change the RNSimple contents after 1 second. Works on Debug. On Release, it waits for an UI change before sending the command.</Text>
          <Button title="ChangeText" onPress={() => {
            numberOfPresses++;
            let currentPresses = numberOfPresses;
            setTimeout( () => {
              UIManager.dispatchViewManagerCommand(
                nativeCompHandle,
                UIManager.getViewManagerConfig('RNSimple').Commands.changeText,
                [ "The button has been pressed " + currentPresses + " times." ]
              );
            }, 2000);
          }} />
          <RNSimple ref={ref => {nativeCompHandle = ReactNative.findNodeHandle(ref)}} style={{flex:1}}/>
```

4. Observe differences between running in Debug and Release:

```bash
npx react-native run-windows
```

```bash
npx react-native run-windows --release
```

## Expected Results
I expect for `DispatchCommand` to be called in a timely manner in a native module's code when I call `UIManager.dispatchViewManagerCommand` in Release on 0.64.  
Similar to how 0.63 works and how Debug on 0.64 works.

## Snack, code example, screenshot, or link to a repository:
I've added a reproduction repo here: https://github.com/jaimecbernardo/reproduce-rnw64-release-dispatch-command-issue

Expected behavior on both Debug and Release after clicking the button and waiting 2 seconds:

image

When building for Release, clicking the button won't change the text after 2 seconds:

image

The text will only change after doing something that forces the UI to update, like clicking the button again.

### PR DESCRIPTION
**Pull request by acoates-ms**
Fixes #7543.

When running in release mode, we run a bunch of native modules as JSI modules.  When making a call from JS -> Native using a native module, this triggers a new UI batch.   When going through a JSI module, this doesn't happen.  

This change causes any call to BatchingMessageQueueThread to cause a new batch to happen.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7575)

### CODE REVIEW

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 1]
```diff
@@ -57,20 +56,56 @@ void BatchingQueueThread::PostBatch() noexcept {
...
+  m_callInvoker = m_batchingQueueCallInvoker;
+}
+
+// Called from the JS thread, once the instance has had a chance to setup the NativeToJsBridge and calls to
+// getDecoratedNativeCallInvoker will work.
+void BatchingQueueThread::decoratedNativeCallInvokerReady(
+    std::weak_ptr<facebook::react::Instance> wkInstance) noexcept {
+  m_callInvoker->invokeAsync([wkInstance, this] {
+    if (auto instance = wkInstance.lock()) {
+      m_callInvoker = instance->getDecoratedNativeCallInvoker(m_callInvoker);
```
Comment (vmoroz) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:87]: >m_callInvoker [](start = 6, length = 13)

Should we protect access to this variable? The runOnQueue below can be called froma different thread.

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 2]
```diff
@@ -57,20 +56,56 @@ void BatchingQueueThread::PostBatch() noexcept {
...
+    }
+  });
+}
+
+BatchingQueueThread::~BatchingQueueThread() noexcept {}
+
+void BatchingQueueThread::runOnQueue(std::function<void()> &&func) noexcept {
+  m_callInvoker->invokeAsync(std::move(func));
```
Comment (vmoroz) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:95]: >m_callInvoker [](start = 2, length = 13)

Does it mean that some requests will go to one call invoker and others to another?

Comment (acoates-ms) [reply vnext/Shared/Threading/BatchingQueueThread.cpp:95]: Yes - That should be fine.  The only difference between the two is if it sets a flag in the NativeToJSBridge to force it to call onBatchComplete later.  The only time this will be happening is during boot, during which time a batch is going to get hit anyway.  If we really wanted to be sure, we could post an empty function after we do the switch.

File: vnext/Shared/Threading/BatchingQueueThread.h [hunk 3]
```diff
@@ -3,11 +3,41 @@
...
 #include <Shared/BatchingMessageQueueThread.h>
 #include <thread>
 
+namespace facebook::react {
+class Instance;
+}
+
 namespace react::uwp {
 
+struct BatchingQueueThread;
```
Comment (dannyvv) [inline vnext/Shared/Threading/BatchingQueueThread.h:16]: >BatchingQueueThread [](start = 7, length = 19)

nit: is fwd decl really needed? It is not used by BatchingQueueCallInvoker...

File: vnext/Shared/Threading/BatchingQueueThread.cpp (hunk 1 above)
Comment (acoates-ms) [reply vnext/Shared/Threading/BatchingQueueThread.cpp:87]: It should be safe.  But the logic to verify that is pretty convoluted -- and so not safe for future changes.  I'll just capture a ref to it.

Comment (acoates-ms) [reply vnext/Shared/Threading/BatchingQueueThread.cpp:87]: This should be ok.  The only place that this variable changes is from this code, and the actual value change will be on the UI thread. All other reads of the variable are on the UI thread.  The read in this code that is on the JS thread will always be before safe since the task to modify it is kicked off after that access.

File: vnext/Shared/Threading/BatchingQueueThread.h (hunk 3 above)
Comment (acoates-ms) [reply vnext/Shared/Threading/BatchingQueueThread.h]: Thanks - Left over from earlier iterations of the fix.

File: vnext/Shared/Threading/BatchingQueueThread.h [hunk 4]
```diff
@@ -3,11 +3,41 @@
...
+  void quitSynchronous() noexcept;
+  void PostBatch() noexcept;
+  void invokeSync(std::function<void()> &&func) noexcept override;
+
+ private:
+  std::shared_ptr<facebook::react::MessageQueueThread> m_queueThread;
+
+  using WorkItemQueue = std::vector<std::function<void()>>;
+  std::shared_ptr<WorkItemQueue> m_taskQueue;
+  std::mutex m_mutex;
```
Comment (asklar) [inline vnext/Shared/Threading/BatchingQueueThread.h:32]: I see we already had this but it seems unnecesary to keep a shared_ptr here instead of std::vector directly? it should std::move cleanly anyway

File: vnext/Shared/Threading/BatchingQueueThread.cpp (hunk 1 above)
Comment (vmoroz) [reply vnext/Shared/Threading/BatchingQueueThread.cpp:87]: No, it is not OK. Previously this code was called under the lock that has a guarantee of the thread safety. After this change we are going to have a race condition. Please add the lock back.

**Comment by vmoroz** [comment]
@acoates-ms, I am removing the AutoMerge tag to avoid accidental merge before the race condition for writing/reading the m_callInvoker variable is fixed.

**Comment by acoates-ms** [comment]
> @acoates-ms, I am removing the AutoMerge tag to avoid accidental merge before the race condition for writing/reading the m_callInvoker variable is fixed.

Oops.  I thought I'd pushed that change before setting the automerge.

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 5]
```diff
@@ -57,9 +54,48 @@ void BatchingQueueThread::PostBatch() noexcept {
...
+}
+
+// Called from the JS thread, once the instance has had a chance to setup the NativeToJsBridge and calls to
+// getDecoratedNativeCallInvoker will work.
+void BatchingQueueThread::decoratedNativeCallInvokerReady(
+    std::weak_ptr<facebook::react::Instance> wkInstance) noexcept {
+  std::scoped_lock lck(m_mutex);
+  m_callInvoker->invokeAsync([wkInstance, this] {
+    if (auto instance = wkInstance.lock()) {
+      m_callInvoker = instance->getDecoratedNativeCallInvoker(m_callInvoker);
```
Comment (vmoroz) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:84]: >m_callInvoker [](start = 6, length = 13)

We neeed to add the `std::scoped_lock lck(m_mutex);` inside of this lambda to protect the write access to the m_callInvoker. So that readers of the m_callInvoker can access it only after it completely changed.

File: vnext/Shared/Threading/BatchingQueueThread.cpp [hunk 6]
```diff
@@ -29,7 +26,7 @@ void BatchingQueueThread::runOnQueue(std::function<void()> &&func) noexcept {
 #endif
 }
 
-void BatchingQueueThread::ThreadCheck() noexcept {
+void BatchingQueueCallInvoker::ThreadCheck() noexcept {
```
Comment (vmoroz) [inline vnext/Shared/Threading/BatchingQueueThread.cpp:29]: >ThreadCheck [](start = 31, length = 11)

It seems to be unused. Should we delete it?

**Review by vmoroz — APPROVED** [review]
:shipit:
