### PR TITLE
Provide error message when an unhandled exception occurs in a native method (in Debug)

### LINKED ISSUE #7871: Native modules that call UI-affine APIs get whitescreened
Native modules that call platform APIs that require UI often run into white screen/crashes due to modules running on the JS thread.
We should add some error handling around the point where we call out to the native module, and try/catch for "you called on the wrong thread" hresult, and then redbox

### PR DESCRIPTION
**Pull request by asklar**
Fixes #7871 

Today when a native module calls an API that expects to be called on the UI thread, from the JS thread, an exception is raised and the app is forcefully terminated. This is because native module methods are `noexcept`.

This change adds some guardrails for developers to indicate what the issue was, and points them to our new documentation about posting work to the UI dispatcher. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7889)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp [hunk 1]
```diff
@@ -34,6 +82,10 @@ void ReactModuleBuilder::AddMethod(
         auto resultWriter = make<DynamicWriter>();
         auto resolveCallback = MakeMethodResultCallback(std::move(resolve));
         auto rejectCallback = MakeMethodResultCallback(std::move(reject));
+
+#ifdef DEBUG
+        Terminator term;
+#endif
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp:91]: nit: consider combining this code into one macro such as REACT_TERMINATE_GUARD.

File: vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp [hunk 2]
```diff
@@ -24,6 +24,54 @@ void ReactModuleBuilder::AddConstantProvider(ConstantProviderDelegate const &con
...
+    std::set_terminate([]() {
+      auto ex = std::current_exception();
+      if (ex) {
+        try {
+          std::rethrow_exception(ex);
+        } catch (const winrt::hresult_error &hr) {
+          wchar_t buf[1024] = {};
+          StringCchPrintf(
+              buf,
+              ARRAYSIZE(buf),
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp:49]: >ARRAYSIZE [](http://example.com/codeflow?start=14&length=9)

Consider using the standatd std::size() method instead of macro

File: vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp [hunk 3]
```diff
@@ -24,6 +24,54 @@ void ReactModuleBuilder::AddConstantProvider(ConstantProviderDelegate const &con
...
+#ifdef DEBUG
+// Starting with RNW 0.64, native modules are called on the JS thread.
+// Modules will usually call Windows APIs, and those APIs might expect to be called in the UI thread.
+// Developers can dispatch work to the UI thread via reactContext.UIDispatcher().Post(). When they fail to do so,
+// cppwinrt will grab the failure HRESULT (RPC_E_WRONG_THREAD), convert it to a C++ exception, and throw it.
+// However, native module methods are noexcept, meaning the CRT will call std::terminate and not propagate exceptions up
+// the stack. Developers are then left with a crashing app and no good way to debug it. To improve developers'
+// experience, we can replace the terminate handler temporarily while we call out to the native method. In the terminate
+// handler, we can inspect the exception that was thrown and give an error message before going down.
+struct Terminator final {
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp:37]: >Terminator [](http://example.com/codeflow?start=7&length=10)

Consider to have a more descriptive name. E.g. TerminateGuard, TerminateExceptionReporter, or something else along these lines.

Comment (vmoroz) [inline vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp:37]: >struct [](http://example.com/codeflow?start=0&length=6)

Please move this class above the ReactModuleBuilder class implementation. We should not split up ReactModuleBuilder  implmenetaiton inot two groups.

File: vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp [hunk 4]
```diff
@@ -24,6 +24,54 @@ void ReactModuleBuilder::AddConstantProvider(ConstantProviderDelegate const &con
...
+        } catch (const winrt::hresult_error &hr) {
+          wchar_t buf[1024] = {};
+          StringCchPrintf(
+              buf,
+              ARRAYSIZE(buf),
+              L"An unhandled exception (0x%x) occurred in a native module. The exception message was:\n\n%s",
+              hr.code(),
+              hr.message().c_str());
+          auto messageBox = reinterpret_cast<decltype(&MessageBoxW)>(
+              GetProcAddress(GetModuleHandle(L"ext-ms-win-ntuser-dialogbox-l1-1-0.dll"), "MessageBoxW"));
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp:55]: >GetModuleHandle [](http://example.com/codeflow?start=29&length=15)

Should we handle cases when we cannot load the DLL?

**Review by vmoroz — APPROVED** [review]
:shipit:

File: vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp (hunk 4 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp:55]: The DLL should always be loaded already (via apiset, at least on onecoreuap). There isn't much we can do other than continue to crash, do you have any ideas of what else we could do?

**Comment by NickGerleman** [comment]
I think this will definitely help a lot of users.
