### PR TITLE
Initialize ETW provider only once

### LINKED ISSUE #6945: Assert when reloading due to Tracelogging
#6869 added tracelogging events but those are supposed to be registered at most once per process lifetime so we crash on reload
```cpp
    _TLG_ASSERT(
        pProvider->RegHandle == 0,
        "TraceLoggingRegister called with already-registered handle");
```

```
>	Microsoft.ReactNative.dll!TraceLoggingRegisterEx(const _TlgProvider_t * hProvider, void(__stdcall*)(const _GUID *, unsigned long, unsigned char, unsigned __int64, unsigned __int64, _EVENT_FILTER_DESCRIPTOR *, void *) pEnableCallback, void * pCallbackContext) Line 2366	C++
 	Microsoft.ReactNative.dll!TraceLoggingRegister(const _TlgProvider_t * hProvider) Line 2353	C++
 	Microsoft.ReactNative.dll!facebook::react::tracing::initializeETW() Line 380	C++
 	Microsoft.ReactNative.dll!facebook::react::InstanceImpl::InstanceImpl(std::shared_ptr<facebook::react::Instance> && instance, std::string && jsBundleBasePath, std::vector<std::tuple<std::string,std::function<std::unique_ptr<facebook::xplat::module::CxxModule,std::default_delete<facebook::xplat::module::CxxModule>> __stdcall(void)>,std::shared_ptr<facebook::react::MessageQueueThread>>,std::allocator<std::tuple<std::string,std::function<std::unique_ptr<facebook::xplat::module::CxxModule,std::default_delete<facebook::xplat::module::CxxModule>> __stdcall(void)>,std::shared_ptr<facebook::react::MessageQueueThread>>>> && cxxModules, std::shared_ptr<facebook::react::TurboModuleRegistry> turboModuleRegistry, std::unique_ptr<facebook::react::InstanceCallback,std::default_delete<facebook::react::InstanceCallback>> && callback, std::shared_ptr<facebook::react::MessageQueueThread> jsQueue, std::shared_ptr<facebook::react::MessageQueueThread> nativeQueue, std::shared_ptr<facebook::react::DevSettings> devSettings, std::shared_ptr<facebook::react::IDevSupportManager> devManager) Line 309	C++
 	Microsoft.ReactNative.dll!facebook::react::InstanceImpl::MakeNoBundle(std::shared_ptr<facebook::react::Instance> && instance, std::string && jsBundleBasePath, std::vector<std::tuple<std::string,std::function<std::unique_ptr<facebook::xplat::module::CxxModule,std::default_delete<facebook::xplat::module::CxxModule>> __stdcall(void)>,std::shared_ptr<facebook::react::MessageQueueThread>>,std::allocator<std::tuple<std::string,std::function<std::unique_ptr<facebook::xplat::module::CxxModule,std::default_delete<facebook::xplat::module::CxxModule>> __stdcall(void)>,std::shared_ptr<facebook::react::MessageQueueThread>>>> && cxxModules, std::shared_ptr<facebook::react::TurboModuleRegistry> turboModuleRegistry, std::unique_ptr<facebook::react::InstanceCallback,std::default_delete<facebook::react::InstanceCallback>> && callback, std::shared_ptr<facebook::react::MessageQueueThread> jsQueue, std::shared_ptr<facebook::react::MessageQueueThread> nativeQueue, std::shared_ptr<facebook::react::DevSettings> devSettings, std::shared_ptr<facebook::react::IDevSupportManager> devManager) Line 231	C++
 	Microsoft.ReactNative.dll!facebook::react::CreateReactInstance(std::shared_ptr<facebook::react::Instance> && instance, std::string && jsBundleBasePath, std::vector<std::tuple<std::string,std::function<std::unique_ptr<facebook::xplat::module::CxxModule,std::default_delete<facebook::xplat::module::CxxModule>> __stdcall(void)>,std::shared_ptr<facebook::react::MessageQueueThread>>,std::allocator<std::tuple<std::string,std::function<std::unique_ptr<facebook::xplat::module::CxxModule,std::default_delete<facebook::xplat::module::CxxModule>> __stdcall(void)>,std::shared_ptr<facebook::react::MessageQueueThread>>>> && cxxModules, std::shared_ptr<facebook::react::TurboModuleRegistry> turboModuleRegistry, std::unique_ptr<facebook::react::InstanceCallback,std::default_delete<facebook::react::InstanceCallback>> && callback, std::shared_ptr<facebook::react::MessageQueueThread> jsQueue, std::shared_ptr<facebook::react::MessageQueueThread> nativeQueue, std::shared_ptr<facebook::react::DevSettings> devSettings) Line 39	C++
 	Microsoft.ReactNative.dll!Mso::React::ReactInstanceWin::Initialize::__l2::<lambda>() Line 389	C++
 	Microsoft.ReactNative.dll!Mso::Executors::Internal::ExecutorInvoker::Invoke<void <lambda>(void) &>(Mso::React::ReactInstanceWin::Initialize::__l2::void <lambda>(void) & callback) Line 204	C++
 	Microsoft.ReactNative.dll!Mso::Futures::FutureTaskInvoke<Mso::Executors::Executor,void <lambda>(void),void,void,4>::Invoke(const Mso::Async::ArrayView<unsigned char> & taskBuffer, Mso::Futures::IFuture * future, Mso::Futures::IFuture * __formal) Line 384	C++
 	Microsoft.ReactNative.dll!Mso::Futures::FutureImpl::Invoke() Line 271	C++
 	Microsoft.ReactNative.dll!Mso::Futures::FutureCallback::Invoke() Line 980	C++
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<void __stdcall(void)> && task, std::optional<std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000>>>> endTime) Line 206	C++
 	Microsoft.ReactNative.dll!Mso::ThreadPoolSchedulerWin::WorkCallback(_TP_CALLBACK_INSTANCE * __formal, void * context, _TP_WORK * __formal) Line 89	C++
```

### PR DESCRIPTION
**Pull request by asklar**
Fixes #6945 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7019)

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]

File: vnext/Shared/tracing/tracing.cpp [hunk 1]
```diff
@@ -376,7 +376,11 @@ void initializeJSHooks(jsi::Runtime &runtime) {
 
 void initializeETW() {
```
Comment (NickGerleman) [inline vnext/Shared/tracing/tracing.cpp:377]: nit: since this is now safe to call after ETW has been initialized, consider renaming to `ensureETWInitialized` to make less ambiguous at callsite.

**Review by NickGerleman — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]
