### PR TITLE
Fix invalidation bug

### LINKED ISSUE #6586: [RNTester] button at bottom of page looks wrong
Looks like the image is being "centered" around its top, left (which is the XAML behavior) as opposed to the center of the image (default for web):

image

### PR DESCRIPTION
**Pull request by kmelmon**
Fixes #6586

This fixes a long standing bug in layout that was discovered recently in RNTester.  This recent bug fix exposed the bug:
https://github.com/microsoft/react-native-windows/pull/6451

The bug is straightforward.  In ViewPanel we do this to invalidate for arrange when top/left changes:

```
/*static*/ void ViewPanel::SetTop(xaml::UIElement const &element, double value) {
  element.SetValue(TopProperty(), winrt::box_value<double>(value));
  element.InvalidateArrange();
}
```
The call to element.InvdliateArrange() is the bug.

This is making the assumption that the ViewPanel is responsible for positioning itself.  This isn't correct.  It is the parent's responsibility for positioning its children.  Thus we are invalidating the wrong element.  We should invalidate the parent, not ourselves.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6593)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/ViewPanel.cpp [hunk 1]
```diff
@@ -127,12 +127,25 @@ winrt::AutomationPeer ViewPanel::OnCreateAutomationPeer() {
...
-  element.InvalidateArrange();
+  InvalidateForArrange(element);
+}
+
+void ViewPanel::InvalidateForArrange(xaml::UIElement element) {
+  // If the element's position has changed, we must invalidate the parent for arrange,
+  // as it's the parent's responsibility to arrange its children.
+  auto parent = VisualTreeHelper::GetParent(element);
+  if (parent) {
+    parent.try_as<xaml::UIElement>().InvalidateArrange();
```
Comment (kmelmon) [inline vnext/Microsoft.ReactNative/Views/ViewPanel.cpp:143]: >parent.try_as<xaml::UIElement>().InvalidateArrange(); [](start = 4, length = 53)

Note that we have other scenarios that might be broken, due to us having more than one element in the hierarchy for a View.  The parent of a ViewPanel might not itself be a ViewPanel.  I find this code confusing!  I'm choosing not to address that potential issue here, to make it safer for us to backport this fix, and do more research first.

Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/ViewPanel.cpp:143]: should test the result of try_as since it could be a frameworkelement but not a uielement?

File: vnext/Microsoft.ReactNative/Views/ViewPanel.cpp [hunk 2]
```diff
@@ -127,12 +127,25 @@ winrt::AutomationPeer ViewPanel::OnCreateAutomationPeer() {
...
   element.SetValue(LeftProperty(), winrt::box_value<double>(value));
-  element.InvalidateArrange();
+  InvalidateForArrange(element);
+}
+
+void ViewPanel::InvalidateForArrange(xaml::UIElement element) {
+  // If the element's position has changed, we must invalidate the parent for arrange,
+  // as it's the parent's responsibility to arrange its children.
+  auto parent = VisualTreeHelper::GetParent(element);
+  if (parent) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/ViewPanel.cpp:142]: nit, can fold init and decl into the if:
```suggestion
  if (auto parent = VisualTreeHelper::GetParent(element)) {
```

**Review by asklar — APPROVED** [review]

**Comment by NickGerleman** [comment]
@rozele they are separate issues. Please feel free to ping offline for details.
