### PR TITLE
Integrate April 22 RN Nightly Build

### LINKED ISSUE #7618: Remove Fork of NativeEventEmitter.js following 4/29 integration.
Source as of 4/15 in `Libraries/EventEmitter/NativeEventEmitter.js` contains bug which causes Accessibility Windows page in RNTester to fail to load due to an issue with the addListener method for AppTheme. Fix https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2 solves issue and fires a warning instead of a Red Box error. Forked file to create `src/Libraries/EventEmitter/NativeEventEmitter.windows.js` which contains the bug fix. 

TO-DO: Remove forked file following 4/29 integration as bug fix will then be in core.

### PR DESCRIPTION
**Pull request by NickGerleman**
Fixes #7618

Commits: https://github.com/facebook/react-native/compare/ae07c53d0...5127c71d6

Mostly mechanical resolution apart from needing to fixup depedency resolution to use newer Metro.

Not yet locally tested to build or run.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7680)

### CODE REVIEW

**Comment by NickGerleman** [comment]
Tested Rex/react-native-win32 locally. E2ETest is passing for UWP. Looks good.

File: vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp [hunk 1]
```diff
@@ -87,28 +92,32 @@ void MapBufferBuilder::putNull(Key key) {
...
 
-void MapBufferBuilder::putInt(Key key, int value) {
+void MapBufferBuilder::putInt(Key key, int32_t value) {
   uint8_t *bytePointer = reinterpret_cast<uint8_t *>(&(value));
   storeKeyValue(key, bytePointer, INT_SIZE);
 }
 
-void MapBufferBuilder::ensureDynamicDataSpace(int size) {
+void MapBufferBuilder::ensureDynamicDataSpace(int32_t size) {
   if (dynamicDataValues_ == nullptr) {
```
Comment (dannyvv) [inline vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:101]: this code should probably assert `size >= 0`. Still don't see why it is not backed by a std: collections...

File: yarn.lock [hunk 2]
```diff
@@ -9035,10 +9035,10 @@ react-clone-referenced-element@^1.0.1:
   resolved "https://registry.yarnpkg.com/react-clone-referenced-element/-/react-clone-referenced-element-1.1.0.tgz#9cdda7f2aeb54fea791f3ab8c6ab96c7a77d0158"
   integrity sha512-FKOsfKbBkPxYE8576EM6uAfHC4rnMpLyH6/TJUL4WcHUEB3EUn8AxPjnnV/IiwSSzsClvHYK+sDELKN/EJ0WYg==
 
-react-devtools-core@^4.12.0:
-  version "4.12.2"
-  resolved "https://registry.yarnpkg.com/react-devtools-core/-/react-devtools-core-4.12.2.tgz#4198f42fec867ed82dd0ee0f059b450e703b2b1e"
-  integrity sha512-cvAiJCSIIan2A22o4j4Twc7PdDrwqiAQVBeZ+osS2T/wv2Ua3a0J8Sgx4pTH5Y7VoWn5WiGCHkAW4S1lYl3kcA==
+react-devtools-core@^4.6.0:
```
Comment (dannyvv) [inline yarn.lock:9038]: Just a not: Interesting how we somehow are rolling back the declared dependency, the resolved version increases, so fine... but still what dependency downgraded for 12 to 6?

Comment (dannyvv) [reply yarn.lock:9038]: A found it, `react-native@0.0.0-5127c71d6` downgraded from 12 to 6. 
Do you think this warrants an investigation in case there are compatibility issues? Since we override it with 4.12.4?

**Review by dannyvv — APPROVED** [review]

File: yarn.lock (hunk 2 above)
Comment (NickGerleman) [reply yarn.lock:9038]: I'll test dev tools manually with the resolution removed.

File: vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp (hunk 1 above)
Comment (NickGerleman) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:101]: I haven't payed much attention to what the data structure is used for, but std::unordered_map is infamous for being slow relative to more cache optimized hash tables.

The standard for unordered_map effectively dictates that is used chained hashing/linked lists. This is because it requires iterators to have pointer stability. This does a lot of pointer chasing, where as a buffer based structure (like open addressing) is much faster on modern hardware.

**Comment by rectified95** [comment]
fixed invalid commit range link in description.

File: yarn.lock (hunk 2 above)
Comment (NickGerleman) [reply yarn.lock:9038]: Oh, I see that this is the yarn resolution for upstream semver constraint.

I put a bit of thought into this. I think I'd rather we align to upstream semver contraints as-is, since that it what users of RN will get when they install.

File: vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp [hunk 3]
```diff
@@ -160,10 +169,14 @@ void MapBufferBuilder::putMapBuffer(Key key, MapBuffer &map) {
...
 MapBuffer MapBufferBuilder::build() {
+  react_native_assert(
+      (keyValues_ != nullptr) &&
+      "Error when building mapbuffer with invalid datastructures.");
+
   // Create buffer: [header] + [key, values] + [dynamic data]
-  int bufferSize = keyValuesOffset_ + dynamicDataOffset_;
+  int32_t bufferSize = keyValuesOffset_ + dynamicDataOffset_;
 
-  _header.bufferSize = static_cast<uint16_t>(bufferSize);
```
Comment (rectified95) [inline vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: Removing this fails my local build (I include the updated .h file too).
@NickGerleman Have you tried it locally?

Comment (NickGerleman) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: It seemed to succeed locally. There was a recent upstream change that I think changed sizes. Do you see anything different if you do a clean build?

Comment (rectified95) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: I made an update to the core PR and found this to be needed. I guess I must have done something wrong, since the CI passes here. 
Still, applying this change to a local master from a few days ago fails for me.

Comment (NickGerleman) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: This integration itself pulls in MapBuffer changes to use int32_t in more places. So I think the removal may only work now.

Comment (rectified95) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: This pulls in all the latest changes to MapBuffer from core. If this works, then we can actually remove the forked file, since it's now no different from core, I think.

Comment (NickGerleman) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: There's one last cast still, from size_t to int32_t. The uint16_t ones should be gone though.

Comment (rectified95) [reply vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp:166]: Double-checked and the int32_t cast was added on Apr 15, so we could have deleted this file in this PR.
