### PR TITLE
Fixes issues with Text backgroundColor

### LINKED ISSUE #7568: Text height does not get updated when removing inline
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone RNTester example: https://github.com/rozele/react-native-windows/tree/pressableTextRepro
2. Open Text component example
3. Scroll to "Pressable edge cases" example
4. On the line that says "Adding pressables to the tree works just fine.", click the button to add a pressable view.
5. Resize the window so the word "remove" in the new view wraps to a new line.
6. Click the word "remove".
7. Observe that the TextBlock height does not change, even though the span was removed.

## Expected Results
The TextBlock height should shrink once the wrapped text is removed. It works as expected when you toggle the wrapped text by clicking the "Click to add" button.

## Snack, code example, screenshot, or link to a repository:
RNTester example: https://github.com/rozele/react-native-windows/tree/pressableTextRepro

https://user-images.githubusercontent.com/1106239/114274071-be5b8d00-99ea-11eb-82ad-57ea4c57e573.mp4

### LINKED ISSUE #7569: Text highlight does not get updated as text changes
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone RNTester example: https://github.com/rozele/react-native-windows/tree/pressableTextRepro
2. Open Text component example
3. Scroll to "Pressable edge cases" example
4. On the line that says "Disabling pressables is okay too.", click "Click to disable".
5. Observe that the text highlighting is *not* removed for the "Click here." text and the highlighting is not updated for the "Click to enable." text.

## Expected Results
Text highlighting updates with changes to nested text.

## Snack, code example, screenshot, or link to a repository:
RNTester example: https://github.com/rozele/react-native-windows/tree/pressableTextRepro

https://user-images.githubusercontent.com/1106239/114274278-a3d5e380-99eb-11eb-8981-ca435c2f962a.mp4

### LINKED ISSUE #8407: TextHighlighter is not removed when backgroundColor prop is removed
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an example that removes sets and removes `backgroundColor` from nested text. E.g.:
```js
  const [backgroundColor, setBackgroundColor] = useState();
  ...
  <Text onPress={() => setBackgroundColor(backgroundColor ? undefined : 'yellow'}>
     <Text style={{backgroundColor}}>
        This
      </Text>
      text {backgroundColor ? 'should' : 'shouldn't' be highlighted.
   </Text>
```
2. 

## Expected Results
When backgroundColor prop is removed, TextHighlighter should be removed.

## Snack, code example, screenshot, or link to a repository:

https://user-images.githubusercontent.com/1106239/129052237-d7d168fb-92ac-43a3-a786-b9a780d1557e.mp4

## Notes

This is likely related to #7569

### PR DESCRIPTION
**Pull request by rozele**
There were two issues with the Text backgroundColor prop:
1. Changes to the backgroundColor prop on virtual text nodes did not update their corresponding TextHighlighters
2. Changes to the underlying text did not update the TextHighlighter ranges

This change forces a refresh of all TextHighlighters any time:
1. A raw text node changes text value
2. A virtual text node is added or removed from the text tree
3. A virtual text or root text node updates its backgroundColor prop

TODOs:
- [x] Pass inherited foreground color down so virtual text highlighters apply the correct foreground color
- [x] Update snapshots since highlighter approach has changed
- [x] Produce a before and after video to ensure RNTester TextExample still works as expected
- [x] Add examples to RNTester to toggle background colors on RCTText and RCTVirtualText to see highlighter updates working
- [x] Add examples to RNTester to remove RCTRawText and RCTVirtualText nodes to see highlighter updates working

Fixes #7568
Fixes #7569
Fixes #8407

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8408)

### CODE REVIEW

**Comment by rozele** [comment]
This is not very effecient. It means we do a DFS on the text tree every time the text changes to recalculate the TextHightlighters. One optimization we could consider is to maintain state in the text shadow nodes to signal whether the DFS is required. We could do this in one of two ways:
1. Maintain a per node count of children with backgroundColor set
2. Maintain a boolean flag at the root text node that signals whether any children have backgroundColor.

My preference would be the latter. I initially thought that having counts at each node would allow us to prune which parts of the tree we walk, but we always need to do a complete DFS to get correct TextRange values for the highlighter.

To go along with the latter approach, the idea would be that any time a RCTText or RCTVirtualText node has a backgroundColor, the RCTText node boolean flag would get set to true. When an RCTVirtualText node removes it's background color, we need to do a DFS to update the TextHighlighters anyway, so at that point we could conditionally reset the flag to false if no highlighters are created.

**Comment by rozele** [comment]
Another thing to consider is to keep the highlighters and just update the ranges, but its less memory efficient to maintain a map from virtual text nodes to their corresponding TextHighlighters than to just recompute the set of required highlighters. Also, recalculating the highlighters from scratch feels a bit less bug prone. I'm open to reconsidering this option if someone feels strongly about it.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 1]
```diff
@@ -106,8 +129,7 @@ bool VirtualTextViewManager::UpdateProperty(
   // FUTURE: In the future cppwinrt will generate code where static methods on
   // base types can be called.  For now we specify the base type explicitly
   if (TryUpdateForeground<winrt::TextElement>(span, propertyName, propertyValue)) {
-    static_cast<VirtualTextShadowNode *>(nodeToUpdate)->m_highlightData.foregroundColor = ColorFrom(propertyValue);
-  } else if (TryUpdateFontProperties<winrt::TextElement>(span, propertyName, propertyValue)) {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:110]: Add this back.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 2]
```diff
@@ -106,8 +129,7 @@ bool VirtualTextViewManager::UpdateProperty(
   // FUTURE: In the future cppwinrt will generate code where static methods on
   // base types can be called.  For now we specify the base type explicitly
   if (TryUpdateForeground<winrt::TextElement>(span, propertyName, propertyValue)) {
-    static_cast<VirtualTextShadowNode *>(nodeToUpdate)->m_highlightData.foregroundColor = ColorFrom(propertyValue);
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:109]: Notify root that highlight may need to be updated

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 3]
```diff
@@ -72,73 +70,102 @@ class TextShadowNode final : public ShadowNodeBase {
...
+  void RemoveChildAt(int64_t indexToRemove) override {
+    if (indexToRemove == 0) {
+      m_firstChildNode = nullptr;
     }
+    Super::RemoveChildAt(indexToRemove);
+    UpdateTextHighlighters();
+  }
+
+  void UpdateTextHighlighters() {
+    const auto textBlock = this->GetView().as<xaml::Controls::TextBlock>();
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:95]: Add logic to conditionally do a DFS only when needed

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 4]
```diff
@@ -274,18 +301,28 @@ YGMeasureFunc TextViewManager::GetYogaCustomMeasureFunc() const {
...
-    // If name is set, it's controlled by accessibilityLabel, and it's already
-    // handled in FrameworkElementViewManager. Here it only handles when name is
-    // not set.
-    if (xaml::Automation::AutomationProperties::GetLiveSetting(element) != winrt::AutomationLiveSetting::Off &&
-        xaml::Automation::AutomationProperties::GetName(element).empty() &&
-        xaml::Automation::AutomationProperties::GetAccessibilityView(element) != winrt::Peers::AccessibilityView::Raw) {
-      if (auto peer = xaml::Automation::Peers::FrameworkElementAutomationPeer::FromElement(element)) {
-        peer.RaiseAutomationEvent(winrt::AutomationEvents::LiveRegionChanged);
+void TextViewManager::OnDescendantTextPropertyChanged(ShadowNodeBase *node, PropertyChangeType propertyChangeType) {
+  if (!std::wcscmp(node->GetViewManager()->GetName(), GetName())) {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:305]: use `== 0`

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 5]
```diff
@@ -72,73 +70,102 @@ class TextShadowNode final : public ShadowNodeBase {
...
-      highData.foregroundColor = parentForeColor;
+  void RemoveChildAt(int64_t indexToRemove) override {
+    if (indexToRemove == 0) {
+      m_firstChildNode = nullptr;
     }
+    Super::RemoveChildAt(indexToRemove);
+    UpdateTextHighlighters();
+  }
+
+  void UpdateTextHighlighters() {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:94]: Add logic to update highlighters when root text backgroundColor and foregroundColor change

**Comment by chrisglein** [comment]
Maybe related to the issue @chiaramooney has been looking at (#8395)?

**Comment by rozele** [comment]
> Maybe related to the issue @chiaramooney has been looking at (#8395)?

@chrisglein Quite possibly. I believe fast refresh does not re-render the entire tree, just updates props that have changed. If that's the case, I believe fast refresh would suffer the same limitations that programmatically updating a prop through a state change faces.

**Comment by rozele** [comment]
Here is a side beside comparison of the before (left) and after (right) for the RNTester TextExample:

https://user-images.githubusercontent.com/1106239/129084756-27bf531d-0f99-4972-b1ac-c8391667f2af.mp4

Note that nothing has "changed" in the UX, though I believe the snapshots will have changed slightly since this simplifies the way highlights are applied and applies highlights to the entire span of text.

**Comment by rozele** [comment]
Here's a before and after with this change:
Before:

https://user-images.githubusercontent.com/1106239/129129067-d2072ac9-5c03-4263-9dff-32c85162521b.mp4

After:

https://user-images.githubusercontent.com/1106239/129129090-9bcc3ab7-c2d7-4534-b555-ec441b0b6163.mp4

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 6]
```diff
@@ -72,73 +70,102 @@ class TextShadowNode final : public ShadowNodeBase {
...
     }
+    Super::RemoveChildAt(indexToRemove);
+    UpdateTextHighlighters();
+  }
 
-    for (const auto &el : span.Inlines()) {
-      if (auto run = el.try_as<winrt::Run>()) {
-        if (highData.backgroundColor) {
-          AddHighlighter(highData.backgroundColor.value(), highData.foregroundColor, run.Text().size());
+  void UpdateTextHighlighters() {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:94]: rename to make it clear that this isn't just an update but that it throws away the text highlighters collection?
e.g. `RecalculateTextHighlighters`

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 7]
```diff
@@ -274,23 +307,33 @@ YGMeasureFunc TextViewManager::GetYogaCustomMeasureFunc() const {
...
-    // If name is set, it's controlled by accessibilityLabel, and it's already
-    // handled in FrameworkElementViewManager. Here it only handles when name is
-    // not set.
-    if (xaml::Automation::AutomationProperties::GetLiveSetting(element) != winrt::AutomationLiveSetting::Off &&
-        xaml::Automation::AutomationProperties::GetName(element).empty() &&
-        xaml::Automation::AutomationProperties::GetAccessibilityView(element) != winrt::Peers::AccessibilityView::Raw) {
-      if (auto peer = xaml::Automation::Peers::FrameworkElementAutomationPeer::FromElement(element)) {
-        peer.RaiseAutomationEvent(winrt::AutomationEvents::LiveRegionChanged);
+void TextViewManager::OnDescendantTextPropertyChanged(ShadowNodeBase *node, PropertyChangeType propertyChangeType) {
+  if (std::wcscmp(node->GetViewManager()->GetName(), GetName()) == 0) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:311]: curious if we would ever want to have text functionality exposed through the abi so that community VMs can reuse it, we need to come up with a better check than "what's your VM's name".

Maybe abstract this check away in a helper `IsTextNode` and add a comment that for the time being only the `TextViewManager` can use this functionality?

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h [hunk 8]
```diff
@@ -16,17 +17,15 @@ struct VirtualTextShadowNode final : public ShadowNodeBase {
...
 
   void AddView(ShadowNode &child, int64_t index) override;
+  void RemoveChildAt(int64_t indexToRemove) override;
+  void removeAllChildren() override;
 
-  static void ApplyTextTransform(ShadowNodeBase &node, TextTransform transform, bool forceUpdate, bool isRoot);
+  void NotifyAncestorsTextPropertyChanged(TextViewManager::PropertyChangeType propertyChangeType);
 
-  struct HighlightData {
-    std::vector<HighlightData> data;
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h:23]: I'm missing where we point to the highlights for the children; is it no longer needed because now we do `NotifyAncestorsTextPropertyChanged`?

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h:23]: Yeah. Each `VirtualTextShadowNode` maintains its foreground color and background color. If either of these change, we call `NotifyAncestorsTextPropertyChanged`, which traverses to the root text to trigger highlighter recalculation.

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h:23]: Which makes me wonder if we want to create an optimization for `backgroundColor` and `color` prop changes. We could store the `TextHightlighter` in the `VirtualTextShadowNode`, and if only the prop value changes (the children don't change), we just update the brushes directly on the `TextHighlighter`.

I guess it's just a question of whether we think that's a common enough scenario to optimize for. The current design is "universal" for the relevant mutations of the text (text nodes added, text nodes removed, background color changed, foreground color changed, etc.), but not necessarily optimal.

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 7 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:311]: So for Android Paper UIManager and how this was set up in v0.59 and earlier for RNW, we just used the managed type system to check if the shadow node was a particular type.

Presumably if we're going to expose core VMs through the ABI, we'll also need to expose shadow node functionality. I'm guessing we don't want to introduce any dynamic_cast / RTTI, so when we take this approach, is there a way for us to add type traits to each shadow node so we can have a non-dynamic cast?

**Review by chiaramooney — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 7 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:311]: we wouldn't use rtti/dynamic_cast since that's not ABI safe, but instead we'd use a WinRT interface you can QueryInterface / `.as<T>()` for

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp]: Added `ShadowNodeTypeUtils.h` to keep this logic in one place.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h (hunk 8 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h:23]: I think the optimization would add too much complexity. It's already complex enough with the optimization to only traverse the text tree when needed.

File: vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp [hunk 9]
```diff
@@ -106,7 +140,13 @@ bool VirtualTextViewManager::UpdateProperty(
...
+    auto node = static_cast<VirtualTextShadowNode *>(nodeToUpdate);
+    if (IsValidOptionalColorValue(propertyValue)) {
+      node->m_foregroundColor = OptionalColorFrom(propertyValue);
+      const auto propertyChangeType =
+          node->m_foregroundColor ? PropertyChangeType::AddBackgroundColor : PropertyChangeType::None;
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:147]: We could potentially split the background color and foreground color props. If a foreground color is set but nothing else has a foreground color, we don't need to recurse through the tree.

Also, since we need this for foreground color as well as background color, we should generalize the PropertyChangeType to call it "Highlight" or something.

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:147]: This still isn't working quite right. Thankfully the E2E tests identify the problem. Will fix.

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp:147]: Need to also set m_hasDescendantBackgroundColor on node as well.

**Comment by NickGerleman** [comment]
@rozele is this ready for merge?

**Comment by rozele** [comment]
@NickGerleman yes.
