### PR TITLE
fix(Text): Prevent crashing from touch/click

### LINKED ISSUE #1622: Touch on RichTextBlock sometimes crashes app.
### Environment

1. `react-native -v`: 0.52.*
2. `npm ls rnpm-plugin-windows`: N/A
3. `npm ls react-native-windows`: master
4. `node -v`: N/A
5. `npm -v`: N/A
6. `yarn --version`: N/A

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): UWP

- Target Device(s): *

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

(Write your steps here:)

1. Open RNTester
2. Open the <Text /> demo
3. In the `Inline views` example, try to click just below one of the inline views.

### Expected Behavior

(Write what you thought would happen.)

The app should not crash.

### Actual Behavior

(Write what happened. Add screenshots!)

The app did crash.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

Follow instructions above in RNTester.

### PR DESCRIPTION
**Pull request by rozele**
Occasionally, if you click the root Span inline of the RichTextBlock rendered for the React Native <Text/> component, the app will not find the "tag" that was targeted, and will crash.

Fixes #1622

### CODE REVIEW

File: ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs [hunk 1]
```diff
@@ -11,7 +11,14 @@ public int GetReactTagAtPoint(UIElement reactView, Point point)
         {
             var richTextBlock = reactView.As<RichTextBlock>();
             var textPointer = richTextBlock.GetPositionFromPoint(point);
-            return textPointer.Parent.GetTag();
+            var textPointerParent = textPointer.Parent;
```
Comment (gmangov) [inline ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs]: Can this be a span or something few levels deep? In such a case textPointer.Parent is not going to be the RichTextBlock but a TextElement, so it it will need recursively walking up. Or it may that textPointer.VisualParent is easier to use?

File: ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs [hunk 2]
```diff
@@ -11,7 +11,14 @@ public int GetReactTagAtPoint(UIElement reactView, Point point)
...
+
+            // We may encounter a case where the parent item is the
+            // `Paragraph` inline attached to the `RichTextBlock`.
+            // In this case, simply return the tag of the `RichTextBlock`.
+            return textPointerParent.HasTag()
```
Comment (gmangov) [inline ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs]: Can this be null?

Comment (rozele) [reply ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs]: Good point - I'll add a null check.

File: ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs (hunk 1 above)
Comment (rozele) [reply ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs]: @gmangov - it's okay for the element to be a few levels deep. If it finds a Span parent, that parent will have been created by the `ReactSpanViewManager`, and as such will have a tag. In fact, the purpose of this `ReactTextCompoundView` is to handle exactly that case so the correct touch handler is invoked for "virtual" text elements.

This is only trying to address the one case where it finds the Paragraph (which is not correlated to the React component, but an implementation detail of using the RichTextBlock).

Comment (rozele) [reply ReactWindows/ReactNative/Views/Text/ReactTextCompoundView.cs]: I updated the comment in the source code to clarify .
