### PR TITLE
Add Workaround for XAML Bug with textDecorationLine

### LINKED ISSUE #6715: textDecorationLine text style persists after setting it to "none"
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 
4.13.0
2. `npx react-native info`: 
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 14.91 GB / 31.91 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17749.0, 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 15.9.28307.1300 (Visual Studio Enterprise 2017), 16.8.30717.126 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: 2.7.15 - C:\Users\jakovs\\.windows-build-tools\python27\python.EXE
  npmPackages:
    @react-native-community/cli: 4.13.0 => 4.13.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: 0.63.6 => 0.63.6
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.18362.0
- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug, Release

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Text component
2. Add `{textDecorationLine: "underline"}` style to the text component (same with `"line-through"` and `"underline line-through"`)
3. Replace style with `{textDecorationLine: "none"}` or remove style from the component altogether
4. Observe that text remains underlined

## Expected Results
When style is removed/replaced it should remove the underline decoration from text element

There is a workaround of wrapping the the above Text in another Text component, which then produces expected result:
```
                <Text>
                    <Text
                        style={this.state.underlined ? styles2.underlined : styles2.notUnderlined}
                        key={this.state.key}>
                        {"Some text"}
                    </Text>
                </Text>
```

## Snack, code example, screenshot, or link to a repository:
Drop this component inside a RNW application:
[https://snack.expo.io/PoDBtyQKi](https://snack.expo.io/PoDBtyQKi)
You may provide a screenshot of the application if you think it is relevant to your bug report.
underline_remains

### PR DESCRIPTION
**Pull request by chiaramooney**
Fix #6715 

**_Why_**
The issue is a bug with the textDecorationLine prop for the Text component where the UI is failing to display the correct styling. When the textDecorationLine prop is set to ‘underline’, an underline appears. But if the prop is then set to ‘none’ or even removed entirely, the underline still persists. This buggy behavior also happens for the other values for this prop, ‘line-through’ and ‘underline-line-through’. Another instance of buggy behavior is when the textDecorationLine prop is initially set to ‘underline’, an underline appears. But if the prop is then set to ‘line-through’, the underline still persists along with the strikethrough.

**_What_**
Turns out buggy behavior in RNW is the result of a bug in XAML, where updates to the textDecorationLine prop are incorrectly marked as not needing rendering when the value is changed. This bug will not be able to be resolved until WinUI3 I believe. Inside the issue there is a link to a XAML issue which details a workaround which can be implemented to resolve the bug. Essentially, following a change in the textDecorationLine prop, the user should change and change back the Text contents of the TextBlock in order to trigger the re-rendering of the component. 

**_How_**
Added workaround code following TryUpdateTextDecorationLine returning true, signaling that the prop has changed in value or been removed. Added comment above workaround noting that this it is one, so the excerpt can be identified later once the bug in XAML is resolved. 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6855)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 1]
```diff
@@ -161,6 +161,12 @@ bool TextViewManager::UpdateProperty(
   } else if (TryUpdateTextAlignment(textBlock, propertyName, propertyValue)) {
   } else if (TryUpdateTextTrimming(textBlock, propertyName, propertyValue)) {
   } else if (TryUpdateTextDecorationLine(textBlock, propertyName, propertyValue)) {
+    // Temporary workaround for bug in XAML which fails to flush old TextDecorationLine render
```
Comment (rectified95) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:164]: Link to the bug issue:
https://github.com/microsoft/microsoft-ui-xaml/issues/1093#issuecomment-514282402

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 2]
```diff
@@ -161,6 +161,12 @@ bool TextViewManager::UpdateProperty(
...
+    std::wstring text(textBlock.Text().c_str());
```
Comment (rectified95) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:165]: if you need to convert to hstring below, you could make the text var a hstring here

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 3]
```diff
@@ -161,6 +161,12 @@ bool TextViewManager::UpdateProperty(
...
+    text.push_back('a');
```
Comment (rectified95) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:166]: nit: setting to an empty string as in the original fix is perhaps slightly cleaner

**Review by rectified95 — CHANGES_REQUESTED** [review]
I'd add a link to the bug you're referencing in the comment and align the fix with what's there. Thanks for bringing this over.

**Review by rectified95 — APPROVED** [review]
LGTM

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 1 above)
Comment (acoates-ms) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:164]: Lets make sure to open an issue in this repo to remove this work around once when xaml bug is fixed.

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 4]
```diff
@@ -161,6 +161,11 @@ bool TextViewManager::UpdateProperty(
   } else if (TryUpdateTextAlignment(textBlock, propertyName, propertyValue)) {
   } else if (TryUpdateTextTrimming(textBlock, propertyName, propertyValue)) {
   } else if (TryUpdateTextDecorationLine(textBlock, propertyName, propertyValue)) {
+    // Temporary workaround for bug in XAML which fails to flush old TextDecorationLine render
+    // Link to Bug: https://github.com/microsoft/microsoft-ui-xaml/issues/1093#issuecomment-514282402
+    winrt::hstring text(textBlock.Text().c_str());
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:166]: I think you can just say `auto text = textBlock.Text();` so that you don't create copies of the string

Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:166]: Ah yes that makes sense. I was following the format of [this line](https://github.com/microsoft/react-native-windows/blob/b01470476fbe07a8fd609ab7c838194671232d9c/vnext/Microsoft.ReactNative/Views/TextViewManager.cpp#L51) in the AddView function, but `auto text = textBlock.Text()` is much cleaner. Want me to create a new PR for this change?
