### PR TITLE
[Fabric] Fix Textinput's caret on focus lost

### LINKED ISSUE #12125: Fabric TexInput caret should remove visibility when focus is lost
### Problem Description

When a textinput loses focus, the caret should be hidden from view. Currently Fabric keeps the caret visible.

### Paper

https://github.com/microsoft/react-native-windows/assets/42554868/1f50aacd-4705-4da3-9969-e6f181c70b13

### Fabric

https://github.com/microsoft/react-native-windows/assets/42554868/b71fd2bc-5afc-4370-af4c-7b4e9a5da785

### Steps To Reproduce

1. Look at playground-composition and click on different TextInputs

### Expected Results

The caret is hidden when focus is lost

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by TatianaKapos**
## Description
Makes TextInput's caret lose visibility when focus is lost.

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
Resolves #12125

### What
Set visibility to false when focus is lost

## Screenshots

https://github.com/microsoft/react-native-windows/assets/42554868/e8734a4c-f131-4977-b0f7-261bed706a7d

## Testing
tested locally

## Changelog
no
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/12157)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp [hunk 1]
```diff
@@ -583,6 +583,7 @@ void WindowsTextInputComponentView::unmountChildComponentView(
 void WindowsTextInputComponentView::onFocusLost() noexcept {
   Super::onFocusLost();
   sendMessage(WM_KILLFOCUS, 0, 0);
+  m_caretVisual.IsVisible(false);
```
Comment (jonthysell) [inline vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp:586]: Does this need to be set to true when focus is gained, or does that happen automatically?

**Review by jonthysell — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp (hunk 1 above)
Comment (acoates-ms) [reply vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp:586]: Does the TextInput not call TxShowCaret(false) when it receives WM_KILLFOCUS?

Comment (TatianaKapos) [reply vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp:586]: Did some digging, TextInput calls TxShowCaret twice when it receives WM_KILLFOCUS, once with TxShowCaret(false) and TxShowCaret(true). The callstack is the same for both calls so not sure why it's being called twice

**Review by acoates-ms — APPROVED** [review]
