### PR TITLE
Fixes bugs for pointerEvents prop

### LINKED ISSUE #8496: Missing behaviors for "pointerEvents" prop
There are a couple issues with `pointerEvents`:
1. `pointerEvents` should be applicable to any RN component that derives from View (e.g., Image, Text, etc.)
2. `pointerEvents` is not implemented for `"box-none"` and `"box-only"`.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

For the former issue, add an example to RNTester like:
```js
  <Text onPress={() => console.log('Pressed')} pointerEvents="none">
    Absolutely not pressable text.
  </Text>
```
If you click on the Text, you should not get a `console.log`, but you still do in the current state of react-native-windows.

For the latter issue of missing implementations for `"box-none"` and `"box-only"`, you can repro from RNTester:
1. Run the Pointer Events example in RNTester
2. Scroll down to the `"box-none"` and `"box-only"` examples, try to click grayed out views that should not respond to events and observe that events still fire.

## Expected Results

Pointer events should work on arbitrary view types that expect View props, and the behaviors for `"box-none"` and `"box-only"` should match iOS and Android.

## Snack, code example, screenshot, or link to a repository:

Here's a video repro of the non-`<View />` `pointerEvents` being ignored:

https://user-images.githubusercontent.com/1106239/131182075-cf8195d1-ca94-4e30-8c4b-c88ae0cf2ba0.mp4

Here's a video repro of the `"box-none"` and `"box-only"` issues:

https://user-images.githubusercontent.com/1106239/131181259-6867ee36-0ee5-42d7-9c54-642f84f0a398.mp4

### PR DESCRIPTION
**Pull request by rozele**
Adds functionality for box-only and box-none via OnPointerEvent callback 

This change checks if the React node has `pointerEvents="box-only"` or `pointerEvents="box-none"` set. If the node is `box-only`, it updates the `ReactPointerEventArgs.Target` view to itself (preventing children from becoming the hit test target for the React pointer event. If the node is `box-none` and the current `ReactPointerEventArgs.Target` value is the current view, it sets the target to `null`, forcing the `TouchEventHandler` to choose an ancestor as the hit target.

https://user-images.githubusercontent.com/1106239/131200698-1bf38123-33ea-49af-8aff-a2f0942d3193.mp4dfs

Fixes #8496

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8500)

### CODE REVIEW

**Comment by rozele** [comment]
Just for fun - here's onMouseEnter / onMouseLeave leveraging the same infrastructure for pointerEvents working as expected:

https://user-images.githubusercontent.com/1106239/131688182-9fdc9c21-a445-4eee-b5f5-75283ec0aa68.mp4

**Comment by rozele** [comment]
Please note - this also fixes #8531, since we explicitly check for `pointerEvents="none"` in case the XAML hit testing fails (or the React element is not a UIElement and does not have the `IsHitTestVisible` property).

File: vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h [hunk 1]
```diff
@@ -128,6 +128,9 @@ struct REACTWINDOWS_EXPORT ShadowNodeBase : public ShadowNode {
   bool m_onMouseEnterRegistered = false;
   bool m_onMouseLeaveRegistered = false;
 
+  // Pointer events
+  std::string m_pointerEvents = "";
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h:132]: nit: Default value is already empty string

```suggestion
  std::string m_pointerEvents;
```

Comment (NickGerleman) [reply vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h:132]: Looking at this further, this would be a bit more efficient to be cached as an enum instead of a string, since we only ever compare it to known values. Consider storing as an enum, then setting accordingly in ViewManagerBase::UpdateProperty. This would also make the ShadowNode a bit smaller, since `std::string` contains a small internal buffer for even empty strings to enable the short string optimization.

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
@msftbot merge in 24 hours
