### PR TITLE
Use auto_revoke in vNext to avoid random crash and remove some winrt namespace and #include headers

### LINKED ISSUE #2524: Introduce auto_revoke to vNext to avoid random crash because different lifecycle of controls and shadow node
This apply to all vNext. It's possible apply to current\ too.
Like TextInputShadowNode, it nexted winrt::TextBox as XamlView. winrt::TextBox is winRT component, so it's possible to be destroyed late after TextInputViewManager.
I see two times of random crashes on TextChanged event but TextInputShadowNode is readonly. It's high probability that we didn't unhook the event in ~TextInputShadowNode, and TextInputShadowNode received callback after it's destroyed.

When we hook up the event, TextChanged returned a token, then the token can be used to unhook the event.

Here is an example how winui avoid this problem by winrt::auto_revoke:
`        m_paneToggleButtonClickRevoker = paneToggleButton.Click(winrt::auto_revoke, { this, &NavigationView::OnPaneToggleButtonClick });`

Here is our example that we didn't follow this pattern and may caused random crash in TextInputShadowNode::createView():
 ```
 textBox.TextChanged([=](auto &&, auto &&)
  {
      if (auto instance = wkinstance.lock())
      {
        m_nativeEventCount++;
        folly::dynamic eventData = folly::dynamic::object("target", tag)("text", HstringToDynamic(textBox.Text()))("eventCount", m_nativeEventCount);
        instance->DispatchEvent(tag, "topTextInputChange", std::move(eventData));
      }
  });
```

### PR DESCRIPTION
**Pull request by licanhua**
Fix #2524
1. Make event to be hooked up with winrt::auto_revoke
2. remove a lot of `namespace winrt` and #include head in .cpp since they are duplicated with what in CppWinRTIncludes.h.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/2746)

### CODE REVIEW

File: vnext/include/CppWinRTIncludes.h [hunk 1]
```diff
@@ -4,22 +4,43 @@
...
+
+#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
+
+#include <winrt/Windows.UI.Xaml.Input.h>
+
+#include <winrt/Windows.UI.Text.h>
+#include <winrt/Windows.UI.Composition.h>
+
 #include <winrt/Windows.UI.Xaml.Hosting.h>
 #include <winrt/Windows.UI.Xaml.h>
```
Comment (marlenecota) [inline vnext/include/CppWinRTIncludes.h]: Alphabetize.

File: vnext/include/CppWinRTIncludes.h [hunk 2]
```diff
@@ -4,22 +4,43 @@
...
+using namespace ::winrt::Windows::UI::Xaml::Controls::Primitives;
+using namespace ::winrt::Windows::UI::Composition;
+
+// using namespace ::winrt::Windows::UI::Xaml::Controls;
+using Control = ::winrt::Windows::UI::Xaml::Controls::Control;
+using ComboBox = ::winrt::Windows::UI::Xaml::Controls::ComboBox;
+using ContentControl = ::winrt::Windows::UI::Xaml::Controls::ContentControl;
+using CheckBox = ::winrt::Windows::UI::Xaml::Controls::CheckBox;
+using ToggleSwitch = ::winrt::Windows::UI::Xaml::Controls::ToggleSwitch;
+}
```
Comment (marlenecota) [inline vnext/include/CppWinRTIncludes.h]: I don't think this should be in a header used by all. I realize it's subjective, but at the very least it is controversial and we should talk about it before adding more to it. It would probably be best for you to split this PR up to unblock the auto_revoke fix.

File: vnext/ReactUWP/Views/CheckboxViewManager.cpp [hunk 3]
```diff
@@ -32,23 +30,28 @@ class CheckBoxShadowNode : public ShadowNodeBase {
...
-    if (!m_updating && instance != nullptr)
-      OnCheckedChanged(*instance, m_tag, true);
-  });
-  checkbox.Unchecked([=](auto &&, auto &&) {
-    auto instance = wkinstance.lock();
-    if (!m_updating && instance != nullptr)
-      OnCheckedChanged(*instance, m_tag, false);
-  });
+  m_checkBoxCheckedRevoker =
+      checkbox.Checked(winrt::auto_revoke, [=](auto &&, auto &&) {
```
Comment (chrisglein) [inline vnext/ReactUWP/Views/CheckboxViewManager.cpp]: Use explicit captures rather than [=]

File: vnext/include/CppWinRTIncludes.h (hunk 2 above)
Comment (chrisglein) [reply vnext/include/CppWinRTIncludes.h]: Agreed it doesn't seem essential to the PR, but I'm guessing it came in because the revoker types + namespaces were long? This does seem to be the pattern that [WinUI uses](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/inc/CppWinRTIncludes.h), but I'm not sure _why_. I'd love to hear more about that and at least have that captured as a comment.

Comment (licanhua) [reply vnext/include/CppWinRTIncludes.h]: Although I think it has a lot of benefits and put them in header, agree to split this PR

Comment (licanhua) [reply vnext/include/CppWinRTIncludes.h]: WinUI use this pattern because it's easy to switch the namespace from Windows::UI::Xaml to Microsoft::UI::Xaml.
We more or less should do it in the same way in RN windows.
We have duplicated using in every cpp like below, and I think it's better to put all in a header file.

#include <winrt/Windows.UI.Xaml.Controls.h>
...

namespace winrt {
using namespace Windows::Foundation;
using namespace Windows::UI;
using namespace Windows::UI::Xaml;
using namespace Windows::UI::Xaml::Controls;
using namespace Windows::UI::Xaml::Controls::Primitives;
using namespace Windows::UI::Xaml::Media;
} // namespace winrt


---
In reply to: [301723713](https://github.com/microsoft/react-native-windows/pull/2746#discussion_r301723713) [](ancestors = 301723713)

Comment (chrisglein) [reply vnext/include/CppWinRTIncludes.h]: Ah. the redirect for MUX versus WUX, that makes sense. A comment in the header here would go a long way towards dispelling any confusion.

File: vnext/ReactUWP/Views/CheckboxViewManager.cpp (hunk 3 above)
Comment (licanhua) [reply vnext/ReactUWP/Views/CheckboxViewManager.cpp]: this is not the only one, I create bug #2748 to tack it

---
In reply to: [301721470](https://github.com/microsoft/react-native-windows/pull/2746#discussion_r301721470) [](ancestors = 301721470)

File: vnext/include/CppWinRTIncludes.h (hunk 2 above)
Comment (licanhua) [reply vnext/include/CppWinRTIncludes.h]: I rollback the header

---
In reply to: [301730122](https://github.com/microsoft/react-native-windows/pull/2746#discussion_r301730122) [](ancestors = 301730122)

File: vnext/include/CppWinRTIncludes.h (hunk 1 above)
Comment (licanhua) [reply vnext/include/CppWinRTIncludes.h]: I rollbacked the change.

---
In reply to: [301440408](https://github.com/microsoft/react-native-windows/pull/2746#discussion_r301440408) [](ancestors = 301440408)

File: vnext/ReactUWP/Views/CheckboxViewManager.cpp (hunk 3 above)
Comment (marlenecota) [reply vnext/ReactUWP/Views/CheckboxViewManager.cpp]: It's good to have a bug to fix all the other [=] already in the code base, but you should fix this new one before checking this in.

File: vnext/ReactUWP/Views/FlyoutViewManager.cpp [hunk 4]
```diff
@@ -132,20 +135,23 @@ void FlyoutShadowNode::createView() {
...
-  });
-
-  m_flyout.Closed([=](auto &&, auto &&) {
-    auto instance = wkinstance.lock();
-    if (!m_updating && instance != nullptr)
-      OnFlyoutClosed(*instance, m_tag, false);
-  });
+  m_flyoutClosingRevoker = m_flyout.Closing(
+      winrt::auto_revoke,
+      [=](winrt::FlyoutBase /*flyoutbase*/,
```
Comment (marlenecota) [inline vnext/ReactUWP/Views/FlyoutViewManager.cpp]: Use explicit capture

File: vnext/ReactUWP/Views/CheckboxViewManager.cpp (hunk 3 above)
Comment (marlenecota) [reply vnext/ReactUWP/Views/CheckboxViewManager.cpp]: Nevermind, it's not new :)

File: vnext/ReactUWP/Views/FlyoutViewManager.cpp (hunk 4 above)
Comment (marlenecota) [reply vnext/ReactUWP/Views/FlyoutViewManager.cpp]: Nevermind, #2748 tracks this work
