### PR TITLE
Deploy apps in CI to catch cli deployment issues

### LINKED ISSUE #5596: sample apps' bundle-cpp fails on new machines
This is because of a bug in the prepareBundle script. The bundler requires the Bundle directory to be created, which prepareBundle is supposed to do, but it only ensures that the parent of the Bundle directory exists

### LINKED ISSUE #5597: Deploying a C# app with a non-default namespace/component fails
We use the assembly name (mynamespace.mycomponent.build.appxrecipe) as the appxrecipe but it's wrong for C# - the uwp project system will create testcli.build.appxrecipe instead. Use the value from the AppxRecipeFile variable instead.

### LINKED ISSUE #5598: Deploying app from layout in the CLI picks the wrong appx manifest if multiple projects in the solution
The sample apps solution has a sampleAppCpp and sampleAppCS. When using the CLI to deploy from layout, we try to find the right appxmanifest to then test that the app got installed successfully but we do so by globbing and getting the first result, which is wrong. We should incorporate the result from parsing react-native.config.js and the --proj switches.

### PR DESCRIPTION
**Pull request by asklar**
This change addresses a few issues:
- Our CI wasn't actually exercising deployment which meant deploying could fail in some cases and we wouldn't know it
- Bundling the sample apps was broken
- Deploying in solutions with multiple projects was unreliable (i.e. it would pick the wrong appxmanifest)
- Deploying a project created with a non-default name for component/namespace was failing for C# projects

Fixes #5596 
Fixes #5597
Fixes #5598

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5587)

### CODE REVIEW

File: vnext/local-cli/src/runWindows/utils/deploy.ts [hunk 1]
```diff
@@ -54,7 +59,16 @@ function getAppPackage(options: RunWindowsOptions): string {
   const appPackageGlob = `${
     options.root
   }/windows/{*/AppPackages,AppPackages/*}/${packageFolder}`;
-  let appPackage = glob.sync(appPackageGlob)[0];
+  const globs = glob.sync(appPackageGlob);
+  let appPackage;
+  if (globs.length == 1 || !projectName) {
```
Comment (NickGerleman) [inline vnext/local-cli/src/runWindows/utils/deploy.ts:64]: '===' instead of '=='. As is will generate eslint warnings (see yarn lint in Extra Checks)

File: vnext/local-cli/src/runWindows/utils/deploy.ts [hunk 2]
```diff
@@ -54,7 +59,16 @@ function getAppPackage(options: RunWindowsOptions): string {
   const appPackageGlob = `${
     options.root
   }/windows/{*/AppPackages,AppPackages/*}/${packageFolder}`;
-  let appPackage = glob.sync(appPackageGlob)[0];
+  const globs = glob.sync(appPackageGlob);
```
Comment (NickGerleman) [inline vnext/local-cli/src/runWindows/utils/deploy.ts:62]: Nit: globs describe the pattern, not the result. Consider something like "appPackageFiles" instead. 

Same below

File: vnext/local-cli/src/runWindows/utils/deploy.ts [hunk 3]
```diff
@@ -54,7 +59,16 @@ function getAppPackage(options: RunWindowsOptions): string {
...
+  let appPackage;
+  if (globs.length == 1 || !projectName) {
+    appPackage = globs[0];
+  } else if (globs.length > 1) {
+    const filteredGlobs = globs.filter(x => x.indexOf(projectName) != -1);
```
Comment (NickGerleman) [inline vnext/local-cli/src/runWindows/utils/deploy.ts:67]: Nit: Use the "includes" function instead of comparing indexof to -1. Same below. 

Same comment above about terminology, where globs describe the pattern, which isn't quite accurate for the variable name here.

File: vnext/local-cli/src/runWindows/utils/deploy.ts [hunk 4]
```diff
@@ -189,12 +224,21 @@ export async function deployToDevice(
 export async function deployToDesktop(
   options: RunWindowsOptions,
   verbose: boolean,
-  slnFile: string,
+  config: Config,
   buildTools: MSBuildTools,
 ) {
-  const appPackageFolder = getAppPackage(options);
+  const windowsConfig: WindowsProjectConfig = config.project.windows;
```
Comment (NickGerleman) [inline vnext/local-cli/src/runWindows/utils/deploy.ts:230]: As is, this type expresses windowsConfig to always be defined, and always have all properties. We later do check these cases, so I'm not sure this type expresses what we want it to. 

Looking at projectConfigWindows, the return type is  "WindowsProjectConfig | null". It seems like that's the right type here, and that we should be able to avoid null checking properties since WindowsProjectConfig doesn't allow them to be null or undefined. 

If we did want to express that windowsConfig can be undefined and that it's properties may be undefined, you could use a type like "Partial\<WindowsProjectConfig\> | undefined". I'm not sure that's correct though. 

Adding this extra information lets the typescript compiler enforce null/undefined checks correctly.

File: vnext/local-cli/src/runWindows/utils/deploy.ts (hunk 1 above)
Comment (NickGerleman) [reply vnext/local-cli/src/runWindows/utils/deploy.ts:64]: This will also show up as a yellow squiggly if you have eslint configured in vs code. Would highly recommend you do that if you haven't.

Comment (asklar) [reply vnext/local-cli/src/runWindows/utils/deploy.ts:64]: @NickGerleman I do have it configured, and it looks like it was showing up, but it's too easy to miss, esp on something as short as "==" :-(

File: vnext/local-cli/src/runWindows/utils/deploy.ts (hunk 4 above)
Comment (asklar) [reply vnext/local-cli/src/runWindows/utils/deploy.ts]: thanks, will try this
