### PR TITLE
Fix announceForAccessibility

### LINKED ISSUE #5908: AccessibilityInfo::announceForAccessibility fails to announce
The code to attempt to get an automation peer for the current window calls `FrameworkElementAutomationPeer::FromElement` on an element, but it always returns null.

We should work out how to successfully get a peer from XAML.

(This code will be checked in with #5849)

### PR DESCRIPTION
**Pull request by chiaramooney**
Resolve #5908 

**_Why_**
announceForAccessibility method in the AccessibilityInfo module failed to announce messages.

**_What_**
The API for the method does not include a reference to a RN component as a parameter but Windows requires an element to announce from. The previous implementation tried to pass in Xaml::Window::Content into FrameworkElementAutomationPeer::FromElement to create an automation peer, but this approach always resulted in the peer being null and no announcement could be made. 

Altered the code such that a Xaml Control (TextBlock) is passed into FrameworkElementAutomationPeer::FromElement instead. This caused the peer returned to be non-null and the announcement could be fired.

**_Testing_**
Created an RNW app and altered Microsoft.ReactNative inside of tester app with the changes to AccessibilityInfo. Was able to hear announcement when announceForAccessibility was called.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7220)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp [hunk 1]
```diff
@@ -41,27 +41,17 @@ void AccessibilityInfo::setAccessibilityFocus(double /*reactTag*/) noexcept {
...
-      element = window.Content();
-    }
-
-    if (!element && react::uwp::Is19H1OrHigher()) {
-      // XamlRoot added in 19H1
-      if (auto xamlRoot = React::XamlUIService::GetXamlRoot(context.Properties().Handle())) {
-        element = xamlRoot.Content();
-      }
-    }
+    auto textBlock = xaml::Controls::TextBlock();
```
Comment (rectified95) [inline vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp:48]: nit: seems like a UIElement might be enough - https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.peers.frameworkelementautomationpeer.fromelement?view=winrt-19041
Would be a little cheaper to create - can you try that?

**Review by rectified95 — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp (hunk 1 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp:48]: you can't instantiate UIElement directly, only subclasses

Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp:48]: Should I leave it as is? Or is there a cheaper subclass I should instantiate instead?

Comment (rectified95) [reply vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp:47]: I think it might work with a Control

Comment (chiaramooney) [reply vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp:47]: Ok looks like Control also can't be instantiated directly only its subclasses.
