### PR TITLE
Prevent hard crash on invalid jsx (button inside text e.g.)

### LINKED ISSUE #4918: Hard crash on invalid jsx
```jsx
<Text>
  <Button title="foo">
</Text>
```

This hard crashes the app without much info (we just call `std::terminate()` or `abort`)

We should a) in Debug, show redbox, b) in Release, throw some sort of exception or show something to the user.

```txt
 # ChildEBP RetAddr  
00 14f7c108 20c4fff1 ucrtbased!issue_debug_notification+0x30 [minkernel\crts\ucrt\src\appcrt\internal\report_runtime_error.cpp @ 28] 
01 14f7c120 20c612ca ucrtbased!__acrt_report_runtime_error+0x11 [minkernel\crts\ucrt\src\appcrt\internal\report_runtime_error.cpp @ 154] 
02 14f7c130 20c6076d ucrtbased!abort+0x1a [minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 51] 
03 14f7c168 2001b4bb ucrtbased!terminate+0x7d [minkernel\crts\ucrt\src\appcrt\misc\terminate.cpp @ 59] 
04 14f7e538 20012e18 Microsoft_ReactNative_1ef70000!<lambda_c6a00e8fc4e144d0d409f704aff8229f>::operator()+0x28b [C:\rnw\vnext\build\x86\Debug\ReactCommon\react-native-patched\ReactCommon\cxxreact\CxxNativeModule.cpp @ 157] 
05 14f7e60c 20017b07 Microsoft_ReactNative_1ef70000!std::_Invoker_functor::_Call<<lambda_c6a00e8fc4e144d0d409f704aff8229f> &>+0x38 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\type_traits @ 1610] 
06 14f7e6e4 20012e87 Microsoft_ReactNative_1ef70000!std::invoke<<lambda_c6a00e8fc4e144d0d409f704aff8229f> &>+0x37 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\type_traits @ 1610] 
07 14f7e7bc 2001c309 Microsoft_ReactNative_1ef70000!std::_Invoker_ret<void,1>::_Call<<lambda_c6a00e8fc4e144d0d409f704aff8229f> &>+0x37 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\type_traits @ 1629] 
08 14f7e8a0 1f6f327b Microsoft_ReactNative_1ef70000!std::_Func_impl_no_alloc<<lambda_c6a00e8fc4e144d0d409f704aff8229f>,void>::_Do_call+0x39 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\functional @ 927] 
09 14f7e98c 1ff19e1e Microsoft_ReactNative_1ef70000!std::_Func_class<void>::operator()+0x5b [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\functional @ 976] 
0a 14f7eaac 1ff18487 Microsoft_ReactNative_1ef70000!<lambda_6beef76cb8fc8595e4995085bda7e2c2>::operator()+0x8e [C:\rnw\vnext\Microsoft.ReactNative\Threading\BatchingQueueThread.cpp @ 53] 
0b 14f7eb90 1ff18d06 Microsoft_ReactNative_1ef70000!std::_Invoker_functor::_Call<<lambda_6beef76cb8fc8595e4995085bda7e2c2> &>+0x57 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\type_traits @ 1610] 
0c 14f7ec78 1ff18507 Microsoft_ReactNative_1ef70000!std::invoke<<lambda_6beef76cb8fc8595e4995085bda7e2c2> &>+0x56 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\type_traits @ 1610] 
0d 14f7ed50 1ff1a729 Microsoft_ReactNative_1ef70000!std::_Invoker_ret<void,1>::_Call<<lambda_6beef76cb8fc8595e4995085bda7e2c2> &>+0x37 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\type_traits @ 1629] 
0e 14f7ee34 1f6f327b Microsoft_ReactNative_1ef70000!std::_Func_impl_no_alloc<<lambda_6beef76cb8fc8595e4995085bda7e2c2>,void>::_Do_call+0x39 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\functional @ 927] 
0f 14f7ef20 1ff1e6bf Microsoft_ReactNative_1ef70000!std::_Func_class<void>::operator()+0x5b [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\functional @ 976] 
10 14f7f054 1ff1d535 Microsoft_ReactNative_1ef70000!Mso::React::MessageDispatchQueue::tryFunc+0x5f [C:\rnw\vnext\Microsoft.ReactNative\Threading\MessageDispatchQueue.cpp @ 41] 
11 14f7f14c 1ff1dd67 Microsoft_ReactNative_1ef70000!<lambda_a0fdbc83580e7984224b8dad653dd9aa>::operator()+0x85 [C:\rnw\vnext\Microsoft.ReactNative\Threading\MessageDispatchQueue.cpp @ 36] 
12 14f7f23c 1f72e64c Microsoft_ReactNative_1ef70000!Mso::Details::FunctionObjectWrapper<<lambda_a0fdbc83580e7984224b8dad653dd9aa>,void>::Invoke+0x57 [C:\rnw\vnext\Mso\functional\functor.h @ 166] 
13 14f7f390 1f747e36 Microsoft_ReactNative_1ef70000!Mso::QueueService::InvokeTask+0xac [C:\rnw\vnext\Mso\src\dispatchQueue\queueService.cpp @ 208] 
14 14f7f50c 5ccf3f98 Microsoft_ReactNative_1ef70000!Mso::TaskDispatcherHandler::Invoke+0x126 [C:\rnw\vnext\Mso\src\dispatchQueue\uiScheduler_winrt.cpp @ 111] 
```

### PR DESCRIPTION
**Pull request by asklar**
Fixes #4918 

If the jsx is not valid we may end up trying to add something that isn't a UIElement (but a DependencyObject, like a Span) to an items Children collection, which will cause a E_NOINTERFACE exception. This is eventually caught by facebook's code and they `std::terminate()` / `abort()`.

Instead, skip adding the node and show a yellowbox and appropriate debug output.

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4921)

### CODE REVIEW

File: vnext/ReactWindowsCore/Modules/UIManagerModule.cpp [hunk 1]
```diff
@@ -271,11 +273,18 @@ void UIManager::setChildren(int64_t viewTag, folly::dynamic &&childrenTags) {
...
+    try {
+      if (!parent.m_zombie)
+        parent.AddView(childNode, index);
+
+      m_nativeUIManager->AddView(parent, childNode, index);
+    } catch (const winrt::hresult_error &e) {
+      if (e.code() == E_NOINTERFACE) {
+        DEBUG_HRESULT_ERROR(e);
+      } else {
+        throw;
```
Comment (kaiguo) [inline vnext/ReactWindowsCore/Modules/UIManagerModule.cpp:285]: Should this be `winrt::throw_hresult(e)`? Or does `throw` automatically does that?

Comment (asklar) [reply vnext/ReactWindowsCore/Modules/UIManagerModule.cpp:285]: `winrt::throw_hresult` takes an `HRESULT` (i.e. an integer) and constructs an instance of `winrt::hresult_error` and throws it (with the stack starting at that point). 
The `throw` keyword rethrows the exception that was caught in the current `catch` block with the existing stack.
