### PR TITLE
Yarn workaround

### LINKED ISSUE #5985: Single-proc build breaks with npm_config_cache already defined
yarn sets up some environment variables (like npm_config_cache) and calls execSync. This calls the Win32 API CreateProcess and passes an environment block which is a merge of the existing environment block (i.e. from the calling process) with some additional stuff that includes npm_config_cache among others.

Environment variables in Windows are case-insensitive, but CreateProcess does not sanitize the environment block. This is a problem because if the calling process had set up NPM_CONFIG_CACHE (all caps), then yarn will just set the lowercase variant of the variable, and node will call CreateProcess which will contain the variable twice.
This breaks some tools that create dictionaries out of the environment block because they expect to run into each variable exactly once (regardless of casing).

`run-windows` is invoked via yarn, and it calls msbuild which crashes when trying to set up options for the compiler when it finds this option twice. We run into this when building in our CI in Azure DevOps pipeline, which sets up NPM_CONFIG_CACHE in the environment.

Related:

actions/virtual-environments#1566
dotnet/msbuild#5726
nodejs/node#35129
dotnet/runtime#42029
https://developercommunity.visualstudio.com/content/problem/1179475/multitooltask-should-sanitize-environment-variable.html
https://github.com/yarnpkg/yarn/issues/8334

### PR DESCRIPTION
**Pull request by asklar**
Fixes #5985 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/5986)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/runWindows.ts [hunk 1]
```diff
@@ -42,6 +42,15 @@ async function runWindows(
     newInfo('Verbose: ON');
   }
 
+  // https://github.com/yarnpkg/yarn/issues/8334 - Yarn on Windows breaks apps that read from the environment variables
+  // Yarn will run node via CreateProcess and pass npm_config_* variables in lowercase without unifying their value
+  // with their possibly existing uppercase counterparts. This breaks programs that read from the environment block
+  // and write to a case-insensitive dictionary since they expect to encounter each variable only once.
+  // The values of the lowercase variables are the one npm actually wants to use, plus they are seeded from the
+  // uppercase variable values one if there are no overrides.
+  delete process.env.NPM_CONFIG_CACHE;
```
Comment (dannyvv) [inline packages/@react-native-windows/cli/src/runWindows/runWindows.ts:51]: shouldn't these be transposed to lowercase if present? I have always set the uppercase versions on my devbox and they seem to be picked up...

**Review by dannyvv — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/runWindows.ts (hunk 1 above)
Comment (asklar) [reply packages/@react-native-windows/cli/src/runWindows/runWindows.ts:51]: yarn will resolve the right value and put it in npm_config_cache (lowercase) but it doesn't clean up the non-all-lowercase versions.
