### PR TITLE
Re-enable most Desktop integration tests

### LINKED ISSUE #13897: Reenable RNTesterIntegrationTests
### Problem Description

Recent integration failed RNTesterIntegrationTests, currently commented these tests out:

```
(FullyQualifiedName!=RNTesterIntegrationTests::Dummy)&
(FullyQualifiedName!=RNTesterIntegrationTests::Fetch)&
(FullyQualifiedName!=RNTesterIntegrationTests::XHRSample)&
(FullyQualifiedName!=RNTesterIntegrationTests::Blob)&
(FullyQualifiedName!=RNTesterIntegrationTests::Logging)
```

### Link to the integration where the error originated

https://github.com/microsoft/react-native-windows/pull/13685

### PR DESCRIPTION
**Pull request by JunielKatarn**
## Description

Re-enable integration tests excluded from CI during the upgrade to React Native 0.76.

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
The disabled tests are required for proper validation of `react-native-win32.dll`.

Resolves #13897

### What
- Switch desktop integration tests' JS engine to V8.
- Re-enable the following tests in CI:
  ```
  (FullyQualifiedName!=RNTesterIntegrationTests::Dummy)&
  (FullyQualifiedName!=RNTesterIntegrationTests::Fetch)&
  (FullyQualifiedName!=RNTesterIntegrationTests::XHRSample)&
  (FullyQualifiedName!=RNTesterIntegrationTests::Blob)&
  (FullyQualifiedName!=RNTesterIntegrationTests::Logging)
  ```

## Testing
Ran the referred set of tests locally. All of them succed.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/14147)

### CODE REVIEW

**Review by TatianaKapos — APPROVED** [review]

File: vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp [hunk 1]
```diff
@@ -72,7 +72,7 @@ shared_ptr<ITestInstance> TestRunner::GetInstance(
   devSettings->platformName = "windows";
 
   // Set to JSIEngineOverride::Chakra when testing the Chakra.dll JSI runtime.
```
Comment (TatianaKapos) [inline vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp:74]: nit: should this comment still say Chakra?

Comment (JunielKatarn) [reply vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp:74]: Probably no.

**Review by TatianaKapos — APPROVED** [review]
