### PR TITLE
Fix Deploy Error for Apps that Contain Spaces in Path

### LINKED ISSUE #10001: CLI fails when project lives in a path that contains spaces
image
I got this error , any give me a solution.

_Originally posted by @IndrakumarR in https://github.com/microsoft/react-native-windows/issues/3263#issuecomment-1137320523_

### PR DESCRIPTION
**Pull request by chiaramooney**
### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
Apps that contain spaces in their path fail to deploy after running `npx react-native run-windows`. Path name incorrectly sent to Powershell, as space has not been escaped correctly.

Resolves #10001

## Testing
Validated in a stand alone app. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10402)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts [hunk 1]
```diff
@@ -181,7 +181,7 @@ function getWindowsStoreAppUtils(options: RunWindowsOptions) {
     'WindowsStoreAppUtils.ps1',
   );
   execSync(
-    `${powershell} -NoProfile Unblock-File "${windowsStoreAppUtilsPath}"`,
+    `${powershell} -NoProfile Unblock-File "'${windowsStoreAppUtilsPath}'"`,
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts:184]: the double quotes that already exist should have addressed this, do you know why they don't? do we need both the double and single quote or would the single quote work by itself?

Comment (chiaramooney) [reply packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts]: From my reading, the double quotes alone works to escape spaces when using `cd`, but when you are running a powershell script, wrapping the script path in double quotes is a correct syntax, but it will not escape spaces. If you want to escape spaces you need to have single quotes. Looks like just single quotes also works here; the double quotes don't affect behavior either way.

**Review by chrisglein — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]
