### PR TITLE
Auto-detect RTL locale and apply to root view

### LINKED ISSUE #4670: RN top-level window is laid out LTR in RTL locales
The basic problem here is:  If I deploy an RN app in an RTL locale (eg Hebrew), the app will be laid out LTR, and the min/max/close buttons are on the right-hand side instead of the left-hand side.

We should provide an easy way for apps to be deployed in RTL locales that are RTL-aware at the top level.

The work for automatically applying RTL layout to the RN tree is more well-understood.  When we run layout, we start with the root react-native node, and for this node we pass a flow direction into yoga, currently we always pass in LTR, which explains why at the app-level the content is always LTR.  

There is actually a TODO in this code with a reference to an internal Office bug number:
https://github.com/microsoft/react-native-windows/blob/b35cc97adef395d7b9886425ef3b12ccd5cec6ee/vnext/ReactUWP/Modules/NativeUIManager.cpp#L857

    // TODO: Real direction (VSO 1697992: RTL Layout)
    YGNodeCalculateLayout(rootNode, actualWidth, actualHeight, YGDirectionLTR);

The app could set the direction property on their top-most RN component but we should consider doing this automatically.  There is an i18Manager.isRTL API which returns true if the app is running in an RTL locale.  We could use this information to determine the layout direction for the root node of the RN tree. 

I'm not clear on what you have to do to get the min/max/close buttons to flip to the other side of the window, this needs some research.

In addition we may need an API for apps to gain explicit control over this behavior.  Some apps may want to always look LTR even in RTL locales.

### LINKED ISSUE #4676: Implement i18nManager.forceRTL
This was discovered when testing the RTLExample page in RNTester.

Near the top of the page there's a button that calls the i18nManager.forceRTL API, which is supposed to force RTL regardless of what locale the app is running in.

react-native-windows doesn't implement this API so this functionality doesn't work.

This issue is tracking adding an implementation for this API.

### LINKED ISSUE #4684: Implement i18nManager.allowRTL
See:
https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps

Relevant section:

-----------------------------
Making an App RTL-ready
To support RTL, you should first add the RTL language bundles to your app.

See the general guides from iOS and Android.
Allow RTL layout for your app by calling the allowRTL() function at the beginning of native code. We provided this utility to only apply to an RTL layout when your app is ready. Here is an example:

iOS:

// in AppDelegate.m
     [[RCTI18nUtil sharedInstance] allowRTL:YES];
Android:

// in MainActivity.java
     I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
     sharedI18nUtilInstance.allowRTL(context, true);
For Android, you need add android:supportsRtl="true" to the <application> element in AndroidManifest.xml file.

Now, when you recompile your app and change the device language to an RTL language (e.g. Arabic or Hebrew), your app layout should change to RTL automatically.

----------------------------------------

### PR DESCRIPTION
**Pull request by kmelmon**
Fixes #4684 
Fixes #4676 
Fixes #4670 

This change adds support for auto-detecting we're in an RTL locale, and flipping the FlowDirection on root view(s) to RightToLeft.  It also adds support for two i18nManager APIs:
forceRTL:  Used for testing, forces the framework into RTL mode even on LTR locales
allowRTL:  When set true, the auto-detection logic runs and flips the root into RTL in RTL locales.  The default value is true, same as the other platforms.

Note that if you toggle the primary language, you must restart the app for changes to be applied.  This is consistent with other platforms.

Tested this change out in the RTLExample page in RNTester which has a control to toggle forceRTL.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4732)

### CODE REVIEW

File: vnext/ReactUWP/Modules/I18nModule.cpp [hunk 1]
```diff
@@ -30,14 +30,55 @@ namespace uwp {
...
+    // Used for debugging purposes, forces RTL even in LTR locales
+    return true;
+  }
+
+  // If the app allows RTL (default is true), then we are in RTL if the locale is RTL
+  return m_allowRTL && m_i18nInfo.second;
+}
+
+void I18nHelper::setAllowRTL(bool allowRTL) {
+  m_allowRTL = allowRTL;
```
Comment (NickGerleman) [inline vnext/ReactUWP/Modules/I18nModule.cpp:77]: Are we okay with this as a global setting instead of per instance? Wondering why we moved to a singleton.

Comment (kmelmon) [reply vnext/ReactUWP/Modules/I18nModule.cpp:77]: The singleton is there for simplicity - this way we don't need to share the I18nModule with the UIManagerModule, which would be awkward.  The information in the singleton is per application instance anyway, so simpler seems better to me.

File: vnext/ReactUWP/Modules/NativeUIManager.cpp [hunk 2]
```diff
@@ -187,6 +188,11 @@ void NativeUIManager::AddRootView(
   XamlView view = xamlRootView->GetXamlView();
   m_tagsToXamlReactControl.emplace(shadowNode.m_tag, xamlRootView->GetXamlReactControl());
 
+  // Push the appropriate FlowDirection into the root view.
+  auto flow = I18nHelper::Instance().getIsRTL() ? winrt::FlowDirection::RightToLeft : winrt::FlowDirection::LeftToRight;
+  view.as<winrt::FrameworkElement>().FlowDirection(
+      I18nHelper::Instance().getIsRTL() ? winrt::FlowDirection::RightToLeft : winrt::FlowDirection::LeftToRight);
```
Comment (asklar) [inline vnext/ReactUWP/Modules/NativeUIManager.cpp:194]: can you please use the updated namespaces? (xaml::FrameworkElement, etc.)

Comment (kmelmon) [reply vnext/ReactUWP/Modules/NativeUIManager.cpp]: done

---
In reply to: [416489965](https://github.com/microsoft/react-native-windows/pull/4732#discussion_r416489965) [](ancestors = 416489965)

File: vnext/ReactUWP/Modules/I18nModule.h [hunk 3]
```diff
@@ -10,19 +10,42 @@
...
+  void setForceRTL(bool forceRTL) override;
 
  private:
-  I18nInfo m_i18nInfo;
+  I18nHelper &m_helper;
 };
+
+class I18nHelper {
+ public:
+  static I18nHelper &Instance();
```
Comment (vmoroz) [inline vnext/ReactUWP/Modules/I18nModule.h:34]: >) [](start = 30, length = 1)

Please consider to add noexcept to methods and constructors to keep binary code smaller.

File: vnext/ReactUWP/Modules/I18nModule.h [hunk 4]
```diff
@@ -10,19 +10,42 @@
...
+
+  I18nHelper();
+
+  void setInfo(I18nModule::I18nInfo &&i18nInfo);
+  std::string getLocaleIdentifier();
```
Comment (vmoroz) [inline vnext/ReactUWP/Modules/I18nModule.h:39]: >) [](start = 34, length = 1)

Can it be const?

File: vnext/ReactUWP/Modules/I18nModule.h [hunk 5]
```diff
@@ -10,19 +10,42 @@
...
+  bool getIsRTL();
+  void setAllowRTL(bool allowRTL);
+  void setForceRTL(bool forceRTL);
+
+ private:
+  I18nModule::I18nInfo m_i18nInfo;
+  bool m_allowRTL = true;
```
Comment (vmoroz) [inline vnext/ReactUWP/Modules/I18nModule.h:46]: > = true [](start = 17, length = 7)

The latest 'fashion' is to use the universal initializers: 
bool m_allowRTL{true};

E.g. the std::atomic fails to initialize otherwise in Clang.
