### PR TITLE
Fix first launch and reload/unload crash

### LINKED ISSUE #2311: Fix the crashes on first-run
There are 2 crashes that consistently occur on first-run:
1. If chrome is not launched prior to the app launched, then there is C++ exception and the app crashes
2. On second try, the bundler/packager doesn't consistently package the RN JS file and hence the app does not refresh with the UI. Once I close the app and run it again, everything just works.

We need to fix both these issues so that developers can reliably launch the app on first-run by running the `react-native run windows` command.

### PR DESCRIPTION
**Pull request by licanhua**
Fix #2311

- Fix the first launch issue because chrome is not launched prior to the app launched.

It takes some time to launch chrome, and so PrepareJavaScriptRuntime may fail. Instead of making the Executor instance to State::Running, we should raise failure.
Otherwise because JavaScript runtime is not initialized, we get blank page, and also returned nothing even if we tried to reload the page. Here is the sample output because of chrome is not launched.
image

- Increase retry count in PrepareJavaScriptRuntime. now it's about 5s to timeout.

- This also fix the reload/unload random crash.

When we unload the instance, ReactControl is destroyed, but we may still receive events because we queued message with [this], but reactInstance and ReactControl have difference lifetime.
Make ReactControl derives from enable_shared_from_this

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/Microsoft/react-native-windows/pull/2373)

### CODE REVIEW

File: RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp [hunk 1]
```diff
@@ -213,12 +213,17 @@ winrt::Windows::Foundation::IAsyncAction WebSocketJSExecutor::ConnectAsync(const
...
-  PrepareJavaScriptRuntime();
-
-  SetState(State::Running);
+  if (PrepareJavaScriptRuntime())
+  {
+    SetState(State::Running);
+  }
+  else
+  {
+    OnHitError("Create a new JS runtime timeout and Executor instance is not connected to a WebSocket endpoint.");
```
Comment (ahimberg) [inline RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp]: Can we make this string a bit more readable for when it shows up in the redbox?  slight adjustment of maybe:
Prepare JS runtime timed out, Executor instance is not connected to a WebSocket endpoint.

File: RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp [hunk 2]
```diff
@@ -213,12 +213,17 @@ winrt::Windows::Foundation::IAsyncAction WebSocketJSExecutor::ConnectAsync(const
...
+  }
 }
 
-void WebSocketJSExecutor::PrepareJavaScriptRuntime()
+bool WebSocketJSExecutor::PrepareJavaScriptRuntime()
 {
   auto timeout = std::chrono::milliseconds(250);
```
Comment (ahimberg) [inline RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp]: Should we bump to the retry count a little bit too?  I haven't seen this error so maybe my machine is fast enough for retries.  I do get errors when chrome wasn't running at all and it booted for debugging - but it launches to an error state that the JS will never be able to connect to

File: RNWCPP/ReactUWP/Views/ReactControl.cpp [hunk 3]
```diff
@@ -101,9 +110,13 @@ void ReactControl::AttachRoot() noexcept
   // Register callback from instance for live reload
   m_liveReloadCallbackCookie = m_reactInstance->RegisterLiveReloadCallback([this]()
   {
-    m_reactInstance->DefaultNativeMessageQueueThread()->runOnQueue([this]()
+    auto weakThis = m_weakThis.This();
```
Comment (ahimberg) [inline RNWCPP/ReactUWP/Views/ReactControl.cpp]: If we're going to have this new shareptr wrapper thing in a mainline path, should reactcontrol be used as a sharedptr instead of unique_ptr?  then we can shared_from_this instead?

Comment (licanhua) [reply RNWCPP/ReactUWP/Views/ReactControl.cpp]: no. It doesn't matter if ReactControl is shared or unique_ptr.
I played tricky to workaround the problem: the actual shared data is 'This' other than ReactControl.
At the beginning, This point to ReactControl, When ReactControl is destroyed, ThisHelper is destroyed first, and This is pointing to null. But This may still exist, and it point to null.

We have this layout:
ReactRootView
 ReactControl
   ThisHelper 
        shared_ptr<This>
            This -> this, and null if ThisHelper is destroyed.

From the implementation, the actual weak_ptr is 'This' other than this(or ReactControl), but customer can think it's the same, because I provide StrongThis function to deduce 'this' from This.

I was tried to make shared_ptr<ReactControl>, it makes me that I need to ReactControl knows about ReactRootView because ReactControl doesn't have the ability to make a weak_ptr.

File: RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp (hunk 1 above)
Comment (licanhua) [reply RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp]:
```suggestion
    OnHitError("Prepare JS runtime timed out, Executor instance is not connected to a WebSocket endpoint.");
```

**Comment by licanhua** [comment]
> Not sure I'm a fan of ThisHelper, where is that from?
I made it. I workaround the problem by create a new shared data This.
Then actual shared_ptr and weak_ptr is This, so we don't need to care if 'this'(or ReactControl) is shared_ptr or unique_ptr.
When processing the queue message, tried to get This from weak_ptr, then get actual 'this'.
When ThisHelper is destroyed, This may still exists, but This is pointing to null

File: RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp (hunk 2 above)
Comment (licanhua) [reply RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp]: 3*250ms is enough of non debugging setup. I don't know if I need to increase the retry count to support debugging.

**Comment by kmelmon** [comment]
I tend to agree with Andy on this one.  The wrappers are confusing to me, and are only obfuscating the important details of when a strong/weak ref is being taken.  I think it would be clearer if you we standardized on using shared_ptr and weak_ptr directly in our codebase.

---
In reply to: [488155028](https://github.com/Microsoft/react-native-windows/pull/2373#issuecomment-488155028) [](ancestors = 488155028)

File: RNWCPP/ReactUWP/Views/ReactControl.h [hunk 4]
```diff
@@ -72,6 +74,7 @@ class ReactControl
 
   winrt::Grid m_redBoxGrid { nullptr };
   winrt::TextBlock m_errorTextBlock { nullptr };
+  WeakThis<ReactControl> m_weakThis{ this };
```
Comment (kmelmon) [inline RNWCPP/ReactUWP/Views/ReactControl.h]: >WeakThis<ReactControl> m_weakThis{ this }; [](start = 2, length = 42)

This is confusing me.  It looks like this actually takes a strong reference on this in the constructor, not a weak reference.
This appears to create a cyclic reference and I don't ever see the cycle broken.  Isn't this causing ReactControl to leak?

Comment (licanhua) [reply RNWCPP/ReactUWP/Views/ReactControl.h]: Look like WeakThis and m_weakThis is not a good name for it.
I rename it to ThisWrapper and m_thisWrapper.
It's not a strong reference/weak reference to this, but just a wrapper of this to help to get weak_ref of This and resolve it to This, then resolve to this.
more details see ThisWrapper.h

**Comment by licanhua** [comment]
> I tend to agree with Andy on this one. The wrappers are confusing to me, and are obfuscating the important details of when a strong/weak ref is being taken. I think it would be clearer if we standardized on using shared_ptr and weak_ptr directly in our codebase.
> 
> In reply to: [488155028](https://github.com/Microsoft/react-native-windows/pull/2373#issuecomment-488155028) [](ancestors = 488155028)

Agree strong and weak terms confuse the user. I rename the terms to ThisWrapper/This/WeakThis and FromWeakThis. 
I still think a wrapper may be better over a new standardized process without a wrapper. And it's very easy to use without any need to care about shared_ptr/unique_ptr of 'this' and parent/child relationship.
Here is another possible implementation, and to resolve this issue, I need to have a shared_ptr<ReactControl>. so its parent ReactRootView would have a shared ReactControl.
To queue with weak_ptr<ReactControl>, ReactRootView should pass a strong/weak ref of ReactControl to ReactControl, so we may have a reverse relationship from ReactControl to ReactRootView.

File: RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp (hunk 2 above)
Comment (licanhua) [reply RNWCPP/ReactUWP/Executors/WebSocketJSExecutorUwp.cpp]: I increase retry count and timeout would be from 750ms to 5s

**Comment by kmelmon** [comment]
Still not a fan of the wrapper.  Closely related:  The lifetime of ReactControl is no longer very straightforward...  The shared_ptr inside ThisWrapper is managing a separate ref count and doesn't actually control the lifetime of ReactControl, because ReactControl was created with the new operator and stored in a unique_ptr.   Finally, your solution requires creating an instance of a ThisWrapper and storing it as a member.  Although all this works, it feels fragile and not as clean as it could be.
I suggest doing the following:
1) Make ReactControl derive from enable_shared_from_this and change ReactRootView to create ReactControl as a shared_ptr.  This will make the lifetime much clearer as ReactControl will have the one and only ref count for the object.
2) Now you should be able to create a weak_ptr from this and capture the weak pointer.
3) ThisWrapper should no longer be necessary and can be deleted.


---
In reply to: [488205059](https://github.com/Microsoft/react-native-windows/pull/2373#issuecomment-488205059) [](ancestors = 488205059)

**Comment by licanhua** [comment]
Agreed. I don't know  enable_shared_from_this is in std library.

---
In reply to: [488499674](https://github.com/Microsoft/react-native-windows/pull/2373#issuecomment-488499674) [](ancestors = 488499674,488205059)

**Comment by kmelmon** [comment]
Version 7 looks great thanks!

---
In reply to: [488513101](https://github.com/Microsoft/react-native-windows/pull/2373#issuecomment-488513101) [](ancestors = 488513101,488499674,488205059)

File: RNWCPP/include/ReactUWP/ReactRootView.h [hunk 5]
```diff
@@ -38,7 +38,7 @@ class ReactRootView : public IXamlRootView
   virtual void SetTag(int64_t tag) override;
 
 private:
-  std::unique_ptr<ReactControl> m_pimpl;
+  std::shared_ptr<ReactControl> m_pimpl;
```
Comment (ahimberg) [inline RNWCPP/include/ReactUWP/ReactRootView.h]: I think you also need to update m_pInnerControl to be stored & created as shared_ptr  in ReactControl_rt.* for the winrt control (tested via the C# app)

Comment (licanhua) [reply RNWCPP/include/ReactUWP/ReactRootView.h]: good catch
