### PR TITLE
Fabric platform color

### LINKED ISSUE #11456: Fabric Button does not render anything (due to lack of PlatformColor)
### Problem Description

`Button` relies on `PlatformColor`, which isn't specified in Fabric like it is on Paper with named colors (which on Paper map to XAML brushes).

I could see this being fixed by:
A) Modifying `Libraries\Components\Button.windows.js` to not use `PlatformColor` and specify hardcoded colors
(note that this would break light/dark/high-contrast mode for the `Button` component)
B) Modify `Microsoft.ReactNative\Fabric\platform\react\renderer\graphics\Color.cpp` to implement `AsWindowsColor()` with a look up of appropriate colors.

This notion of "appropriate colors" is interesting though, because... what are the right colors?

In order to get `Button` to work, you'd need these:
- SolidBackgroundFillColorBaseBrush
- ButtonBackgroundPressed
- ButtonForegroundPressed
- ButtonForegroundPointerOver
- ButtonBackground
- ButtonBorderBrush
- ButtonForeground
- ButtonBackgroundDisabled
- ButtonBorderBrushDisabled
- ButtonForegroundDisabled
- ButtonBackgroundPointerOver
- ButtonBorderBrushPointerOver
- ButtonBorderBrushPressed

Those names are very derived from XAML, and in a world where RNW doesn't rely on XAML... are those the right "system" colors? Contrast with the [FURN Colors](https://github.com/microsoft/fluentui-react-native/blob/main/packages/theming/default-theme/src/defaultColors.ts). What's the boundary between system color and color palette served by a control library.

# Proposal
To get unblocked, just bypass this with specified colors (either in the Button JS or in PlatformColor) that used by any built in components. The problems mentioned above can wait.

Something [like this](https://github.com/microsoft/react-native-windows/compare/main...chrisglein:fabricPlatformColor?expand=1)? Needs support for theming thought at some point: https://github.com/microsoft/react-native-windows/issues/11489

With that fix:
image

### Steps To Reproduce

1. Clone https://github.com/chiaramooney/sample-fabric/
2. Add a `Button`
3. Where is it?
(it's there, you can click it, but none of it content renders)

Or, view in playground composition:
image

### Expected Results

I can see the button

### CLI version

11.0.0-alpha.2

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.25336
  CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Memory: 1.92 GB / 15.92 GB
Binaries:
  Node:
    version: 16.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.15.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33516.290 (Visual Studio Community 2022)
    - 16.11.33423.256 (Visual Studio Community 2019)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.0.0-20230321-2153-7b86e3aae
    wanted: 0.0.0-20230321-2153-7b86e3aae
  react-native-windows:
    installed: 0.0.0-canary.637
    wanted: 0.0.0-canary.637
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

_No response_

### Visual Studio Version

None

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by chrisglein**
### Type of Change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Why
Resolves #11456

### What
Implements some values in `PlatformColor` so that the built in controls can render.

Note that pending #11489, these colors will all be light mode. This will need to be revisited when theming exists.

## Screenshots
Add any relevant screen captures here from before or after your changes. 
| Before| After |
|--------|--------|
| image | image |

## Testing
- Manual verification of controls in RNTester
- Integration into a Fabric ap using Button and other non-core controls that use `PlatformColor`

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/11504)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp [hunk 1]
```diff
@@ -7,58 +7,113 @@
...
+    }
+    return xaml::Media::SolidColorBrush(m_color->m_color);
   }
-  return xaml::Media::SolidColorBrush(m_color->m_color);
-}
 #endif // CORE_ABI
 
-SharedColor colorFromComponents(ColorComponents components) {
-  float ratio = 255;
+  SharedColor colorFromComponents(ColorComponents components) {
```
Comment (jonthysell) [inline vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp:83]: Why the sudden indentation? Do you need to re-run `yarn format`?

File: vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp [hunk 2]
```diff
@@ -7,58 +7,113 @@
...
-    return false;
+    if (!color) {
+      return false;
+    }
+
+    return colorComponentsFromColor(color).alpha > 0;
+  }
+
+winrt::Windows::UI::Color ResolvePlatformColor(Color const * const color) {
+    // Issue #11489. These are all the light-theme values. Which is better than no values.
```
Comment (jonthysell) [inline vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp:18]: Can you add a comment on *where* you got these values from, so we know where to look in the future?

**Review by jonthysell — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp (hunk 1 above)
Comment (chrisglein) [reply vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp:83]: Ugh, thought I had removed those, must have re-added in my last edit. VS/VSCode's checked in config for the repo has "format on save" turned on, and the files are out of sync with the checked in clang format file. So it seems like either the format rules picked by the editor needs to be updated or there needs to be a whitespace-only pass on all the checked in Fabric files. I was explicitly trying to avoid getting into that mess for this change, but one of the commits when awry.

Comment (chrisglein) [reply vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp:83]: FWIW `yarn format` isn't running for me:

> \react-native-windows> yarn format
yarn run v1.22.19
$ format-files -i -style=file -assume-filename=../.clang-format
'format-files' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Comment (chrisglein) [reply vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp]: Rebased to fix the commit that messed with whitespace.

File: vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp (hunk 2 above)
Comment (chrisglein) [reply vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp]: Added comment with description and file url for both shared colors and control colors.

**Review by jonthysell — APPROVED** [review]
