### PR TITLE
Flyouts should dismiss when their island changes if they are light dismissable

### LINKED ISSUE #6077: Flyout doesn't hide when window is resized (Xaml Islands only)
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 163.66 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open playground win32 app.
2. Go to Flyout example.
3. Open Flyout.
4. Resize window.

## Expected Results
Expect that Flyout would hide. It stays visible. Note that this works correctly in the UWP Playground app. This issue is specific to Xaml Islands.

See this gist for a fixed version of FlyoutViewManager.cpp: https://gist.github.com/lyahdav/b3a533b19269f9d3a2ea0ba5f86f8184. I didn't have time to make a PR. Note that gist is off of an old master. The only relevant code is where `m_xamlRootChangedRevoker` is used.

### PR DESCRIPTION
**Pull request by asklar**
Fixes #6077 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6092)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp [hunk 1]
```diff
@@ -284,8 +287,14 @@ void FlyoutShadowNode::updateProperties(const folly::dynamic &&props) {
...
       if (m_isOpen) {
         auto popup = GetFlyoutParentPopup();
-        if (popup != nullptr)
+        if (popup != nullptr) {
           popup.IsLightDismissEnabled(m_isLightDismissEnabled);
+        }
+      }
+      if (m_xamlRootChangedRevoker && !m_isLightDismissEnabled) {
+        m_xamlRootChangedRevoker.revoke();
+      } else if (m_isLightDismissEnabled) {
```
Comment (NikoAri) [inline vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp:296]: >else if [](start = 8, length = 7)

(nit) maybe switch if and else if for readability?
if (m_isLightDismissEnabled)
else if(m_xamlRootChangedRevoker)

**Review by NikoAri — APPROVED** [review]
:shipit:

File: vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp [hunk 2]
```diff
@@ -358,6 +358,39 @@ winrt::Flyout FlyoutShadowNode::GetFlyout() {
...
+void FlyoutShadowNode::EnsureXamlRootChangedRevoker() {
+  if (m_xamlRootChangedRevoker) {
+    return;
+  }
+  if (auto flyoutBase6 = m_flyout.try_as<winrt::IFlyoutBase6>()) {
+    auto wkinstance = GetViewManager()->GetReactInstance();
+    if (auto instance = wkinstance.lock()) {
+      if (auto xamlRoot = static_cast<NativeUIManager *>(instance->NativeUIManager())->tryGetXamlRoot()) {
+        m_xamlRootChangedRevoker =
+            xamlRoot.Changed(winrt::auto_revoke, [this](auto &&, auto &&) { onDropViewInstance(); });
```
Comment (chrisglein) [inline vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp:388]: Assumption here seems to be that IsLightDismissEnabled is true. Which you handle by hooking/unhooking the event. You also could just _check_
```
if (IsLightDismissEnabled) {
    onDropViewInstance();
}
```

Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp:388]: @chrisglein thanks, I like it! it will simplify things.

File: vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp (hunk 1 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp:296]: thanks for taking a look! :) I took this out in the new commit.

**Review by jonthysell — APPROVED** [review]
