### PR TITLE
 Normalize paths provided by react-native.config.js

### LINKED ISSUE #7979: react-native.config.js errors on windows.vcxproj paths on non windows builds.
In non windows platform, when during the build process, the react-native.config.js is read. It actually parses the windows platform data and expects to find the vcxproj in ios/android builds.  This creates a problem if the vcxproj had a windows path containing \.   A path containing \ or / are both acceptable on windows, but only / is acceptable on non windows. 

I believe the problem stems originally from the react-native-cli, but is RNW related. So not sure who/how to track/report this bug, so just leaving here for now. 

Suggested possible fixes.

* Force windows to also error on non / so that only / is used for consistency across all platforms, instead of \\ 
* Force non windows to lazily read the file path, so it doesn't attempt to resolve windows path when not building for windows. 

Situations where problem was being mitigated in interim.

https://github.com/wonday/react-native-orientation-locker/pull/188
https://github.com/react-native-webview/react-native-webview/pull/2046

The Error:

```
error ENOENT: no such file or directory, open '/Users/namrog84/MyRepo/src/apps/MyApp/node_modules/react-native-orientation-locker/windows/OrientationWindows\OrientationWindows.vcxproj'. Run CLI with --verbose flag for more details.
[!] Invalid `Podfile` file: 767: unexpected token at 'Error: ENOENT: no such file or directory, open '/Users/namrog84/MyRepo/src/apps/MyApp/node_modules/react-native-orientation-locker/windows/OrientationWindows\OrientationWindows.vcxproj
```

This error stemmed from the react-native.config.js in react-native-orientation-locker

```
module.exports = {
  dependency: {
    platforms: {
      windows: {
        sourceDir: 'windows',
        solutionFile: 'OrientationWindows.sln',
        projects: [
          {
            projectFile: 'OrientationWindows\\OrientationWindows.vcxproj',
            directDependency: true,
          }
        ],
      },
	},
  },
};
```

### PR DESCRIPTION
**Pull request by jonthysell**
This PR makes sure that raw paths specified in a react-native.config.js
are normalized when config is run, before the result is passed up to
whichever CLI command called for it.

Closes #7979

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7982)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/config/projectConfig.ts [hunk 1]
```diff
@@ -115,7 +116,8 @@ export function projectConfigWindows(
       result.solutionFile =
         'Error: Solution file is null in react-native.config.';
     } else {
-      result.solutionFile = userConfig.solutionFile;
+      result.solutionFile = path.normalize(userConfig.solutionFile!);
+      validSolution = true;
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/config/projectConfig.ts:120]: is this right? we don't set validSolution back to false if one of the conditions below fails

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/config/projectConfig.ts:120]: The indentation from lint is confusing, but that line to set to true is in the `if (usingManualOverride)` block, and the later conditions are part of the `else` block.

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/config/projectConfig.ts:120]: I believe that path.normalize() will convert forward slashes to back slashes on Windows, but will not do the other way around on Unix systems. I had to add my own logic to do this in a separate project.

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/config/projectConfig.ts:120]: Since we're blocking the command from running on non-windows anyway, this normalization is mostly just to clean up unnecessary things like `project\..\project\`

Comment (asklar) [reply packages/@react-native-windows/cli/src/config/projectConfig.ts:120]: I mean the new `validSolution = true` in 120, versus the error conditions in 124-149

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/config/projectConfig.ts:120]: 124-149 are checking for project errors and set `validProject`, which is independent from the solution checks that set `validSolution`

**Review by asklar — APPROVED** [review]
