### PR TITLE
Fix resetting of playground comboboxes upon load

### LINKED ISSUE #6177: Playground comboboxes for bundle file/app name get reset upon load
- launch playground
- disable web debugging
- load rntester
When load completes, the comboboxes for bundle file and app name are reset

### PR DESCRIPTION
**Pull request by asklar**
Fixes #6177 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/6178)

### CODE REVIEW

File: packages/playground/windows/playground/MainPage.cpp [hunk 1]
```diff
@@ -82,7 +82,13 @@ void MainPage::OnLoadClick(
               strongThis->x_UseFastRefreshCheckBox().IsChecked(context.UseFastRefresh());
               strongThis->x_UseDirectDebuggerCheckBox().IsChecked(context.UseDirectDebugger());
               strongThis->x_BreakOnFirstLineCheckBox().IsChecked(context.DebuggerBreakOnNextLine());
-              strongThis->x_entryPointCombo().SelectedItem(winrt::box_value(context.DebugBundlePath()));
+              auto debugBundlePath = context.DebugBundlePath();
+              for (auto item : strongThis->x_entryPointCombo().Items()) {
```
Comment (NickGerleman) [inline packages/playground/windows/playground/MainPage.cpp:86]: nit: const ref

**Review by NickGerleman — APPROVED** [review]
