### PR TITLE
[Fabric] Add DeviceInfoModule

### LINKED ISSUE #11414: Rework Built-In DeviceInfo for Fabric
This comment exists within the playground-composition implementation and the new e2e-test-app-fabric implementation. Creating a work item to track tackling the fix for this so the workaround can be removed. 

See https://github.com/microsoft/react-native-windows/blob/1d2767e7ded6943ed7a4723d2d59186659afe011/packages/playground/windows/playground-composition/Playground-Composition.cpp#L145-L182 for source. 
// Work around crash in DeviceInfo when running outside of XAML environment
// TODO rework built-in DeviceInfo to allow it to be driven without use of HWNDs or XamlApps

### PR DESCRIPTION
**Pull request by marlenecota**
## Description
Add DeviceInfoModule implementation for Fabric.

### Type of Change
- New feature (non-breaking change which adds functionality)

### Why
Resolves #11414 

### What
Leverage existing win32 implementation for Fabric

## Testing
playground-composition builds and Constants look right + CI.

## Changelog
Should this change be included in the release notes: yes

Add DeviceInfoModule for Fabric
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/12450)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp [hunk 1]
```diff
@@ -65,28 +77,30 @@ void DeviceInfoHolder::InitDeviceInfoHolder(const Mso::React::IReactContext &con
...
-            }
-          });
+    } else {
+        hwnd = XamlUIService::GetIslandWindowHandle(deviceInfoHolder->m_context->Properties());
     }
   }
+
+  if (hwnd) {
+    deviceInfoHolder->m_wmSubscription = SubscribeToWindowMessage(
+        ReactNotificationService(context.Notifications()),
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp:87]: Is anyone firing this notification?  I suspect this currently requires the application to manually notify us when the window changes size.?

File: vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp [hunk 2]
```diff
@@ -32,13 +36,21 @@ DeviceInfoHolder::DeviceInfoHolder(const Mso::React::IReactContext &context) : m
 }
 
 void DeviceInfoHolder::InitDeviceInfoHolder(const Mso::React::IReactContext &context) noexcept {
```
Comment (jonthysell) [inline vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp:38]: Is there someplace where we were previously not registering DeviceInfo when running Fabric?

Comment (marlenecota) [reply vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp:38]: The module was being registered before, but it was crashing early on from DeviceInfoHolder being null since creation was only done under `if (xaml::TryGetCurrentApplication())`

File: vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp (hunk 1 above)
Comment (marlenecota) [reply vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp:87]: Added FowardWindowMessage so that it fires now.

File: packages/playground/windows/playground-composition/Playground-Composition.cpp [hunk 3]
```diff
@@ -480,6 +480,9 @@ LRESULT CALLBACK WndProc(HWND hwnd, UINT message, WPARAM wparam, LPARAM lparam)
     case WM_WINDOWPOSCHANGED: {
       auto windowData = WindowData::GetFromWindow(hwnd);
       windowData->UpdateSize(hwnd);
+
+      winrt::Microsoft::ReactNative::ReactNotificationService rns(windowData->InstanceSettings().Notifications());
+      winrt::Microsoft::ReactNative::ForwardWindowMessage(rns, hwnd, message, wparam, lparam);
```
Comment (marlenecota) [inline packages/playground/windows/playground-composition/Playground-Composition.cpp:485]: @jonthysell  we might be switching away from this API in the near future, but in the meantime, we might need to add this to the template.

Comment (acoates-ms) [reply packages/playground/windows/playground-composition/Playground-Composition.cpp:485]: Do we have an issue to switch this over to a real API that takes a size.  Something like MS::RN::NotifyOfWindowSizeChanged(rns, size);

Comment (marlenecota) [reply packages/playground/windows/playground-composition/Playground-Composition.cpp:485]: Opened #12497 to track the work

**Review by acoates-ms — APPROVED** [review]
