### PR TITLE
fix(ScrollView): Adds `manipulationModes` prop to enable gestures beh…

### LINKED ISSUE #569: Fix SwipeableListView
Rows in SwipeableListView are not able to capture the PanResponder.

### PR DESCRIPTION
**Pull request by rozele**
…ind ScrollView

Currently, the native ScrollView captures the pointer before any views inside the scroll view have a chance to respond to gestures. This breaks things like `SwipeableListView`, which uses a `PanResponder` behind the ScrollView to intercept X-dimension motions. This change adds a new prop to `ViewPropTypes` to support `ManipulationMode` on the UWP FrameworkElement. You must set the `ManipulationMode` of the view inside the `ScrollViewer` in order for it to respond to gestures without the pointer being captured by `ScrollViewer`.

Fixes #569

### CODE REVIEW

File: ReactWindows/ReactNative/UIManager/BaseViewManager.cs [hunk 1]
```diff
@@ -105,6 +106,32 @@ public void SetZIndex(TFrameworkElement view, int zIndex)
...
 
         /// <summary>
+        /// Sets the manipulation mode for the view.
+        /// </summary>
+        /// <param name="view">The view instance.</param>
+        /// <param name="manipulationModes">The manipulation modes.</param>
+        [ReactProp("manipulationModes")]
+        public void SetManipulationMode(TFrameworkElement view, JArray manipulationModes)
+        {
+            if (manipulationModes == null || manipulationModes.Count == 0)
```
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/BaseViewManager.cs]: need to return from this block.

File: ReactWindows/ReactNative/UIManager/BaseViewManager.cs [hunk 2]
```diff
@@ -105,6 +106,32 @@ public void SetZIndex(TFrameworkElement view, int zIndex)
...
+            {
+                view.ManipulationMode = ManipulationModes.System;
+            }
+
+            var manipulationMode = ManipulationModes.System;
+            foreach (var modeString in manipulationModes)
+            {
+                if (modeString.Type == JTokenType.String)
```
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/BaseViewManager.cs]: Do we need to throw for invalid input? Should we just use Debug.Assert here?

**Comment by matthargett** [comment]
Is there an example in UI Explorer that can be used to demonstrate the before/after?

File: ReactWindows/ReactNative/UIManager/BaseViewManager.cs [hunk 3]
```diff
@@ -105,6 +107,31 @@ public void SetZIndex(TFrameworkElement view, int zIndex)
...
+            if (manipulationModes == null)
+            {
+                view.ManipulationMode = ManipulationModes.System;
+                return;
+            }
+
+            var manipulationMode = ManipulationModes.System;
+            foreach (var modeString in manipulationModes)
+            {
+                Debug.Assert(modeString.Type == JTokenType.String);
```
Comment (sayar) [inline ReactWindows/ReactNative/UIManager/BaseViewManager.cs]: Are y'all using debug.assert's everywhere instead of exceptions?

**Comment by rozele** [comment]
@matthargett this PR makes the SwipeableListView example work in RNTester, I'll have a follow on PR that adds that exposes that example.

File: ReactWindows/ReactNative/UIManager/BaseViewManager.cs (hunk 3 above)
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/BaseViewManager.cs]: Nope, in this case the input validation is being done by the PropTypes declaration in React.js, so adding conditionals and exceptions are wasted compute cycles and wasted developer cycles to go for code coverage on those exceptions (if and when we add unit tests for ViewManager).

The Debug.Assert here is purely to document expectations.
