### PR TITLE
Fix Text.BackgroundColor overwriting foreground.

### LINKED ISSUE #7690: backgroundColor makes color stop working
If you create a text element like the following, it renders with black text on a black background instead of white text on a black background.:

`<Text style={{color: 'white', backgroundColor: 'black'}}>Hello!</Text>`

Additionally, there's some weirdness with reloading. Changing the backgroundColor requires an app restart for some reason.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
```
npx react-native --version
5.0.1-alpha.2
```
2. `npx react-native info`:
```
> npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (10) x64 Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
    Memory: 5.26 GB / 12.00 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.16299.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: 11.0.8 - C:\Program Files\Zulu\zulu-11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. add `<Text style={{color: 'white', backgroundColor: 'black'}}>Hello!</Text>` to a rnw app
2. Notice that the text is not white

## Expected Results
style.color should work, even when backgroundColor is specified.

### PR DESCRIPTION
**Pull request by rectified95**
Fixes #7690

We use XAML `TextHighlighter` to implement background coloring for `<Text>`, because `TextBlock` doesn't expose a plain `background` prop. This has the unintended consequence of overwriting the `foreground` property of the `TextBlock` or its child `Span` elements. The fix is to specify `TextHighlighter.Foreground`.

Incidentally, creating a highlighter with just `TextHighlighter.Foreground` specified, yields an uncalled for yellow background by default. The mitigation I'm using is to conditionally skip the creation of highlighters when traversing the tree (alternatively, set foreground to `Colors::Transparent`, which is less optimal since it involves the creation of a redundant highlighter - by then, `TextBlock.Foreground` or `Span.Foreground` has already been set.

Updated the snapshot library with https://github.com/asklar/XamlTreeDump/pull/9 to include `Texthighlighter.Foreground` in the tree dumps.

Adding several new examples to thoroughly test the interplay of `color` and `backgroundColor` for Text.
image
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7707)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 1]
```diff
@@ -72,40 +74,53 @@ class TextShadowNode final : public ShadowNodeBase {
...
     } else if (auto span = static_cast<ShadowNodeBase &>(child).GetView().try_as<winrt::Span>()) {
-      AddNestedTextHighlighter(m_ColorValue, span, static_cast<VirtualTextShadowNode &>(child).m_highlightData);
+      AddNestedTextHighlighter(
+          m_backgroundColor, m_foregroundColor, span, static_cast<VirtualTextShadowNode &>(child).m_highlightData);
     }
   }
 
   void AddNestedTextHighlighter(
       const std::optional<winrt::Windows::UI::Color> &parentColor,
+      const std::optional<winrt::Windows::UI::Color> &parentForeColor,
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:89]: nit: consider renaming the "parentColor" param to make it explicit it is the background color.

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp [hunk 2]
```diff
@@ -72,40 +74,53 @@ class TextShadowNode final : public ShadowNodeBase {
...
   }
 
-  void AddHighlighter(const winrt::Windows::UI::Color &color, size_t runSize) {
+  void AddHighlighter(
+      const std::optional<winrt::Windows::UI::Color> &backgroundColor,
+      const std::optional<winrt::Windows::UI::Color> &foregroundColor,
+      size_t runSize) {
     auto newHigh = winrt::TextHighlighter{};
-    newHigh.Background(react::uwp::SolidBrushFromColor(color));
+    newHigh.Background(react::uwp::SolidBrushFromColor(backgroundColor.value()));
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:119]: If foreground color is optional, but background color is required, could we wire parameter types to reflect that? I.e. only use the std::optional where std::nullopt would be a valid input. 

Having a parameter type that doesn't allow null values acts as an explicit invariant to the assumption the highlighted code makes, that backgroundColor always has a value.

**Review by NickGerleman — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Views/TextViewManager.cpp (hunk 2 above)
Comment (rectified95) [reply vnext/Microsoft.ReactNative/Views/TextViewManager.cpp:119]: True, `AddHighlighter` only gets called when `backgroundColor` is present, but since it's not always, I store it as std::optional in the shadow node (original PR remark). And then I just passed it around as such.
Given this, would it still be better to change this method's param to plain Color from optional, but keep the member field as optional? What about `AddNestedTextHighlighter` - it might get called with a null backgroundColor.
