### PR TITLE
Align WinAppSDK template to not hardcode package versions

### LINKED ISSUE #10796: RNW templates hardcode CppWinRT version
### Problem Description

Currently, the RNW CLI hardcodes a specific version of `Microsoft.Windows.CppWinRT` into new app/library projects. However this means various projects could all be building with different CppWinRT versions, which **may** work but at the very least means wasting time restoring different packages and complicating debugging.

As of #10794 , we give customers the ability to set a different CppWinRT version than RNW defaults to, but that only impacts projects from the RNW repo, not customer apps or community modules.

### Steps To Reproduce

1. Run `react-native-windows-init` in a RN project.
2. Check the version of `Microsoft.Windows.CppWinRT` specified by the PackageReference in the newly created project file

### Expected Results

The version should be set to the variable `(CppWinRTVersion)`, not a specific version.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

_No response_

### Target Device(s)

_No response_

### Visual Studio Version

_No response_

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

_No response_

### LINKED ISSUE #10798: RNW WinAppSDK templates hardcode msbuild items better served by an external targets file
### Problem Description

The RNW CLI WinAppSDK project template hardcodes various PackageReferences (our `Microsoft.ReactNative.WindowsAppSDK` and `Microsoft.WindowsAppSDK`) and includes some specialized MSIX packaging targets. We don't do that on other platforms, preferring to set those references within the External targets file, using parameterized values.

Similar to #10796 

### Steps To Reproduce

1. Run `react-native-windows-init --useWinUI3` in a RN project.
2. Check the versions of `Microsoft.ReactNative.WindowsAppSDK` and `Microsoft.WindowsAppSDK` specified by the PackageReference in the newly created project file

### Expected Results

_No response_

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

_No response_

### Target Device(s)

_No response_

### Visual Studio Version

_No response_

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by jonthysell**
This PR moves control of specifying various targets and package versions for PackageReferences for the WinAppSDK template into the external property sheets and uses variables that can be overridden, rather than stamping hardcoded versions into the template project files.

This PR also sets the template for C++/WinRT projects to consume the `CppWinRTVersion` variable, rather than a hardcoded version.

Closes #10796
Closes #10798

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10799)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/generator-windows/index.ts [hunk 1]
```diff
@@ -541,17 +541,5 @@ export async function installScriptsAndDependencies(options: {
 }
 function getWinAppSDKPackages(nugetVersion: string): NugetPackage[] {
```
Comment (AgneLukoseviciute) [inline packages/@react-native-windows/cli/src/generator-windows/index.ts:542]: would it be possible to also move the NETCore.UniversalWindowsPlatform import from `getUwpCsPackages()` out to a props file and get rid of these function calls altogether?

**Review by AgneLukoseviciute — APPROVED** [review]

File: packages/@react-native-windows/cli/src/generator-windows/index.ts (hunk 1 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts:542]: Yeah, I wasn't sure how far to take moving things. Because I *could* go for a CoreApp-style approach and move all package versions for all templates.

For WinAppSDK, with the SDK-style projects, I'm all for that approach.

For the UWP C++ and C#, I wasn't so sure.

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts:542]: I think I will leave this PR as is, and open a new bug to gauge if we want to go further.

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/generator-windows/index.ts:542]: Opened bug here: #10829
