### PR TITLE
Fixes race conditions for ReactImage

### LINKED ISSUE #7191: Race when changing Image src prop
Any time an asynchronous image source is used (e.g., whenever a network request must be made to download images when headers are specified in the image source), there is a race where the asynchronous image loading step may complete after the image source has been updated again. To demonstrate this, I modified the <Image /> native component to sleep for 5 seconds while making a network request for an image.
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone the exaggerated repro: https://github.com/rozele/react-native-windows/tree/imageRaceRepro
2. Launch RNTester
3. Open Image Example
4. Navigate to "Loading Indicator Source" example (modified for repro)
5. Click "Refresh Image" twice within 5 seconds.

## Expected Results

Expected behavior is that, the first time you click "Refresh Image", the image source changes to troll face. The next time you click "Refresh Image", the image source reverts to the original image. However, since we simulate a delay in the network request (with the Sleep(5000) call), the troll face image finishes loading _after_ you've reset the image to the original, and troll face is the final image that is display.

## Snack, code example, screenshot, or link to a repository:
Repro branch: https://github.com/rozele/react-native-windows/tree/imageRaceRepro

https://user-images.githubusercontent.com/1106239/108738854-06d5ee80-7502-11eb-8fcb-dcbfecb81e4f.mp4

### LINKED ISSUE #7192: Image disappears when rapidly switching between sources
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone the exaggerated repro: https://github.com/rozele/react-native-windows/tree/imageRaceRepro
2. Launch RNTester
3. Open Image Example
4. Navigate to "Loading Indicator Source" example (modified for repro)
5. Click "Refresh Image" twice within 5 seconds.

## Expected Results

Expected behavior is that, the first time you click "Refresh Image", the image source changes to troll face. The next time you click "Refresh Image", the image source reverts to the original image. However, since we simulate a delay in the network request (with the Sleep(5000) call), the image URI set on the ImageBrush is the same as the original URI, so the Opacity will be set to `0` but the ImageLoaded callback that should reset the Opacity to `1` will never be called because the URI is not truly updated.

## Snack, code example, screenshot, or link to a repository:
Repro branch: https://github.com/rozele/react-native-windows/tree/imageRaceRepro

https://user-images.githubusercontent.com/1106239/108743935-5cf96080-7507-11eb-92a0-1c0b7eb4a1d9.mp4

### PR DESCRIPTION
**Pull request by rozele**
This change adds a counter to ensure that only the latest prop value for
image source will be used in the ReactImage::SetBackground method and
also prevents a bug where the ImageBrush opacity gets stuck at zero by
checking that the URI has actually changed.

Fixes #7191
Fixes #7192

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7193)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp [hunk 1]
```diff
@@ -219,9 +222,15 @@ winrt::fire_and_forget ReactImage::SetBackground(bool fireLoadEndEvent) {
     if (strong_this && fireLoadEndEvent) {
       strong_this->m_onLoadEndEvent(*strong_this, false);
     }
+    co_return;
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:225]: Separate issue, and didn't repro, but it seems like we want probably want to bail out if there is some exception here.

File: vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp [hunk 2]
```diff
@@ -219,9 +222,15 @@ winrt::fire_and_forget ReactImage::SetBackground(bool fireLoadEndEvent) {
...
   }
 
   if (auto strong_this{weak_this.get()}) {
+    // If the image source has been updated since this operation started, do not continue
+    if (currentImageSourceId != strong_this->m_imageSourceId) {
```
Comment (rozele) [inline vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:230]: Note - we will not fire an onLoad / onLoadFailed / onLoadEnd in cases where the image source is updated before the async loading operation completes. I'm not sure what the expectations are in these cases.

Comment (acoates-ms) [reply vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:230]: Yeah, we should check what happens in the core platforms here, since we do want alignment. -- If you are not going to handle that here, at least open an issue to take a look at that later.

**Comment by acoates-ms** [comment]
@marlenecota - Just as an FYI incase you want to look at this, since you've touch the image code somewhat lately.

**Review by acoates-ms — APPROVED** [review]

**Comment by asklar** [comment]
Adding @marlenecota to review this as it's touching image

File: vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp (hunk 2 above)
Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:230]: Done. https://github.com/microsoft/react-native-windows/issues/7194, will update comment.

Comment (rozele) [reply vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:231]: FYI - found source code in iOS that shows similar behavior, documented in #7194 which is closed. There is not currently any implied contract that onLoadEnd fires every time this source changes, so there shouldn't be any concerns here.

**Review by marlenecota — APPROVED** [review]
