### PR TITLE
CLI: Default to deploy by layout

### LINKED ISSUE #8773: CLI `run-windows` should default to deploy from layout unless a cert is present / appx signing is enabled
### Summary

Right now we deploy from layout for debug but not release.

### Motivation

After removing the certs in #8672, using `--release` doesn't work without also adding `--deploy-from-layout`. It makes more sense to always deploy from layout (as VS does) and then only do a "real deploy" when there is a cert present (as VS does).

### Basic Example

| Command | Cert configured? | Deploy from layout? |
|:-|:-:|:-:|
| `run-windows` | No | Yes |
| `run-windows` | Yes | No |
| `run-windows --release` | No | Yes |
| `run-windows --release` | Yes | No |
| `run-windows --deploy-from-layout` | No | Yes |
| `run-windows --deploy-from-layout` | Yes | Yes* |
| `run-windows --release --deploy-from-layout` | No | Yes |
| `run-windows --release --deploy-from-layout` | Yes | Yes* |

*: Is this possible? Can we force a deploy from layout even when a cert is configured?

### Open Questions

_No response_

### PR DESCRIPTION
**Pull request by jonthysell**
This PR changes the CLI to always deploy from layout if:
- passed `--deploy-from-layout` (to force it) OR
- the build had `AppxSigningEnabled` missing or set to false OR
- the build had `PackageCertificateFile` not set

Alternatively, you can say we only try to deploy via package if BOTH
`AppxSigningEnabled` is set to true AND `PackageCertificateFile` is set.

Closes #8773

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8776)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts [hunk 1]
```diff
@@ -44,6 +45,69 @@ export function getBuildConfiguration(options: RunWindowsOptions): BuildConfig {
...
+  if (options.msbuildprops) {
+    const msbuildprops = build.parseMsBuildProps(options);
+    if ('AppxSigningEnabled' in msbuildprops) {
+      hasAppxSigningEnabled =
+        msbuildprops.AppxSigningEnabled.toLowerCase() === 'true';
+    }
+    if ('PackageCertificateKeyFile' in msbuildprops) {
+      hasPackageCertificateKeyFile = true;
+    }
+  }
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts:74]: should these be augmented with whatever the user passes via `--msbuildprops`?

**Review by asklar — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts (hunk 1 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts:74]: I don't understand what you mean. This code specifically parses `--msbuildprops` and looks for the two props we care about.

Comment (asklar) [reply packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts:74]: ah sorry I thought parseMsBuildProps was parsing the project xml to extract those props' values

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts:74]: I check what's passed on the command line first as it will override things, and if those properties weren't passed, only then do I spend the time parsing the project file
