### PR TITLE
Fixed .Net Native crash for custom struct deserialization

### LINKED ISSUE #3838: SampleAppCS in Release throws exception when clicking "Call SampleModuleCS!"
This only repros in Release bits, and is most certainly a .Net Native issue.

Call Stack:

>	System.Private.CoreLib.dll!System.RuntimeExceptionHelpers.FailFast(string message, System.Exception exception, System.RuntimeExceptionHelpers.RhFailFastReason reason, System.IntPtr pExAddress, System.IntPtr pExContext) Line 208	C#
 	System.Private.CoreLib.dll!System.RuntimeExceptionHelpers.GetRuntimeException(System.Runtime.ExceptionIDs id) Line 74	C#
 	[External Code]	
 	System.Private.Interop.dll!System.Runtime.InteropServices.McgMarshal.ComRelease(System.IntPtr pComItf) Line 731	C#
 	System.Private.Interop.dll!System.__ComObject.Cleanup(bool disposing) Line 796	C#
 	System.Private.Interop.dll!System.RCWFinalizer.~RCWFinalizer() Line 53	C#

### PR DESCRIPTION
**Pull request by vmoroz**
The investigation has shown that the .Net Native does not allow to have a parameter passed as 'ref' in a dynamically generated lambda. It was causing a crash when we generate ReadValue lambda to read custom class or struct where we pass the type by 'ref'.

In this PR we work around this issue by having a different delegate signature used for generating custom class reader. It uses return value instead of 'ref' parameter.

This change only affect the internal implementation of the Microsoft.ReactNative.SharedManaged code. There are no changes in user code required.

Closes #3838 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4696)

### CODE REVIEW

File: vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs [hunk 1]
```diff
@@ -211,13 +214,33 @@ private static Delegate GenerateReadValueForEnum(Type valueType)
         : null;
     }
 
+    public static void ReadClass<TClass>(IJSValueReader reader, out TClass value) where TClass : new()
+    {
+      // .Net Native seems to have a bug that does not allow to have 'out' or 'ref' parameters.
```
Comment (NikoAri) [inline vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs:219]: >bug [](start = 37, length = 3)

(nit) would be nice to contact .net team with this issue :)

File: vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs [hunk 2]
```diff
@@ -232,41 +255,50 @@ private static Delegate GenerateReadValueForClass(Type valueType)
...
-              While(reader.Call(GetNextObjectProperty, propertyName),
-                (members.Length != 0)
-                ? Switch(propertyName,
-                    members.Select(member => SwitchCase(
-                      value.SetPropertyStatement(member.Name, reader.CallExt(ReadValueOf(member.Type))),
-                      Constant(member.Name))).ToArray()) as Expression
-                : Default(typeof(void))))));
-      }
+      var fields =
+              from field in classType.GetFields(BindingFlags.Public | BindingFlags.Instance)
```
Comment (dannyvv) [inline vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs:263]: nit: seems indention seems to has changed
```suggestion
        from field in classType.GetFields(BindingFlags.Public | BindingFlags.Instance)
```

File: vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs (hunk 1 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs:219]: I did. No response.

---
In reply to: [414051939](https://github.com/microsoft/react-native-windows/pull/4696#discussion_r414051939) [](ancestors = 414051939)

File: vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs (hunk 2 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs]: Good catch! Fixed.

---
In reply to: [414053528](https://github.com/microsoft/react-native-windows/pull/4696#discussion_r414053528) [](ancestors = 414053528)

File: vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs (hunk 1 above)
Comment (asklar) [reply vnext/Microsoft.ReactNative.SharedManaged/JSValueReaderGenerator.cs:219]: @vmoroz could you file a bug in the dotnet runtime project?
https://github.com/dotnet/runtime
