### PR TITLE
Telemetry Refactor

### LINKED ISSUE #7312: Review telemetry schema
@jonthysell has some thoughts on what data we should collect through telemetry (e.g. sdk versions, vs versions, etc.).
We should get this done soon so we can turn telemetry back on.

### LINKED ISSUE #7903: Failing UTs after lockfile deduplication
It looks like reenabling JS UT parallelism leads to failiure of one of our tests. Going to leave fixing the test failure that slipped in for later.
```
ERR!  FAIL  src/test/sanitize.test.ts
ERR!   √ Sanitize message, no-op (2 ms)
ERR!   √ Sanitize message, project_dir (1 ms)
ERR!   √ Sanitize message, node_modules (1 ms)
ERR!   √ Sanitize message, other path
ERR!   √ Sanitize message, forward slashes (1 ms)
ERR!   √ Sanitize message, file share path
ERR!   √ Sanitize message, with cpu/thread id
ERR!   √ Error code (1 ms)
ERR!   √ Sanitize stack frame (1 ms)
ERR!   √ basic setup (2 ms)
ERR!   × thrown exception a->b, hello world (39 ms)
ERR!   √ throw exception with error code (19 ms)
ERR!   × thrown exception a->b, hello path (8 ms)
ERR!   √ trackEvent should not identify roleInstance (1 ms)
ERR!   √ No message (1 ms)
ERR! 
ERR!   ● thrown exception a->b, hello world
ERR! 
ERR!     expect(received).toBeTruthy()
ERR! 
ERR!     Received: false
ERR! 
ERR!       262 |   Telemetry.client!.flush();
ERR!       263 |
ERR!     > 264 |   expect(pass).toBeTruthy();
ERR!           |                ^
ERR!       265 |   Telemetry.client!.clearTelemetryProcessors();
ERR!       266 |   Telemetry.client!.addTelemetryProcessor(sanitizeEnvelope);
ERR!       267 |   done();
ERR! 
ERR!       at Object.<anonymous> (src/test/sanitize.test.ts:264:16)

```

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/pull/7901#r642135462_

### PR DESCRIPTION
**Pull request by jonthysell**
This PR refactors our RNW CLI telemetry code to be easier to consume, align with our requirements, and add a suite of unit and E2E tests.

**Note:** This PR does not *enable* telemetry collection yet - we still need to (re)-setup the service side to actually receive data, test the E2E pipeline and fix any bugs.

Closes #7312
Closes #7903

## Overview

All telemetry-related operations are driven by the `Telemetry` class, the `CodedError` type, and a small handful of helper functions exported from the  `@react-native-windows/telemetry` package. Consumers of this package (`@react-native-windows/cli` and `react-native-windows-init`) are provided this abstraction layer and are therefore no longer expected to understand the intricacies of the underlying telemetry service (Application Insights).

CLI commands are now generally restructured to follow this pattern:

```ts
async function cliCommand(args) {
  // Telemetry setup
  Telemetry.setup();
  Telemetry.startCommand(...);

  let cliCommandError: Error | undefined;
  try {
    await cliCommandInternal(args);
  } catch (error) {
    // Report any error thrown
    Telemetry.trackException(error);
    cliCommandError= error;
  }

  // Telemetry cleanup
  TelemetryTest.endCommand(...);
}
```

With this setup, none of the code within internal function (`cliCommandInternal` here) has any notion of or connection to the telemetry system, other than throwing `CodedError` whenever it hits a known error in our code that we wish to capture. (Note that none of the functionality of any of our commands were changed in this PR, as they were already throwing `CodedError` s with appropriate extra data, where appropriate). Any unknown errors are also caught and recorded by the Telemetry.

In the end, we expect up to two events from every CLI command: `RNWCLI.Command` and potentially one error event: `RNWCLI.CodedError`. The `RNWCLI.Command` event is fired in the call to `endCommand` and contains everything we want to know from a run of our commands, success or failure. If an error was thrown, then we'll also have fired an additional event with the call to `trackException`, including error codes, stack traces, etc. The two events can be correlated to one another via the `sessionId` property.

Every effort has been made to make sure that we can easily extend and update our CLI commands *without* having to update the telemetry code. For example, the work to gather the command line arguments/options passed, to gather project info and environment setup, are all set up in a standardized way and sanitize such data of PII.

## Work Remaining
- [x] Create module to calculate base telemetry properties
    - [x] deviceId (unique device id)
    - [x] deviceLocale (system locale)
    - [x] deviceNumCPUs (number of CPUs)
    - [x] deviceTotalMemory (total RAM)
    - [x] deviceDiskFreeSpace (free disk space)
    - [x] sampleRate (telemetry sampling rate)
    - [x] captureCI (are we capturing telemetry for CI, may change later as per #6479)
    - [x] isCI (are we currently running in CI)
    - [x] ciType (the type of CI being used)
    - [x] isMsftInternal (is this running on the Microsoft corporate domain)
    - [x] isCliTest (detect if we're just testing the CLI, not actually running it)
    - [x] getSessionId (used to correlate telemetry events)
- [x] Add unit tests for base telemetry properties module
- [x] Create module to discover versions of tools and dependencies for telemetry properties
    - [x] node
    - [x] npm
    - [x] react
    - [x] react-native
    - [x] @react-native-community/cli
    - [x] react-native-windows
    - [x] @react-native-windows/cli
    - [x] react-native-windows-init
    - [x] Microsoft.Windows.CppWinRT
    - [x] Microsoft.UI.Xaml
    - [x] Visual Studio
    - [x] yarn
- [x] Add unit tests for versions module
- [x] Create module to calculate project properties
    - [x]  getProjectId() (unique hash of project name)
    - [x] usesTypeScript() (project is using TS)
    - [x] usesReactNativeConfig() (project has a react-native.config.js file)
    - [x] configToProjectInfo() (converts react-native config info into telemetery info)
- [x] Add unit tests for project module
- [x] Update CLI to include config info for experimental properties
    - [x] need `useHermes` to calculate which JS engine, Chakra or Hermes
    - [x] need `useExperimentalNuget` to calculate building RNW from source or using nuget
    - [x] update configToProjectInfo() to parse it out
- [x] Create module to process and sanitize error telemetry
    - [x] tryGetErrorCode()
    - [x] sanitizeErrorMessage()
    - [x] sanitizeErrorStackFrame()
- [x] Add unit tests for error module
- [x] Refactor Telemetry object
    - [x] Remove access to internal fields
    - [x] Refactor setup into smaller methods
    - [x] Set base properties in setup
    - [x] Set cli properties in setup
    - [x] Set project properties
- [x] Implement Telemerty.startCommand()
- [x] Implement Telemerty.endCommand()
- [x] Move loose exported functions from telemetry module into more appropriate modules
- [x] Update `npx react-native-windows-init` to call the new APIs appropriately
    - [x] setup()
    - [x] startCommand()
    - [x] setProjectInfo()
    - [x] endCommand()
    - [x] trackException()
- [x] Update `npx react-native run-windows` to call the new APIs appropriately
    - [x] setup()
    - [x] startCommand()
    - [x] setProjectInfo()
    - [x] endCommand()
    - [x] trackException()
- [x] Update `npx react-native autolink-windows` command to report telemetry
    - [x] Add `telemetry` arg
    - [x] setup()
    - [x] startCommand()
    - [x] setProjectInfo()
    - [x] endCommand()
    - [x] trackException()
- [x] Update Telemetry tests module and add e2e telemetry tests

## Verification
- [x] Verify react-native-windows-init reports telemetry properly when creating a new canary project
- [x] Verify @react-native-windows/cli reports telemetry properly when using run-windows in a new canary project
- [x] Verify @react-native-windows/cli reports telemetry properly when using autolink-windows in a new canary project
- [x] Verify @react-native-windows/cli reports telemetry properly when using run-windows in a in-repo project
- [x] Verify @react-native-windows/cli reports telemetry properly when using autolink-windows in a in-repo project
- [x] Verify react-native-windows-init reports telemetry properly when creating a new project against older stable branches

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8253)

### CODE REVIEW

**Comment by jonthysell** [comment]
Currently waiting on https://github.com/microsoft/react-native-windows/pull/8402 to get in before I can wrap this up

**Comment by jonthysell** [comment]
I don't think this will meet the bar for 0.66. Marking this as 0.67 just in case.

File: packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts [hunk 1]
```diff
@@ -158,7 +151,6 @@ export const runWindowsOptions: CommandOption[] = [
   {
     name: '--info',
     description: 'Dump environment information',
-    default: false,
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts:161]: Be sure to update the typings above to reflect that these can now be undefined instead of always a raw boolean.

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts:161]: These typings come from the community cli and already accept undefined.

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts:161]: I mean the typings in the RunWindowsOptions type above, that we define.

Various options are set to either boolean, or boolean | undefined, based on whether a default is declared here.

**Comment by NickGerleman** [comment]
This PR is pretty big, with a lot of different changes it looks like.

Are there atomic changes we could pull out of this PR to have reviewed separately?

**Comment by jonthysell** [comment]
> This PR is pretty big, with a lot of different changes it looks like.
> 
> Are there atomic changes we could pull out of this PR to have reviewed separately?

Not really. I mean, you could separate out the tests as a separate PR, but the point of the refactor was taking something that wasn't enabled (the Telemetry code) that had tendrils throughout our commands and pull them all back into one place.

**Comment by jonthysell** [comment]
> > This PR is pretty big, with a lot of different changes it looks like.
> > Are there atomic changes we could pull out of this PR to have reviewed separately?
> 
> Not really. I mean, you could separate out the tests as a separate PR, but the point of the refactor was taking something that wasn't enabled (the Telemetry code) that had tendrils throughout our commands and pull them all back into one place.

I've extracted out the option default cleanup here: #8629

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 2]
```diff
@@ -4,207 +4,411 @@
...
+  protected static versionsProp: Record<string, string> = {};
+  protected static projectProp?:
+    | projectUtils.AppProjectInfo
+    | projectUtils.DependencyProjectInfo = undefined;
+
+  protected static reset(): void {
+    // Reset client
     if (Telemetry.client) {
-      Telemetry.client.config.disableAppInsights = true;
+      Telemetry.client.flush({isAppCrashing: true});
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:75]: This call (with `isAppCrashing`) is only made in-between tests to make sure events don't leak across.

The telemetry library was designed for long-running web apps, so batches up telemetry events and schedules them for later. So if your app is coming down because of a crash, this flag lets you tell the telemetry to *really* start flushing right away. Technically you can also pass in a callback that gets called when the telemetry has been submitted, but I omitted it here, since we're just resetting the state for the next test.

File: packages/@react-native-windows/cli/src/runWindows/runWindows.ts [hunk 3]
```diff
@@ -4,68 +4,67 @@
...
-    process.exitCode = 1;
+import {autolinkWindowsInternal, AutoLinkOptions} from './utils/autolink';
+
+/**
+ * Sanitizes the given option for telemetery.
+ * @param key The key of the option.
+ * @param value The unsanitized value of the option.
+ * @returns The sanitized value of the option.
+ */
+function optionSanitizer(key: string, value: any): any {
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/runWindows.ts:39]:
```suggestion
function optionSanitizer(key: keyof RunWindowsOptions, value: any): any {
```

File: packages/@react-native-windows/telemetry/package.json [hunk 4]
```diff
@@ -18,7 +18,15 @@
     "watch": "rnw-scripts watch"
   },
   "dependencies": {
-    "applicationinsights": "^1.8.8"
+    "@types/envinfo": "^7.8.1",
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/package.json:21]: Should be in `devDependencies`.

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 5]
```diff
@@ -4,207 +4,411 @@
...
+    Telemetry.client = new appInsights.TelemetryClient(
+      Telemetry.options.setupString,
+    );
+
+    // Uncomment for Fiddler testing
+    // Telemetry.client.config.proxyHttpUrl = 'http://localhost:8888';
+    // Telemetry.client.config.proxyHttpsUrl = 'http://localhost:8888';
+
+    Telemetry.client.config.disableAppInsights = Telemetry.isTest;
+    Telemetry.client.channel.setUseDiskRetryCaching(!Telemetry.isTest);
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:135]: Why enable only on non-test?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 6]
```diff
@@ -4,207 +4,411 @@
...
+      .toString();
+    Telemetry.client!.commonProperties.deviceTotalMemory = basePropUtils
+      .deviceTotalMemory()
+      .toString();
+    Telemetry.client!.commonProperties.deviceDiskFreeSpace = basePropUtils
+      .deviceDiskFreeSpace()
+      .toString();
+    Telemetry.client!.commonProperties.ciCaptured = basePropUtils
+      .captureCI()
+      .toString();
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:153]: Will this ever be `false` when `ciType` is also set?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 7]
```diff
@@ -4,207 +4,411 @@
...
+      return;
+    }
+
+    const props: Record<string, any> = {
+      eventName: 'RNWCLI.CodedError',
+    };
+
+    // Save off CodedError info
+    const codedError =
+      error instanceof errorUtils.CodedError
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:381]: Should we handle non-coded exceptions with a different event?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 8]
```diff
@@ -4,207 +4,411 @@
...
+        ? (error as errorUtils.CodedError)
+        : null;
+    props.codedError = {
+      type: codedError?.type ?? 'Unknown',
+      rawErrorCode: errorUtils.tryGetErrorCode(error.message) ?? '',
+      data: codedError?.data ?? {},
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:387]: This is a little bit dangerous, since we do not control the message of non-CodedError, and we cannot control the type of content (or data member) that appears in it. 

We should guard these to only instances of the errors that we fire, that are known to be telemetry safe.

File: packages/@react-native-windows/telemetry/src/utils/errorUtils.ts [hunk 9]
```diff
@@ -0,0 +1,157 @@
...
+  }
+}
+
+/**
+ * Tries to parse an error code out of an error message.
+ * @param msg An error message to process.
+ * @returns The parsed error code.
+ */
+export function tryGetErrorCode(msg: string): string | undefined {
+  const errorRegEx = /error (\w+\d+):/gi;
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/utils/errorUtils.ts:99]: Is this specifically trying to extract MSBuild error? Could we make that clear?

Curious of what known cases we have for the pattern though. E.g. I think compiler warnings will prefix the number with `C`.

File: packages/@react-native-windows/telemetry/src/utils/errorUtils.ts [hunk 10]
```diff
@@ -0,0 +1,157 @@
...
+      }
+      if (noPath !== '') {
+        clean.push(noPath);
+      }
+    } else if (part !== '') {
+      clean.push(part);
+    }
+  }
+  return clean.join('').trim();
+}
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/utils/errorUtils.ts:135]: This function is not safe to be used, since it by design only tries to remove some recognized patterns (and misses some important ones). We only enable it with `preserveErrorMessages`, but if full messages are opt-in, should we still try to scrub them?

File: packages/@react-native-windows/telemetry/src/utils/errorUtils.ts [hunk 11]
```diff
@@ -0,0 +1,157 @@
...
+  } else {
+    // case 2: method === <no_method> or something without '(', fileName is full path
+  }
+  // preserve only the last_directory/filename
+  frame.fileName = path.join(
+    path.basename(path.dirname(frame.fileName)),
+    path.basename(frame.fileName),
+  );
+  frame.assembly = '';
+}
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/utils/errorUtils.ts:157]: I do not think it is safe to include filename, since folks can hook other code into the CLI.

Maybe we can whitelist files in our package, relative to node_modules?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 12]
```diff
@@ -4,207 +4,411 @@
...
-    } else if (part !== '') {
-      clean.push(part);
+
+  static endCommand(info: CommandEndInfo, extraProps?: Record<string, any>) {
+    if (!Telemetry.client) {
+      return;
+    }
+
+    if (!Telemetry.commandInfo.startInfo) {
+      return;
```
Comment (NickGerleman) [inline packages/@react-native-windows/telemetry/src/telemetry.ts:335]: Throw on misuse?

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 13]
```diff
@@ -884,13 +889,70 @@ function verboseMessage(message: any, verbose?: boolean) {
...
+ */
+function optionSanitizer(key: string, value: any): any {
+  switch (key) {
+    case 'sln':
+    case 'proj':
+      return value === undefined ? false : true;
+    default:
+      return value === undefined ? false : value;
+  }
+}
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:906]: Same feedback as above for the `runWindows` version, we should be careful of newly added options.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 14]
```diff
@@ -884,13 +889,70 @@ function verboseMessage(message: any, verbose?: boolean) {
...
+ * Sanitizes the given option for telemetery.
+ * @param key The key of the option.
+ * @param value The unsanitized value of the option.
+ * @returns The sanitized value of the option.
+ */
+function optionSanitizer(key: string, value: any): any {
+  switch (key) {
+    case 'sln':
+    case 'proj':
+      return value === undefined ? false : true;
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:902]:
```suggestion
      return value !== undefined;
```

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 15]
```diff
@@ -884,13 +889,70 @@ function verboseMessage(message: any, verbose?: boolean) {
...
+ * @param config Config passed from react-native CLI.
+ * @param options Options passed from react-native CLI.
+ */
+async function autolinkWindows(
+  args: string[],
+  config: Config,
+  options: AutoLinkOptions,
+) {
+  await startTelemetrySession(
+    'autolink-windows',
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:929]: Is there a way to tell if we are being run by VS?

File: packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts [hunk 16]
```diff
@@ -154,3 +159,39 @@ export function newSuccess(text: string) {
...
+        );
+      }
+    } else {
+      console.log(
+        `Command failed. Re-run the command with ${chalk.bold(
+          '--logging',
+        )} for more information.`,
+      );
+    }
+  }
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts:196]: Does this function do nothing if no Error is passed in? Why is Error optional then?

**Review by NickGerleman — COMMENTED** [review]
Leaving a batch of comments now

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts]: I removed this.

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 17]
```diff
@@ -4,207 +4,411 @@
...
+    return false;
   }
 
-  static isCI(): boolean {
-    return (
-      process.env.AGENT_NAME !== undefined || // Azure DevOps
-      process.env.CIRCLECI === 'true' || // CircleCI
-      process.env.TRAVIS === 'true' || // Travis
-      process.env.CI === 'true' // other CIs
+  /** Populates the versions property of tools we care to track. */
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:249]: No, we don't break down how any of the time is spent running a command.

File: packages/@react-native-windows/cli/src/runWindows/runWindows.ts (hunk 3 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/runWindows.ts]: Fixed.

File: packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts [hunk 18]
```diff
@@ -0,0 +1,134 @@
...
+}
+
+/**
+ * Gets whether the process is running as part of our CLI tests.
+ * @returns Whether the process is running as part of our CLI tests.
+ */
+export function isCliTest(): boolean {
+  return (
+    process.env.RNW_CLI_TEST !== undefined &&
+    process.env.RNW_CLI_TEST.toLowerCase().trim() === 'true'
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts:117]: Telemetry's package.json when running `yarn test`.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 13 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts]: Fixed.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 14 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts]: This only works because these options happen to be flags, if we pass other types the existing logic is more applicable.

File: packages/@react-native-windows/cli/src/runWindows/runWindows.ts [hunk 19]
```diff
@@ -4,68 +4,67 @@
...
+    case 'root':
+    case 'target':
+    case 'sln':
+    case 'proj':
+    case 'buildLogDirectory':
+      return value === undefined ? false : true;
+    case 'msbuildprops':
+      return value === undefined ? 0 : value.split(',').length;
+    default:
+      return value === undefined ? false : value;
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/runWindows.ts]: All args must be captured, but yes, using `keyof` in the option sanitizers can make sure that devs adding new args will have to explicitly decide on sanitization behavior. I've also expanded the tests to make sure that devs must also add the args to the options interfaces in the first place (which is currently not enforced).

File: packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts [hunk 20]
```diff
@@ -0,0 +1,134 @@
...
+export function deviceDiskFreeSpace(drivePath?: string | null): number {
+  try {
+    const out = execSync(`dir /-C ${drivePath ?? process.cwd()}`)
+      .toString()
+      .split('\r\n');
+    const line = out[out.length - 2];
+    const result = line.match(/(\d+) [^\d]+(\d+) /);
+    if (result && result.length > 2) {
+      return Number(result[2]);
+    }
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts:61]: wmic is deprecated and no longer part of Windows.

File: packages/@react-native-windows/telemetry/src/utils/errorUtils.ts (hunk 9 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/errorUtils.ts:99]: I think it's for MSBuild errors. This is the logic we had before I just moved it here.

File: packages/@react-native-windows/telemetry/src/utils/versionUtils.ts [hunk 21]
```diff
@@ -0,0 +1,177 @@
...
+  } catch {}
+  return null;
+}
+
+/**
+ * Gets the version installed of the specified npm package.
+ * @param pkgName The npm package name.
+ * @returns The version installed, if available.
+ */
+export async function getVersionOfNpmPackage(
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/versionUtils.ts:70]: How does calling `require.resolve` not find the exact place where node would be looking, starting from the place where node looks?

File: packages/@react-native-windows/telemetry/src/telemetry.ts [hunk 22]
```diff
@@ -4,207 +4,411 @@
...
+const DefaultSetupString = '795006ca-cf54-40ee-8bc6-03deb91401c3';
+
+export const NpmPackagesWeTrack: string[] = [
+  '@react-native-community/cli',
+  '@react-native-windows/cli',
+  '@react-native-windows/telemetry',
+  'react',
+  'react-native',
+  'react-native-windows',
+  'react-native-windows-init',
```
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:46]: I think it can still work because I'm using `require` to find the package.json, but unfortunately I can't test this until I get it checked in so I can call `react-native-windows-init` without any workarounds like yarn link.

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 12 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:335]: I didn't want to create errors just for "you're using the telemetry library wrong" since we're using telemetry to report errors.

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 17 above)
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:249]: It might be an interesting metric to start gathering times for phases of a command, but I don't think it needs to be in this initial check-in. https://github.com/microsoft/react-native-windows/issues/9109

File: packages/@react-native-windows/telemetry/src/utils/versionUtils.ts (hunk 21 above)
[the remark this answers is not in the document]
Comment (NickGerleman) [reply packages/@react-native-windows/telemetry/src/utils/versionUtils.ts:70]: It has to do with the package you start from. Because `telemetry` doesn't declare the dependency, non yarn package managers will hide it away.

In general, you always need to do resolution searching from the root of the package that declares the dependency.

File: packages/@react-native-windows/telemetry/package.json (hunk 4 above)
Comment (NickGerleman) [reply packages/@react-native-windows/telemetry/package.json:21]: The typings shouldn't be needed though.

File: packages/@react-native-windows/cli/src/e2etest/autolink.test.ts [hunk 23]
```diff
@@ -528,6 +534,25 @@ test('Indirect autolink dependency', () => {
   );
 });
 
+// eslint-disable-next-line complexity
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/e2etest/autolink.test.ts:537]: Remove?

Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/e2etest/autolink.test.ts:537]: same below

**Comment by NickGerleman** [comment]
@jonthysell I think there are some layers where you could chop up this PR. Would be helpful to start getting bits merged that we know are all good.

File: packages/@react-native-windows/cli/src/e2etest/autolink.test.ts (hunk 23 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/e2etest/autolink.test.ts:537]: It's not technically necessary here for autolink, but we have too many options in run-windows

**Comment by jonthysell** [comment]
> @jonthysell Jon Thysell (JAUNTY) FTE I think there are some layers where you could chop up this PR. Would be helpful to start getting bits merged that we know are all good.

How do you propose I chop it up? If the telemetry library updates its API surface, then the consumers have to update. As it stands, the telemetry is just dead code. So the only option I can think of is:

1. PR 1: Strip out all telemetry calls from the cli and init packages
2. PR 2: Refactor of telemetry package
3. PR 3: Add telemetry calls back into cli and init packages

Is that enough?

File: packages/react-native-windows-init/src/Cli.ts [hunk 24]
```diff
@@ -334,32 +327,127 @@ function installReactNativeWindows(
   );
 }
 
-function getRNWInitVersion(): string {
+/**
+ * Sanitizes the given option for telemetery.
```
Comment (asklar) [inline packages/react-native-windows-init/src/Cli.ts:331]: typo: telemetry :P

File: packages/react-native-windows-init/src/Cli.ts [hunk 25]
```diff
@@ -334,32 +327,127 @@ function installReactNativeWindows(
...
-    if (
-      pkgJson.name === 'react-native-windows-init' &&
-      pkgJson.version !== undefined
-    ) {
-      return pkgJson.version;
+    const config = JSON.parse(
+      execSync('npx react-native config', {
+        stdio: ['ignore', 'pipe', 'ignore'],
+      }).toString(),
+    );
```
Comment (asklar) [inline packages/react-native-windows-init/src/Cli.ts:388]: consider not spawning a new nodejs instance and instead require config

File: packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts [hunk 26]
```diff
@@ -0,0 +1,71 @@
...
+      // We are under the windows path, anonymize with [windows]
+      return `[windows]\\???${ext}(${filepath.length})`;
+    } else if (rest.toLowerCase().startsWith(nodeModules)) {
+      // We are under the node_modules path
+      for (const trackedNpmPackage of NpmPackagesWeTrack) {
+        if (
+          rest
+            .toLowerCase()
+            .startsWith(nodeModules + trackedNpmPackage.replace(/\//g, '\\'))
+        ) {
```
Comment (asklar) [inline packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts:48]: this will capture things like react* - need to make sure we either add slashes to all entries in NpmPackagesWeTrack, or better yet add a slash here to force a strict match

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts [hunk 27]
```diff
@@ -0,0 +1,215 @@
...
+ * @returns The language of the RNW project.
+ */
+function getRnwLang(
+  config: Record<string, any> | null | undefined,
+): 'cpp' | 'cs' | null {
+  if (config) {
+    for (const project of config.projects) {
+      if (project.directDependency) {
+        return project.projectLang;
+      }
```
Comment (asklar) [inline packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:99]: this will return the first one, can't we have more than 1 direct dependency and so we should return an array of langs?

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts [hunk 28]
```diff
@@ -0,0 +1,215 @@
...
+      const rnwLang = config.project.windows.project?.projectLang;
+      const usesTS = await usesTypeScript(config.project.windows.folder);
+      const usesRNConfig = await usesReactNativeConfig(
+        config.project.windows.folder,
+      );
+      const jsEngine = parseBoolean(
+        config.project.windows.experimentalFeatures?.UseHermes,
+      )
+        ? 'Hermes'
+        : 'Chakra';
```
Comment (asklar) [inline packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:143]: Office will use V8 here; does Office use run-windows / do we care?

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts [hunk 29]
```diff
@@ -0,0 +1,215 @@
...
+      const rnwSource = parseBoolean(
+        config.project.windows.experimentalFeatures?.UseExperimentalNuget,
+      )
+        ? 'NuGet'
+        : 'Source';
+
+      const dependencies: DependencyProjectInfo[] = [];
+      for (const dependencyName in config.dependencies) {
```
Comment (asklar) [inline packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:151]: looks like useWinUI3 isn't captured here? is it captured elsewhere?

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts [hunk 30]
```diff
@@ -0,0 +1,215 @@
...
+      )
+        ? 'Hermes'
+        : 'Chakra';
+      const rnwSource = parseBoolean(
+        config.project.windows.experimentalFeatures?.UseExperimentalNuget,
+      )
+        ? 'NuGet'
+        : 'Source';
+
+      const dependencies: DependencyProjectInfo[] = [];
```
Comment (asklar) [inline packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:150]: we should probably capture WinUI2xVersion - and possibly WindowsTargetPlatformVersion

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 31]
```diff
@@ -980,6 +1049,11 @@ export const autolinkOptions: CommandOption[] = [
       "Override the app project file determined by 'react-native config', e.g. windows\\myApp\\myApp.vcxproj",
     default: undefined,
   },
+  {
+    name: '--no-telemetry',
+    description:
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:1054]: update the CLI readme with this new option

**Review by asklar — APPROVED** [review]
LGTM after the comments are addressed : )

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts (hunk 28 above)
Comment (NickGerleman) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:143]: Office uses the shared CLI commands (e.g. "start", "bundle"), but not run-windows, autolink-windows, or generate-windows.

Comment (NickGerleman) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:143]: Projects like FURN will use the CLI for their UWP test apps, but that only uses public bits.

File: packages/@react-native-windows/cli/src/e2etest/autolink.test.ts (hunk 23 above)
Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/e2etest/autolink.test.ts:537]: Is it possible change the code in run-windows so that it doesn't omit the warning, instead of disabling it for both?

Comment (jonthysell) [reply packages/@react-native-windows/cli/src/e2etest/autolink.test.ts:537]: fixed

File: packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts (hunk 26 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts:48]: fixed

File: packages/react-native-windows-init/src/Cli.ts (hunk 24 above)
Comment (jonthysell) [reply packages/react-native-windows-init/src/Cli.ts:331]: fixed

File: packages/react-native-windows-init/src/Cli.ts (hunk 25 above)
Comment (jonthysell) [reply packages/react-native-windows-init/src/Cli.ts:388]: We need the whole infra of the `react-native config` command to run in order to get data like what other platforms are supported.

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts (hunk 28 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:143]: react-native-win32 does not use our CLI, in fact it explicitly does not connect to the react-native CLI infra.

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts (hunk 27 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:99]: Also, this just occurred to me, don't we want to include the non-direct dependencies' languages anyway? I mean, they're necessary for the project to build.

Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:99]: I think that it's important that we capture the languages of every project that gets specified as needed. You can easily imagine a C# module project "wrapper" of a C++ non-module project, and we'd want to capture both.

File: packages/@react-native-windows/cli/src/runWindows/runWindows.ts (hunk 19 above)
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/runWindows.ts]: I fixed this for run-windows and autolink-windows, because the interfaces exist. I will do react-native-windows-init in another PR. Tracking issue: https://github.com/microsoft/react-native-windows/issues/9163

File: packages/@react-native-windows/telemetry/src/utils/versionUtils.ts (hunk 21 above)
[the remark this answers is not in the document]
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/versionUtils.ts:70]: Tracking issue here: https://github.com/microsoft/react-native-windows/issues/9164

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 5 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:135]: We're don't want telemetry from running unit tests to actually get transmitted. This caching is a mechanism where-by, if a transmit fails, the lib saves it to disk and the next time someone tries to send telemetry with this lib, it'll resend it. We don't want test events saved to disk to be picked up later and transmitted when we're not running tests.

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 7 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:381]: I don't think it's necessary, our coded events are just superset of error with a symbolic error type. So we just pass up the type "Unknown" if a regular Error is thrown.

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 8 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:387]: The data member only exists in CodedError, but yes we can double check that here.

File: packages/@react-native-windows/telemetry/src/utils/errorUtils.ts (hunk 10 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/errorUtils.ts:135]: This just sanitizes file paths and we have lots of tests for that. Do we need to do this when our current default is to strip all messages? No. This code won't even get run. Will we need this if we flip the switch, yes. If there are other patterns let's add them before we ever decide we need to flip the switch.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 31 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:1053]: Issue: https://github.com/microsoft/react-native-windows-samples/issues/602

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts (hunk 30 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:164]: Tracking: https://github.com/microsoft/react-native-windows/issues/9165

File: packages/@react-native-windows/telemetry/src/utils/projectUtils.ts (hunk 29 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/projectUtils.ts:165]: Tracking: https://github.com/microsoft/react-native-windows/issues/9165

File: packages/@react-native-windows/telemetry/src/telemetry.ts (hunk 6 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/telemetry.ts:153]: We are currently planning on _not_ capturing telemetry from CI runs. However if we decided to change that decision, it would be akin to changing our event sampling rate.

Having this field captured here lets us partition the data on its value and calculate accurate statistics.

File: packages/@react-native-windows/telemetry/src/utils/errorUtils.ts (hunk 11 above)
Comment (jonthysell) [reply packages/@react-native-windows/telemetry/src/utils/errorUtils.ts:157]: I will just change this to use our more robust logic around anonymized paths.
