### PR TITLE
Fix transform center point

### LINKED ISSUE #4077: Scale animations not occurring from center of component (19H1+)
### Environment

If you are using latest version:
1. `react-native -v`: 0.60.6
2. `react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 18.01 GB / 31.84 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
    react-native-windows: 0.60.0-vnext.133 => 0.60.0-vnext.133
    rnpm-plugin-windows: 0.3.5 => 0.3.5
  Installed UWP SDKs:
    10.0.14393.0
    10.0.15063.0
    10.0.16299.0
    10.0.17134.0
    10.0.17749.0
    10.0.17763.0
    10.0.18362.0

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

Create a project using react-native-windows that uses scale animations (see reproducible example below).

### Expected Behavior

Scale animation will occur at the center of the component, so the component will either grow or shrink from the center outwards in all directions.

### Actual Behavior

Scale animation occurs at the top-left of the component, so it grows or shrinks from the top-left to the bottom-right.

I see that there is a block comment in FrameworkElementViewManager right above the function "ApplyTransformMatrix" that explains the process that RNW uses to make the animation happen about the center rather than the top-left corner of the component, and I have confirmed that the code does go through that process (ApplyTransformMatrix -> StartTransformAnimation -> GetTransformCenteringExpression), but the animation still occurs from the top-left of the component.

### Reproducible Example

I created an example in base RN to show that it works in that case: https://snack.expo.io/@jagorrin/scale-animation-example

If the same code is used in a project consuming RNW, the scale animation will grow or shrink the component from the top-left to the bottom-right instead of from the center outwards in all directions.

### PR DESCRIPTION
**Pull request by kaiguo**
Fixes #4077.

The `g_HasActualSizeProperty` was not properly initialized which leads to a wrong code path when [creating center vector](https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Views/ExpressionAnimationStore.cpp#L49-L51). Moving the initialization to ShadowNodeBase so that we can have the correct value ready before the checks.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4169)

### CODE REVIEW

File: vnext/ReactUWP/Views/ShadowNodeBase.cpp [hunk 1]
```diff
@@ -99,12 +100,18 @@ winrt::Windows::UI::Composition::CompositionPropertySet ShadowNodeBase::EnsureTr
 // "center":  This is the center of the UIElement
 // "transform": This will hold the un-centered TransformMatrix we want to apply
 void ShadowNodeBase::UpdateTransformPS() {
+  auto uielement = m_view.try_as<winrt::UIElement>();
+  assert(uielement != nullptr);
+
+  if (g_HasActualSizeProperty == TriBit::Undefined) {
+    // ActualSize works on 19H1+ only
+    g_HasActualSizeProperty = (uielement.try_as<winrt::IUIElement10>()) ? TriBit::Set : TriBit::NotSet;
+  }
```
Comment (kmelmon) [inline vnext/ReactUWP/Views/ShadowNodeBase.cpp]: I suggest moving this logic to as early as possible - how about doing this in createView()?  I'm not worried about the perf cost of doing this one-time query.

Comment (kaiguo) [reply vnext/ReactUWP/Views/ShadowNodeBase.cpp]: yeah makes sense, moved over : )

**Comment by kaiguo** [comment]
Transform only works on 19H1+ but our test pipeline is using Windows Server 2019 which doesn't have the latest 19H1 changes.
[Platform.Version is undefined](https://github.com/microsoft/react-native-windows/issues/4176), I didn't find a good way to detect the OS version. Left some comment on the test and commenting it out for now.

File: vnext/ReactUWP/Views/ShadowNodeBase.cpp [hunk 2]
```diff
@@ -30,6 +31,13 @@ void ShadowNodeBase::updateProperties(const folly::dynamic &&props) {
 
 void ShadowNodeBase::createView() {
   m_view = GetViewManager()->CreateView(this->m_tag);
+
+  if (auto uielement = m_view.try_as<winrt::UIElement>()) {
+    if (g_HasActualSizeProperty == TriBit::Undefined) {
+      // ActualSize works on 19H1+ only
```
Comment (asklar) [inline vnext/ReactUWP/Views/ShadowNodeBase.cpp]: swap the order these two happen in, no use calling QueryInterface if we already set the global variable
