### PR TITLE
Use full path to powershell

### LINKED ISSUE #8756: Apps created in 0.65 do not build-deploy in VS
1. npx react-native init rn65
2. cd rn65
3. npx react-native-windows-init --overwrite
4. open windows\rn65.sln
5. F5

expected: app builds then deploys
actual: app fails to build:

image

### PR DESCRIPTION
**Pull request by asklar**
Fixes #8756 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8775)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts [hunk 1]
```diff
@@ -112,10 +113,12 @@ function getWindowsStoreAppUtils(options: RunWindowsOptions) {
     '..',
     '..',
     '..',
-    'powershell',
+    powershell,
```
Comment (asklar) [inline packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts:116]:
```suggestion
    'powershell',
```

**Comment by NickGerleman** [comment]
Is the concern here that the "powershell" pointed to may change?

**Review by jonthysell — APPROVED** [review]
