### PR TITLE
Flip ImageView in RTL mode

### LINKED ISSUE #4026: Images are mirrored in RTL mode
### Environment

```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.60.0-microsoft.35

$ react-native run-windows --info
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 37.32 GB / 63.90 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react-native: 0.60.0-microsoft.35 => 0.60.0-microsoft.35
    react-native-windows: 0.60.0-vnext.121 => 0.60.0-vnext.121
  Installed UWP SDKs:
    10.0.14393.0
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0
                                        
```

Target Device: Desktop
VS 2019
Repros in Debug and Release

### Steps to Reproduce

1. Create a View with an Image element in it
2. Set the preferred language in the OS to any RTL language (Arabic, for example)

### Expected Behavior
Layout elements should be mirrored in position, but Images should not be mirrored.

### Actual Behavior
Images are mirrored along with everything else in the UI. The only mitigation is to set `direction: 'ltr'` on the style of the Image element.

Sample image in en-US:
image

Sample image in ar-SA:
image

### PR DESCRIPTION
**Pull request by kaiguo**
Fix #4026.

Image gets flipped in RTL mode, which is not the desired behavior, unflipping it in ImageViewManager.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4064)

### CODE REVIEW

File: vnext/ReactUWP/Views/Image/ImageViewManager.cpp [hunk 1]
```diff
@@ -85,6 +86,19 @@ class ImageShadowNode : public ShadowNodeBase {
 
       imageViewManager->EmitImageEvent(reactImage.as<winrt::Grid>(), succeeded ? "topLoad" : "topError", source);
       imageViewManager->EmitImageEvent(reactImage.as<winrt::Grid>(), "topLoadEnd", source);
+
+
+      // ImageView gets flipped by yoga layout in RTL mode. Use ScaleTransfrom to flip it back.
+      const auto layoutDirection = winrt::Windows::ApplicationModel::Resources::Core::ResourceContext()
+                             .GetForCurrentView()
+                             .QualifierValues()
+                             .Lookup(L"LayoutDirection");
```
Comment (kmelmon) [inline vnext/ReactUWP/Views/Image/ImageViewManager.cpp]: Is this the only scenario that needs to be detected?  I'm wondering what happens if someone sets direction:rtl on an ancestor of the Image.

File: vnext/ReactUWP/Views/Image/ImageViewManager.cpp [hunk 2]
```diff
@@ -85,6 +86,19 @@ class ImageShadowNode : public ShadowNodeBase {
...
+      if (layoutDirection != L"LTR") {
+        const winrt::ScaleTransform horizontalFlipTransform;
+        horizontalFlipTransform.ScaleX(-1);
+        reactImage->RenderTransformOrigin(winrt::Point(0.5, 0.5));
+        reactImage->RenderTransform(horizontalFlipTransform);
```
Comment (kmelmon) [inline vnext/ReactUWP/Views/Image/ImageViewManager.cpp]: Using these properties will collide with the transform property in two ways:  1) There is a transform property that can be set on any component.  Setting a transform plus doing this invert need to be combined.  2) The transform properties internally uses "facades", which puts the UIElement into "strict" mode.  See FrameworkElementViewManager::updateProperties() for the non-animating case.  There is also an animating case to consider.  I think the solution for this will need to use facades when available.

File: vnext/ReactUWP/Views/Image/ImageViewManager.cpp (hunk 1 above)
Comment (kaiguo) [reply vnext/ReactUWP/Views/Image/ImageViewManager.cpp]: @kmelmon turns out our Image is not actually an Image, it's a Grid with image background instead. Grid inherits flow direction from parent and mirrors its background in RTL mode. I forced the Grid container to LTR mode, I think that fixed the issue.

Comment (kmelmon) [reply vnext/ReactUWP/Views/Image/ImageViewManager.cpp]: nice!  this makes sense.

---
In reply to: [378605745](https://github.com/microsoft/react-native-windows/pull/4064#discussion_r378605745) [](ancestors = 378605745)

**Comment by kmelmon** [comment]
Can you add a regression test for this?  We have XAML tree dump capability which could be useful here.

**Comment by kaiguo** [comment]
> Can you add a regression test for this? We have XAML tree dump capability which could be useful here.

Added. The tree dumper doesn't dump FlowDirection by default so I had to make some small modifications to it.

**Comment by kmelmon** [comment]
Thanks!

---
In reply to: [585523258](https://github.com/microsoft/react-native-windows/pull/4064#issuecomment-585523258) [](ancestors = 585523258)
