### PR TITLE
Better error reporting and elevating if necessary in CLI

### LINKED ISSUE #4640: Cannot run React Native Windows App
### Environment

$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 947.75 MB / 7.93 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1.npx react-native init ReactWindows --version ^0.61.5
2.cd ReactWindows
3.npx react-native-windows-init --overwrite
4. npx react-native run-windows

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

1. Try to run Without Using Visual Studio
Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=16.0 /bl
 × Building Solution: Utilization:          100.0    Average Utilization: 100.0...
 × Build failed with message undefined. Check your build configuration.
image

2. Try to run With Visual Studio 2019
image

3. Try to run with Visual Studio Code
Could not debug. Error while executing command 'c:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager': Error while executing command 'c:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager' (error code 101)
image

(Write what happened. Add screenshots!)

### react-native run-windows --logging
```
  If you see build failure on `react-native run-windows`, please try again with 'react-native run-windows --logging' and provide the [output.]
C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native-windows\PropertySheets\ReactPatches.targets(35,5):
 error MSB3027: Could not copy "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native\ReactCommon\fabric
\components\view\accessibility\accessibilityPropsConversions.h" to "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_mod 
ules\react-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\\fabric\components\vie 
w\accessibility\accessibilityPropsConversions.h". Exceeded retry count of 10. Failed.  [C:\Users\nghia\source\repos\React-Windows-HelloWorld\R 
eactWindows\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native-windows\PropertySheets\ReactPatches.targets(35,5): 
 error MSB3021: Unable to copy file "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native\ReactCommon\f 
abric\components\view\accessibility\accessibilityPropsConversions.h" to "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\nod 
e_modules\react-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\\fabric\component 
s\view\accessibility\accessibilityPropsConversions.h". Could not find a part of the path 'C:\Users\nghia\source\repos\React-Windows-HelloWorld 
\ReactWindows\node_modules\react-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\ 
\fabric\components\view\accessibility\accessibilityPropsConversions.h'. [C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\nod 
e_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
  Copying file from "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native\ReactCommon\fabric\textlayout
  manager\platform\ios\RCTTextPrimitivesConversions.h" to "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\reac
  t-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\\fabric\textlayoutmanager\pla 
  tform\ios\RCTTextPrimitivesConversions.h".
C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native-windows\PropertySheets\ReactPatches.targets(35,5):
 error MSB3027: Could not copy "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native\ReactCommon\fabric
\textlayoutmanager\platform\ios\RCTTextPrimitivesConversions.h" to "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_mod 
ules\react-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\\fabric\textlayoutmana 
ger\platform\ios\RCTTextPrimitivesConversions.h". Exceeded retry count of 10. Failed.  [C:\Users\nghia\source\repos\React-Windows-HelloWorld\R
eactWindows\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native-windows\PropertySheets\ReactPatches.targets(35,5): 
 error MSB3021: Unable to copy file "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native\ReactCommon\f 
abric\textlayoutmanager\platform\ios\RCTTextPrimitivesConversions.h" to "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\nod 
e_modules\react-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\\fabric\textlayou 
tmanager\platform\ios\RCTTextPrimitivesConversions.h". Could not find a part of the path 'C:\Users\nghia\source\repos\React-Windows-HelloWorld 
\ReactWindows\node_modules\react-native-windows\Microsoft.ReactNative\build\x86\Debug\Microsoft.ReactNative\react-native-patched\\ReactCommon\ 
\fabric\textlayoutmanager\platform\ios\RCTTextPrimitivesConversions.h'. [C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\nod 
e_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
Done Building Project "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-native-windows\Microsoft.ReactNati 
ve\Microsoft.ReactNative.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\windows\ReactWindows\ReactWindows.vcxproj.metaproj" ( 
default targets) -- FAILED.

Done Building Project "C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\windows\ReactWindows.sln" (default targets) -- FAILED
.
```
Deferred Messages
  
  Detailed Build Summary
  ======================

  ============================== Build Hierarchy (IDs represent configurations) =====================================================
  Id                  : Exclusive Time   Total Time   Path (Targets)
  -----------------------------------------------------------------------------------------------------------------------------------
  0                   : 0.140s           32.873s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\windows\ReactWindows. 
  sln ()
  | 1                 : 0.011s           32.721s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\windows\ReactWindows\ 
  ReactWindows.vcxproj.metaproj ()
  | . 4               : 25.936s           32.710s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-n 
  ative-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj ()
  | | | 5             : 1.287s           1.287s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\Common\Common.vcxproj ()
  | | | 6             : 1.780s           1.780s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\Folly\Folly.vcxproj () 
  | | | 7             : 1.283s           1.337s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\JSI\Universal\JSI.Universal.vcxproj ()
  | | | | 10          : 0.022s           0.022s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\Common\Common.vcxproj (GetNativeManifest)
  | | | . 11          : 0.032s           0.032s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\Common\Common.vcxproj (GetResolvedLinkLibs)
  | | | 8             : 1.011s           1.050s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\ReactCommon\ReactCommon.vcxproj ()
  | | | . 12          : 0.039s           0.039s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\Folly\Folly.vcxproj (GetNativeManifest)
  | | | 9             : 1.069s           1.217s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\ReactWindowsCore\ReactWindowsCore.vcxproj ()
  | | | | 13          : 0.061s           0.061s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\ReactCommon\ReactCommon.vcxproj (GetNativeManifest)
  | | | | 14          : 0.038s           0.038s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\Folly\Folly.vcxproj (GetResolvedLinkLibs)
  | | | . 15          : 0.048s           0.048s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\ReactCommon\ReactCommon.vcxproj (GetResolvedLinkLibs)
  | | | 16            : 0.034s           0.034s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\JSI\Universal\JSI.Universal.vcxproj (GetNativeManifest)
  | | . 17            : 0.067s           0.067s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\node_modules\react-nat 
  ive-windows\ReactWindowsCore\ReactWindowsCore.vcxproj (GetNativeManifest)
  | 2                 : 0.007s           0.007s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\windows\..\node_module 
  s\react-native-windows\ReactCommon\ReactCommon.vcxproj.metaproj ()
  . 3                 : 0.006s           0.006s       C:\Users\nghia\source\repos\React-Windows-HelloWorld\ReactWindows\windows\..\node_module 
  s\react-native-windows\ReactWindowsCore\ReactWindowsCore.vcxproj.metaproj ()

  ============================== Node Utilization (IDs represent configurations) ====================================================
  Timestamp:            1        Duration   Cumulative
  -----------------------------------------------------------------------------------------------------------------------------------
  637229702341547238:   0        0.102s     0.102s ..
  637229702342564518:   1        0.009s     0.111s
  637229702342654290:   4        0.414s     0.525s ........
  637229702346793353:   5        1.287s     1.811s .........................
  637229702359658793:   6        1.781s     3.592s ...................................
  637229702377471142:   7        0.120s     3.712s ..
  637229702378667945:   10       0.022s     3.734s
  637229702378887358:   7        0.849s     4.583s ................
  637229702387374655:   11       0.032s     4.615s
  637229702387693794:   7        0.315s     4.930s ......
  637229702390845408:   8        0.159s     5.088s ...
  637229702392431123:   12       0.039s     5.127s
  637229702392820076:   8        0.853s     5.980s .................
  637229702401347279:   9        0.125s     6.105s ..
  637229702402593933:   13       0.061s     6.166s .
  637229702403202336:   9        0.501s     6.666s ..........
  637229702408208927:   14       0.038s     6.704s
  637229702408587902:   15       0.048s     6.752s
  637229702409066628:   9        0.445s     7.197s ........
  637229702413514729:   4        0.008s     7.205s
  637229702413594563:   16       0.034s     7.239s
  637229702413933617:   17       0.067s     7.305s .
  637229702414601834:   4        25.515s     32.820s +++++ (scale 1:100)
  637229702669750161:   1        0.003s     32.823s
  637229702669780269:   2        0.007s     32.830s
  637229702669849906:   3        0.006s     32.836s
  637229702669909705:   0        0.037s     32.873s
  -----------------------------------------------------------------------------------------------------------------------------------
  Utilization:          100.0    Average Utilization: 100.0
× Building Solution
 × Build failed with message undefined. Check your build configuration.

### Additional context

(Write any other additional context that may help in root causing the issue.)

### PR DESCRIPTION
**Pull request by asklar**
Fixes #4640 

* Elevate if necessary for uninstall/install
* Provide guidance to re-run with --logging for more info
* Detect app crash on launch
We'll show the contents of the event log for the crash, something like
```
Faulting application name: ReactUWPTestApp.exe, version: 1.0.0.0, time stamp: 0x5e9fc65d
Faulting module name: KERNELBASE.dll, version: 10.0.19613.1000, time stamp: 0x0e8f9339
Exception code: 0xe0434352
Fault offset: 0x0012aa52
Faulting process id: 0x59c
Faulting application start time: 0x01d6185fc18954ed
Faulting application path: C:\Program Files\WindowsApps\ReactUWPTestApp_1.0.0.0_x86__kc2bncckyf4ap\ReactUWPTestApp.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a3452235-3abc-4f66-8d89-7f1a59ef413e
Faulting package full name: ReactUWPTestApp_1.0.0.0_x86__kc2bncckyf4ap
Faulting package-relative application ID: App
```

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4672)

### CODE REVIEW

**Comment by acoates-ms** [comment]
Any chance we can include some information on what to do with that information?  Is there a way for them to look up that report id and get some useful information out of it?

File: vnext/local-cli/runWindows/runWindows.js [hunk 1]
```diff
@@ -14,6 +14,17 @@ const msbuildtools = require('./utils/msbuildtools');
 const autolink = require('./utils/autolink');
 const chalk = require('chalk');
 
+function ExitProcessWithError(loggingWasEnabled) {
+  if (!loggingWasEnabled) {
+    console.log(
+      'Re-run the command with',
```
Comment (NickGerleman) [inline vnext/local-cli/runWindows/runWindows.js:20]: Consider using a template string here.

**Comment by asklar** [comment]
> Any chance we can include some information on what to do with that information? Is there a way for them to look up that report id and get some useful information out of it?

I wanted to get the CLR exception info out but that doesn't seem to be logged :(
