### PR TITLE
Expose YellowBox functionality to native code

### LINKED ISSUE #1039: Implement native mechanism for invoking the yellowbox (console.warn)
There is currently no way to invoke a yellow box (console.warn) from native code... This will allow a developer to issue a warning from the native code when something is not supported... That warning will show in DEBUG, but will be ignored in RELEASE mode...  This is in place of throwing an exception and/or adding DEBUG vs. RELEASE conditionals...

### PR DESCRIPTION
**Pull request by asklar**
Fixes #1039 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4740)

### CODE REVIEW

File: vnext/ReactUWP/Views/ShadowNodeBase.cpp [hunk 1]
```diff
@@ -154,5 +154,10 @@ void ShadowNodeBase::EnsureHandledKeyboardEventHandler() {
   }
 }
 
+void ShadowNodeBase::YellowBox(const std::string &message) {
+  const auto instance = GetViewManager()->GetReactInstance().lock();
+  instance->CallJsFunction("RCTLog", "logToConsole", folly::dynamic::array("warn", message));
```
Comment (vmoroz) [inline vnext/ReactUWP/Views/ShadowNodeBase.cpp:159]: >instance [](start = 2, length = 8)

Please add a check for null in case if lock() above fails.

File: vnext/ReactUWP/Views/ShadowNodeBase.cpp [hunk 2]
```diff
@@ -154,5 +154,10 @@ void ShadowNodeBase::EnsureHandledKeyboardEventHandler() {
   }
 }
 
+void ShadowNodeBase::YellowBox(const std::string &message) {
```
Comment (vmoroz) [inline vnext/ReactUWP/Views/ShadowNodeBase.cpp:157]: >) [](start = 57, length = 1)

Can we mark it as noexcept?

File: vnext/ReactUWP/Polyester/IconViewManager.cpp [hunk 3]
```diff
@@ -65,9 +65,11 @@ void IconShadowNode::updateProperties(const folly::dynamic &&props) {
     if (propertyName == "color") {
       if (IsValidColorValue(propertyValue))
         glyphs.Fill(BrushFrom(propertyValue));
-#if FUTURE
-      else if (propertyValue.isNull())
-        ; // Log error, must have a color
+#ifdef DEBUG
+      else if (propertyValue.isNull()) {
+        // Log error, must have a color
+        YellowBox("IconShadowNode - color property must be non-null");
```
Comment (acoates-ms) [inline vnext/ReactUWP/Polyester/IconViewManager.cpp:71]: Generally Facebook only does this warning once per instance.  You wouldn't want your app spammed with this error.
Unfortunately their warnOnce API isn't exposed to native.  But then again, its probably not hard to do something on the native side to only do this once.

File: vnext/ReactUWP/Views/ShadowNodeBase.cpp (hunk 2 above)
Comment (asklar) [reply vnext/ReactUWP/Views/ShadowNodeBase.cpp:157]: @vmoroz I don't think we can guarantee that callJSFunction doesn't throw, can we?

File: vnext/ReactUWP/Polyester/IconViewManager.cpp (hunk 3 above)
Comment (asklar) [reply vnext/ReactUWP/Polyester/IconViewManager.cpp:71]: YellowBox _already_ aggregates/coalesces like warnings into one and you just get one warning per message, with a badge for the # of times it has hit.
image

Comment (acoates-ms) [reply vnext/ReactUWP/Polyester/IconViewManager.cpp:71]: I believe that it only does that if it matches the last error.  So once we have multiple of these it would get very spammy.

Comment (asklar) [reply vnext/ReactUWP/Polyester/IconViewManager.cpp:71]: @acoates-ms confirmed that when I get the 53 test ones, then go to another page that shows a yellow box, then go to the 53 test yellowbox, the test yellowbox correctly adds those up and brings it to the top:

image
