### PR TITLE
Fix os.arch for x86/arm64

### LINKED ISSUE #10136: cannot run from cmd or through VS Code launch.json (when building on CPU that identifies as ia32)
### Problem Description

I have been trying to get my react windows project to build in VS Code for a few days now to no avail. 

I have followed all steps in this tutorial: https://microsoft.github.io/react-native-windows/docs/getting-started but have been matched with many different error messages:

Running the dependency script im told I have all dependencies required, although before manually fixing the visual studio install components, I was receiving an error that my windows was not in the specified range [6.1,6.3] to install some Microsoft packages, not sure if this is the issue. I upgraded my windows to the latest and that specific error went away

image

In my visual studio installer I have all required components installed: 

image

Currently, when launching either through the command line 'npx react-native run-windows' or the launch.json file, Im met with the following error. 

image

I am able to run the application by running 'npm start' from a powershell window, and using the [Debug | x64] configuration in Visual Studio, but not being able to run this through the command line indicates to me that something is wrong with the configuration that I would like to fix.

image

### Steps To Reproduce

1. follow steps in react native tutorial
2. attempt to run in VS Code using launch.json file
3. error
following the react native tutorial on both my personal desktop and work laptop have produced the same errors. 

### Expected Results

ability to run the application using 'npx react-native run-windows'

### CLI version

7.0.3

### Environment

```markdown
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) ia32 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.19 GB / 15.69 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files (x86)\nodejs\node.EXE      
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD    
    npm: 8.11.0 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32106.194 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: 0.68.5 => 0.68.5
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by asklar**
## Description
Fixes #10136

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
os.arch() returns 'ia32' for x86, and ia32 is not understood by the CLI

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/11659)

### CODE REVIEW

**Review by chrisglein — APPROVED** [review]

**Review by jonthysell — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts [hunk 1]
```diff
@@ -72,7 +72,12 @@ export const runWindowsOptions: CommandOption[] = [
   {
     name: '--arch [string]',
     description: 'The build architecture (ARM64, x86, x64)',
-    default: os.arch(),
+    default:
+      os.arch() === 'ia32'
+        ? 'x86'
```
Comment (vmoroz) [inline packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts:77]: >x86 [](http://example.com/codeflow?start=11&length=3)

Should we rather default to x64? I think modern CPUs are mostly 64 bit.

**Review by vmoroz — APPROVED** [review]
:shipit:

**Comment by jonthysell** [comment]
Possibly resolves #11642
