### PR TITLE
Resolve Transform Matrix before Animation

### LINKED ISSUE #12204: [Fabric] ActivityIndicator missing transform prop
### Problem Description

In #12115, the code for the transform prop was moved in into `CompositionBaseComponentView` to be used by all components, but the call to `updateTransformProps()` was not added to `ActivityIndicatorComponentView`.

### Steps To Reproduce

1. Set a `transform` style prop on an ActivityIndicator

### Expected Results

Transform is applied

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by sharath2727**
### Type of Change
- Bug fix (non-breaking change which fixes an issue)
- 
### Why
As of today, a simple transformation of a visual using transform prop below is not taking any effect because the parameters are not being used.
 transform: [
            { scaleX: 1 },
            { rotate: '45deg' }
        ],

Resolves #12204

### What
Use resolvetransform method to create a transform matrix of all operations and send it to animation.

## Screenshots
After resolvetransform:
{rotate: -45deg}
image

{rotate: 45deg}
image

{scale: 2}, {rotate: 45deg}
image

{scale: 2}, {rotate: 45deg}, {translateX: -10}
image

## Changelog
yes
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/13450)

### CODE REVIEW

**Review by acoates-ms — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp [hunk 1]
```diff
@@ -180,11 +180,46 @@ const facebook::react::LayoutMetrics &ComponentView::layoutMetrics() const noexc
   return m_layoutMetrics;
 }
 
+void ComponentView::FinalizeTransform(
```
Comment (TatianaKapos) [inline vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp:183]: Should this be noexcept?

**Review by TatianaKapos — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp (hunk 1 above)
Comment (sharath2727) [reply vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp:183]: Oops missed it.

**Review by TatianaKapos — APPROVED** [review]
