### PR TITLE
Fix autolinking to respect WinUI2xVersion or WinUI3Version set in ExperimentalFeatures.props

### LINKED ISSUE #8431: Autolinking Overwrites WinUI2xVersion Set in ExperimentalFeatures
Unpackaged applications require a special WinUI package, as is currently used in Playground-Win32. Playground currently disables autolinking, which has its own logic to set WinUI packages in `packages.config`. If autolinking is enabled, it will rewrite the WinUI package in `packages.config` with the stock version.

E.g. this is the result of running autolinking for playground-win32 (or building it from the CLI instead of VS) 
image

### PR DESCRIPTION
**Pull request by jonthysell**
This changes autolinking to look for those properties in
ExperimentalFeatures.props and if not found, then fallback to the values
in WinUI.props.

Note that while this "fixes" autolinking for playground win32
(unpackaged) it "breaks" autolinking for playground win32 (packaged) and
playground UWP. So regardless of this change, autolinking should remain
disabled when building any playground.

Tests have also been added to verfiy this change in logic.

Closes #8431

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8589)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 1]
```diff
@@ -686,11 +686,23 @@ export class AutolinkWindows {
...
-      // use the UseWinUI3 value in react-native.config.js, or if not present, the value from ExperimentalFeatures.props
+      // Check if WinUI2xVersion is specified in experimental features
+      const targetWinUI2xVersion = configUtils.tryFindPropertyValue(
+        experimentalFeatures.content,
+        'WinUI2xVersion',
+      );
+      // Check if WinUI3Version is specified in experimental features
+      const targetWinUI3xVersion = configUtils.tryFindPropertyValue(
+        experimentalFeatures.content,
+        'WinUI3Version',
```
Comment (dannyvv) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:697]: unrelated question: Should we upgrade the property to become `3x` to match `2x`?

**Review by dannyvv — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 1 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:697]: The tests I added actually failed because I didn't notice that difference. However, since this is something we "expose" for developers to set, I'm hesitant in changing names.

**Comment by jonthysell** [comment]
Hmm, it looks like Playground was updated to actually use autolinking (allowing the check to run)

**Comment by jonthysell** [comment]
In order for this to work, we need to re-disable autolinking for the playgrounds. We might be able to re-enable them once we address #8591.

**Comment by jonthysell** [comment]
@NickGerleman How do you feel about this? I mean, having to disable autolinking for the playgrounds again, at least until I can make headway with #8591.

**Comment by NickGerleman** [comment]
> @NickGerleman How do you feel about this? I mean, having to disable autolinking for the playgrounds again, at least until I can make headway with #8591.

Go for it
