### PR TITLE
Fix hardware back events

### LINKED ISSUE #10742: Hardware back button events are broken
### Problem Description

Line 430 has a typo in it ("hardward") which causes the event it fires to never be picked up by the JS side:
https://github.com/microsoft/react-native-windows/blob/7196c86120722a52d4595c26a321872c2a242238/vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp

I have a PR I will make implementing a patch we have on our app to fix this (by just fixing the typo)

### Steps To Reproduce

1. Attach a callback for back button press events via BackHandler.addEventListener()
2. Observe that the handler isn't called

### Expected Results

Handler is called

### CLI version

7.0.3

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
    Memory: 40.55 GB / 63.69 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.3.32901.215 (Visual Studio Enterprise 2022), 16.11.32901.82 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: 7.0.3 => 7.0.3
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-windows: 0.67.6 => 0.67.6
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

_No response_

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by DrewHigginsMSFT**
### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
Fixes a typo that was causing hardware back button event subscriptions to not fire in JS.

Resolves #10742 

### What
Fixed typo "hardward" -> "hardware"

Tested locally in our app by applying this change as a patch to our node_modules via `npx patch-package`

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/10743)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp [hunk 1]
```diff
@@ -427,7 +427,7 @@ bool TouchEventHandler::DispatchBackEvent() {
     return false;
```
Comment (acoates-ms) [inline vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp:428]: We should probably be checking the QuirkSettings::GetBackHandlerKind before forwarding the event to JS and marking it as handled. Looks like we are not correctly checking that in the case of the pointer event.

See https://microsoft.github.io/react-native-windows/docs/native-api/QuirkSettings#setbackhandlerkind

```cpp
if (winrt::Microsoft::ReactNative::implementation::QuirkSettings::GetBackHandlerKind(
          winrt::Microsoft::ReactNative::ReactPropertyBag(m_context->Properties())) ==
      winrt::Microsoft::ReactNative::BackNavigationHandlerKind::JavaScript)
```

**Review by asklar — APPROVED** [review]

**Comment by rozele** [comment]
Ouch, looks like this should also be picked back to v0.66 and above. Introduced in #7837. My bad. Thanks for the fix!
