### PR TITLE
Autolinking doesn't add a project marked as a non-direct dependency

### LINKED ISSUE #7437: Autolinking is broken for react-native-webview
Autolinking isn't working for react-native-webview. The module was added before we had the props/targets that we used to infer that something is a RNW module. Moreover, we have a bug in autolinking where projects that a module depends on, that are not themselves RNW modules, are not added to the solution.

### PR DESCRIPTION
**Pull request by asklar**
Fixes #7437 

The following check incorrectly marks a project with `directDependency: false` as invalid:
```ts
itemsToCheck.forEach(item => {
    dependencyIsValid = !!(dependencyIsValid &&
        item in project &&
        project[item] &&
        !project[item].toString().startsWith('Error: '));
});
```

Adding some basic tests to ensure the indirect dependency is captured as valid

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7438)

### CODE REVIEW

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts [hunk 1]
```diff
@@ -434,7 +434,7 @@ export class AutolinkWindows {
                 dependencyIsValid = !!(
                   dependencyIsValid &&
                   item in project &&
-                  project[item] &&
+                  project[item] !== '' &&
```
Comment (NickGerleman) [inline packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:437]: Is the intention here to allow null but not empty string?

Maybe not for now, but I've noticed a lot of the schema validation code here is tricky. There are some libraries we use in other places to automate this (e.g. `io-ts`), where it's quite simple to define a schema as a TS type and check an object against it at runtime. Would be nice to look at something like that, since it would reduce bug-surface, do more type checks, and enforce our TS types are correct.

E.g. this is how we declaratively define part of the `overrides.json` schema in Serialized.ts

```ts
/**
 * Serialized form of {@see PatchOverride}
 */
const PatchOverrideType = t.type({
  type: t.literal('patch'),
  file: t.string,
  baseFile: t.string,
  baseVersion: t.union([t.undefined, t.string]),
  baseHash: t.string,
  issue: t.union([t.undefined, t.number]),
});
```

Comment (asklar) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:437]: Filed #7439

**Review by NickGerleman — APPROVED** [review]

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 1 above)
Comment (jonthysell) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:437]: `directDependency` is a required field and is supposed to be a boolean true/false.

https://microsoft.github.io/react-native-windows/docs/0.63/config#project-object-fields-1

This regression was made during the conversion to typescript. The original code was `project[item] !== null`.

**Review by jonthysell — APPROVED** [review]
Thank you @asklar for adding tests.

File: packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts (hunk 1 above)
Comment (NickGerleman) [reply packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts:437]: I meant that IIRC the final version of 0.62 with autolinking was after the TS conversion. So I think it was released with this.
