### PR TITLE
Fix Bug in Accessible/Focusable Behavior

### LINKED ISSUE #9826: Keyboard Focus and Accessibility Focus should be the same
### Problem Description

According to UIA and Narrator team, on Windows, keyboard focus and accessibility focus should always point to the same element. Currently in RNW, when a focusable element is passed `accessible=false`, the element is removed from the UIA tree but remains keyboard focusable. Thus the user, when tabbing to an element with `accessible=false` with a screen reader enabled, can see keyboard focus move to the element and accessibility focus jump to the app window. Then, the screen reader announces `<app name> window` creating a poor/disorienting screen reader experience. 

### Steps To Reproduce

Run the Playground App.
Edit a sample page to include a TouchableHighlight control and with the `accessible` set to false. 
Enable narrator.
Tab to TouchableHighlight.

### Expected Results

When an element is passed `accessible=false`, it should no longer be `focusable` leading both keyboard focus and the screen reader to skip over the element. 

### CLI version

N/A

### Environment

```markdown
N/A
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by chiaramooney**
### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)
- 
### Why
According to UIA and Narrator team, on Windows, keyboard focus and accessibility focus should always point to the same element. Currently in RNW, when a focusable element is passed accessible=false, the element is removed from the UIA tree but remains keyboard focusable. Thus the user, when tabbing to an element with accessible=false with a screen reader enabled, can see keyboard focus move to the element and accessibility focus jump to the app window. Then, the screen reader announces <app name> window creating a poor/disorienting screen reader experience.

Resolves #9826

### What
Modify native handling of accessible and focusable prop for view based and control based components such that both accessible and focusable must be true for an element to be focusable and accessible. If one is set to false, the component will behave as if both have been set to false. 

## Testing
Tested in playground and playground win32 by setting accessible and focusable to all configurations on a range of components and running narrator. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9840)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp [hunk 1]
```diff
@@ -197,6 +197,12 @@ bool FrameworkElementViewManager::UpdateProperty(
         } else {
           xaml::Automation::AutomationProperties::SetAccessibilityView(element, winrt::AccessibilityView::Raw);
         }
+        if (auto control = nodeToUpdate->GetView().try_as<xaml::Controls::Control>()) {
+          if (control.IsTabStop() != propertyValue.AsBoolean()) {
+            control.IsTabStop(false);
+            xaml::Automation::AutomationProperties::SetAccessibilityView(element, winrt::AccessibilityView::Raw);
+          }
+        }
```
Comment (NickGerleman) [inline vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp:205]: Consider adding logic matching `ViewViewManager` to `ControlViewManager`, instead of this fallback in `FrameworkElementViewManager` It gets potentially confusing for multiple classes in the same hierarchy to mutate the same properties on the control. Reading `accessible` in those two view managers would fix the `focusable` implementation everywhere we provide `focusable` I think.

**Review by NickGerleman — APPROVED** [review]

**Review by AgneLukoseviciute — APPROVED** [review]
