### PR TITLE
Fix crash when adding a ReactRootView while reloading a ReactHost

### LINKED ISSUE #7920: Win32 Playground crashes when disabling Web Debugger
## Environment
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 121.86 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210524.090203 - C:\tools\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31229.75 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone repo
2. Run playground-win32.sln
3. In Playground Win32 app go to File > Settings > uncheck Web Debugger
4. File > Open Javascript File
5. Pick RNTester
6. App crashes

## Expected Results
Expected: No crash.
Actual: Crash:
```
Exception thrown at 0x00007FFE8CE8D259 (Microsoft.ReactNative.dll) in Playground-win32.exe: 0xC0000005: Access violation writing location 0x0000000000000000.
```

Call stack:
```
>	Microsoft.ReactNative.dll!CrashWithRecovery(unsigned int tag) Line 24	C++
 	Microsoft.ReactNative.dll!winrt::Microsoft::ReactNative::implementation::ReactRootView::UpdateRootViewInternal() Line 191	C++
 	Microsoft.ReactNative.dll!winrt::Microsoft::ReactNative::implementation::ReactRootView::InitRootView(Mso::CntPtr<Mso::React::IReactInstance> && reactInstance, Mso::React::ReactViewOptions && reactViewOptions) Line 164	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::ReactViewInstance::InitRootView::__l2::<lambda>(winrt::com_ptr<winrt::Microsoft::ReactNative::implementation::ReactRootView> & rootControl) Line 26	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::ReactViewInstance::PostInUIQueue::__l2::<lambda>() Line 45	C++
 	Microsoft.ReactNative.dll!Mso::Executors::Internal::ExecutorInvoker::Invoke<Mso::Maybe<void> <lambda>(void) &>(Microsoft::ReactNative::ReactViewInstance::PostInUIQueue::__l2::Mso::Maybe<void> <lambda>(void) & callback) Line 203	C++
 	Microsoft.ReactNative.dll!Mso::Futures::FutureTaskInvoke<Mso::Executors::Executor,Mso::Maybe<void> <lambda>(void),void,Mso::Maybe<void>,4>::Invoke(const Mso::Async::ArrayView<unsigned char> & taskBuffer, Mso::Futures::IFuture * future, Mso::Futures::IFuture * __formal) Line 317	C++
 	Microsoft.ReactNative.dll!Mso::Futures::FutureImpl::Invoke() Line 271	C++
 	Microsoft.ReactNative.dll!Mso::Futures::FutureCallback::Invoke() Line 980	C++
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<void __cdecl(void)> && task, std::optional<std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000>>>> endTime) Line 208	C++
 	Microsoft.ReactNative.dll!Mso::TaskDispatcherHandler::Invoke() Line 173	C++
 	[External Code]	
 	Playground-win32.exe!RunPlayground(int showCmd, bool useWebDebugger) Line 404	C++
 	Playground-win32.exe!WinMain(HINSTANCE__ * instance, HINSTANCE__ * __formal, char * __formal, int showCmd) Line 431	C++
 	[External Code]	
```

### PR DESCRIPTION
**Pull request by acoates-ms**
Fixes #7920

Playground win32 has a pretty weird setup of creating a host, then when you tell it to load the instance it will trigger a host.ReloadInstance, and then immediately create a new `ReactRootView` and associate it with the host.

When this happens first an unload is triggered in the existing instance.  That is an async operation, during which time the new `ReactRootView` tries to attach to the host, and ends up attaching to the old instance.  Then the new instance is loaded, which then also tries to attach to the new `ReactRootView`, which crashes due to some checks verifying that a view is always unloaded before it gets another load.

Also renamed the live reload option in the playground win32 app to fast refresh, and got rid of the reuse instance checkbox which wasn't hooked up to anything.  And hooked up the reload instance menu to actually reload the instance.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/8042)

### CODE REVIEW

File: vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp [hunk 1]
```diff
@@ -536,10 +537,10 @@ Mso::Future<void> ReactViewHost::InitViewInstanceInQueue() noexcept {
     return Mso::MakeCanceledFuture();
   }
 
-  //// We cannot load if instance is not loaded.
-  // if (!m_reactHost->IsInstanceLoaded()) {
-  //  return Mso::MakeCanceledFuture();
-  //}
+  //// We cannot load if instance is in the process of being unloaded.
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp:540]: nit: please remove the extra //

**Review by vmoroz — APPROVED** [review]

**Review by asklar — APPROVED** [review]
