### PR TITLE
[Image] add svg data uri support

### LINKED ISSUE #4669: Svg data uris triggers an exception for ReactImage
### Steps to Reproduce

1) Take an svg file and base64 encode it as described in [this post](https://css-tricks.com/lodge/svg/09-svg-data-uris/)

2) Attempt to launch the RNW application

### Expected Behavior

Data uris for svgs load the svg just like they do for pngs on RNW.

(Write what you thought would happen.)

### Actual Behavior

ReactImage, while calling DecodeFromBase64String triggers an exception causing the image to not load and the application to crash.

### Reproducible Demo

`<Image 
    style={{ resizeMode: 'center' }}
source={{  uri: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4PSIwcHgiIHk9IjBweCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDEwMCAxMDAiIHhtbDpzcGFjZT0icHJlc2VydmUiIGhlaWdodD0iMTAwcHgiIHdpZHRoPSIxMDBweCI+CjxnPgoJPHBhdGggZD0iTTI4LjEsMzYuNmM0LjYsMS45LDEyLjIsMS42LDIwLjksMS4xYzguOS0wLjQsMTktMC45LDI4LjksMC45YzYuMywxLjIsMTEuOSwzLjEsMTYuOCw2Yy0xLjUtMTIuMi03LjktMjMuNy0xOC42LTMxLjMgICBjLTQuOS0wLjItOS45LDAuMy0xNC44LDEuNEM0Ny44LDE3LjksMzYuMiwyNS42LDI4LjEsMzYuNnoiLz4KCTxwYXRoIGQ9Ik03MC4zLDkuOEM1Ny41LDMuNCw0Mi44LDMuNiwzMC41LDkuNWMtMyw2LTguNCwxOS42LTUuMywyNC45YzguNi0xMS43LDIwLjktMTkuOCwzNS4yLTIzLjFDNjMuNywxMC41LDY3LDEwLDcwLjMsOS44eiIvPgoJPHBhdGggZD0iTTE2LjUsNTEuM2MwLjYtMS43LDEuMi0zLjQsMi01LjFjLTMuOC0zLjQtNy41LTctMTEtMTAuOGMtMi4xLDYuMS0yLjgsMTIuNS0yLjMsMTguN0M5LjYsNTEuMSwxMy40LDUwLjIsMTYuNSw1MS4zeiIvPgoJPHBhdGggZD0iTTksMzEuNmMzLjUsMy45LDcuMiw3LjYsMTEuMSwxMS4xYzAuOC0xLjYsMS43LTMuMSwyLjYtNC42YzAuMS0wLjIsMC4zLTAuNCwwLjQtMC42Yy0yLjktMy4zLTMuMS05LjItMC42LTE3LjYgICBjMC44LTIuNywxLjgtNS4zLDIuNy03LjRjLTUuMiwzLjQtOS44LDgtMTMuMywxMy43QzEwLjgsMjcuOSw5LjgsMjkuNyw5LDMxLjZ6Ii8+Cgk8cGF0aCBkPSJNMTUuNCw1NC43Yy0yLjYtMS02LjEsMC43LTkuNywzLjRjMS4yLDYuNiwzLjksMTMsOCwxOC41QzEzLDY5LjMsMTMuNSw2MS44LDE1LjQsNTQuN3oiLz4KCTxwYXRoIGQ9Ik0zOS44LDU3LjZDNTQuMyw2Ni43LDcwLDczLDg2LjUsNzYuNGMwLjYtMC44LDEuMS0xLjYsMS43LTIuNWM0LjgtNy43LDctMTYuMyw2LjgtMjQuOGMtMTMuOC05LjMtMzEuMy04LjQtNDUuOC03LjcgICBjLTkuNSwwLjUtMTcuOCwwLjktMjMuMi0xLjdjLTAuMSwwLjEtMC4yLDAuMy0wLjMsMC40Yy0xLDEuNy0yLDMuNC0yLjksNS4xQzI4LjIsNDkuNywzMy44LDUzLjksMzkuOCw1Ny42eiIvPgoJPHBhdGggZD0iTTI2LjIsODguMmMzLjMsMiw2LjcsMy42LDEwLjIsNC43Yy0zLjUtNi4yLTYuMy0xMi42LTguOC0xOC41Yy0zLjEtNy4yLTUuOC0xMy41LTktMTcuMmMtMS45LDgtMiwxNi40LTAuMywyNC43ICAgQzIwLjYsODQuMiwyMy4yLDg2LjMsMjYuMiw4OC4yeiIvPgoJPHBhdGggZD0iTTMwLjksNzNjMi45LDYuOCw2LjEsMTQuNCwxMC41LDIxLjJjMTUuNiwzLDMyLTIuMyw0Mi42LTE0LjZDNjcuNyw3Niw1Mi4yLDY5LjYsMzcuOSw2MC43QzMyLDU3LDI2LjUsNTMsMjEuMyw0OC42ICAgYy0wLjYsMS41LTEuMiwzLTEuNyw0LjZDMjQuMSw1Ny4xLDI3LjMsNjQuNSwzMC45LDczeiIvPgo8L2c+Cjwvc3ZnPg==',
  }}
/>`

### PR DESCRIPTION
**Pull request by marlenecota**
Fixes #4669

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7198)

### CODE REVIEW

File: packages/playground/Samples/image.tsx [hunk 1]
```diff
@@ -51,6 +54,8 @@ export default class Bootstrap extends React.Component<
       imageUri = smallImageUri;
     } else if (value === 'large') {
       imageUri = largeImageUri;
+    }else if (value === 'data-svg') {
```
Comment (asklar) [inline packages/playground/Samples/image.tsx:57]: nit, spacing :)
```suggestion
    } else if (value === 'data-svg') {
```

File: vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp [hunk 2]
```diff
@@ -140,7 +140,11 @@ void ReactImage::Source(ReactImageSource source) {
     if (((scheme == L"http") || (scheme == L"https")) && !source.headers.empty()) {
       source.sourceType = ImageSourceType::Download;
     } else if (scheme == L"data") {
-      source.sourceType = ImageSourceType::InlineData;
+      if (source.uri.find("image/svg") != std::string::npos) {
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:143]: should there be some more parsing of what the url pieces are? e.g. what if they have a url that has that string in it?
`http://foo/bar/image/svg/myimage.svg` ?

**Review by asklar — APPROVED** [review]

File: vnext/Microsoft.ReactNative/Views/Image/ReactImage.h [hunk 3]
```diff
@@ -13,7 +13,7 @@
 
 namespace react::uwp {
 
-enum class ImageSourceType { Uri = 0, Download = 1, InlineData = 2, Svg = 3 };
+enum class ImageSourceType { Uri = 0, Download = 1, InlineData = 2, Svg = 3, SvgInlineData = 4 };
```
Comment (asklar) [inline vnext/Microsoft.ReactNative/Views/Image/ReactImage.h:16]: this could be split into two types: ImageSourceType { Uri, Download, Inline } and ImageFormat { Bitmap, Svg }
What's the difference between Download and Uri ?

File: packages/playground/Samples/image.tsx [hunk 4]
```diff
@@ -16,6 +16,9 @@ const smallImageUri =
 const dataImageUri =
   'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg==';
 
+const dataImageSvg =
+  'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4gPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyOCAyOCIgZmlsbD0ibm9uZSI+PHBhdGggZD0iTTEzLjEyNSAwSDBWMTMuMTI1SDEzLjEyNVYwWiIgZmlsbD0iI0YyNTAyMiI+PC9wYXRoPjxwYXRoIGQ9Ik0yOCAwSDE0Ljg3NVYxMy4xMjVIMjhWMFoiIGZpbGw9IiM3RkJBMDAiPjwvcGF0aD48cGF0aCBkPSJNMTMuMTI1IDE0Ljg3NUgwVjI4SDEzLjEyNVYxNC44NzVaIiBmaWxsPSIjMDBBNEVGIj48L3BhdGg+PHBhdGggZD0iTTI4IDE0Ljg3NUgxNC44NzVWMjhIMjhWMTQuODc1WiIgZmlsbD0iI0ZGQjkwMCI+PC9wYXRoPjwvc3ZnPiA=';
```
Comment (jonthysell) [inline packages/playground/Samples/image.tsx:20]: Such a beautiful image. I expecially like the `I+PHBhdGggZD0`

File: vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp (hunk 2 above)
Comment (jonthysell) [reply vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp:143]: You should probably just check that the string starts with `data:image/svg+xml;`

**Review by jonthysell — APPROVED** [review]

**Comment by rozele** [comment]
This is really cool. I wonder if there's a way we can easily break out the SVG support into it's own component in some way so future source formats can be supported more easily (e.g., I have an example working against libwebp [here](https://github.com/rozele/react-native-windows/blob/webp/vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp#L342-L362)). Thoughts @marlenecota @asklar?
