### PR TITLE
fix(BaseViewManager): Remove dependency on WinRTXamlToolkit

### LINKED ISSUE #1214: Remove dependency on WinRTXamlToolkit
We only use it for rectangular clipping, which is easy enough to implement.

### PR DESCRIPTION
**Pull request by rozele**
The `SetClipToBounds` property from `WinRTXamlToolkit` is too simple to implement to justify the dependency. Also, the approach that uses dimensions seems to be a bit less complex that relying on both a XAML dependency property and the SizeChanged event.

Fixes #1214

### CODE REVIEW

File: Libraries/Components/Picker/PickerWindows.js [hunk 1]
```diff
@@ -44,10 +44,10 @@ var PickerWindows = React.createClass({
...
     selected: PropTypes.number,
     selectedValue: PropTypes.any,
-    enabled: ReactPropTypes.bool,
-    onValueChange: ReactPropTypes.func,
-    prompt: ReactPropTypes.string,
-    testID: ReactPropTypes.string,
+    enabled: PropTypes.bool,
+    onValueChange: PropTypes.func,
+    prompt: PropTypes.string,
+    testID: PropTypes.string,
```
Comment (rozele) [inline Libraries/Components/Picker/PickerWindows.js]: This should be a separate PR.
