### PR TITLE
Fix JSValue memory leak in move constructor

### LINKED ISSUE #7827: Memory leak in JSValue
## Environment
  "name": "react-native",  "version": "0.63.3"
  "name": "react-native-windows", "version": "0.63.4"

- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug
- I checked memory consumption by Diagnostic Tool->Memory usage. I made memory dump before loop and after 10000 iterations, and compare them.
- Actually 2 memory leaks here. 1 = 120 bytes, 2 = 16 bytes. Stack call for both of them you can see on the screenshots. 

## Steps To Reproduce

 int i = 0;
 for (; i < 10000; ++i)
            {
                JSValueArray ar;
                JSValueObject v0{ {"X", 0} };
                JSValue val = JSValue(std::move(v0));
                ar.push_back(std::move(val));
                ar.push_back(JSValue("Test"));
            }

## Expected Results
No any memory leaks.

## Snack, code example, screenshot, or link to a repository:
Screenshot (38)
Leak1
Leak2

### PR DESCRIPTION
**Pull request by vmoroz**
The `JSValue` move constructor did not call the destructors for Object, Array, and String types. As a result, some collection artifacts were not correctly destroyed. They were most probably used only for debugging.

The fix is simple: call the `other` destructor in the move constructor. After the call the `other` becomes a `JSValue::Null` value.

Thanks a lot to @OleksandrDorosh who found and  reported the issue!

Fixes #7827

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7859)

### CODE REVIEW

File: vnext/Microsoft.ReactNative.Cxx/JSValue.cpp [hunk 1]
```diff
@@ -439,13 +439,13 @@ void JSValueArray::WriteTo(IJSValueWriter const &writer) const noexcept {
 JSValue::JSValue(JSValue &&other) noexcept : m_type{other.m_type} {
   switch (m_type) {
     case JSValueType::Object:
-      new (&m_object) JSValueObject(std::move(other.m_object));
+      new (std::addressof(m_object)) JSValueObject(std::move(other.m_object));
```
Comment (asklar) [inline vnext/Microsoft.ReactNative.Cxx/JSValue.cpp:442]: any reason to use placement new + addressof instead of something like `m_object = std::move(other.m_object)` (same elsewhere)

**Review by asklar — APPROVED** [review]
fix seems fine to me, consider simplifying the assignment if possible

**Comment by asklar** [comment]
I prob wouldn't go down to 62, maybe not even 63, since this isn't security related. @microsoft/react-native-windows-backport-triage

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
> I prob wouldn't go down to 62, maybe not even 63, since this isn't security related. @microsoft/react-native-windows-backport-triage

63 will be used by anyone also relying on macos. This seems critical enough to me to want to fix it there. I'm not confident 0.62 is  building in CI at the moment.

**Comment by asklar** [comment]
well, 63 isn't building in CI right now either :D

**Comment by NickGerleman** [comment]
> well, 63 isn't building in CI right now either :D

We probably need to fix that... Office will be there until react-native-macos 0.64.

File: vnext/Microsoft.ReactNative.Cxx/JSValue.cpp (hunk 1 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative.Cxx/JSValue.cpp:442]: These are not real fields - these are part of a union. So, in constructor they are just like some memory initialized with 0. Doing an assignment may crash because we did not run default constructors there yet, and running destructors as a part of the assignment is not valid.

**Review by dannyvv — APPROVED** [review]

**Comment by dannyvv** [comment]
@vmoroz : Let me know if you need help with 0.63 once the PR is in.

**Review by jonthysell — APPROVED** [review]

**Comment by NickolayGerasimenko** [comment]
@vmoroz Why can't we just remove these two lines from move ctor and that is it? Why do we need explicitly call `other` dtor here instead of let runtime to call it in natural way when it needs it?
` other.m_type = JSValueType::Null;`
` other.m_int64 = 0;`
`}`

**Comment by vmoroz** [comment]
> @vmoroz Why can't we just remove these two lines from move ctor and that is it?
> ` other.m_type = JSValueType::Null;`
> ` other.m_int64 = 0;`
> `}`
> Why do we need explicitly call `other` dtor here instead of let runtime to call it in natural way when it needs it?

@NickolayGerasimenko, you are right: we do not need to run the destructor on `other`. It will be destroyed later anyway. The main reason I did it in this PR is to keep the same observable side effects. Previously the `other` JSValue was always becoming JSValueType::Null. If we skip calling the destructor, the `other` value will keep its type. It is most probably a desirable behavior, but it may have unexpected results in the previously published versions where I want this fix to be ported.
I have created Issue #7873  to remove it in future versions starting from 0.65.

**Comment by NickolayGerasimenko** [comment]
@vmoroz Is this issue exist on Mac as well ?
